### ISSUE TITLE
Transparent PBR terrain has noise on minimap

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#1027]
## Test plan

See, "Minimap" in https://github.com/secondlife/viewer/blob/release/materials_featurette/doc/testplans/pbr_terrain_composition.md

**Comment by cosmic-linden** [comment]
Some day the minimap tiles will be rendered with a shader, but that day is not today.

**Comment by cosmic-linden** [comment]
@irinabproductengine Added test plan to original post in ticket

**Comment by dmytrohproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of [secondlife/iqa#231](https://github.com/secondlife/iqa/issues/231).
