### ISSUE TITLE
WebRTC: Clicking when changing audio devices.

### ISSUE THREAD

**Issue by roxanneskelly** [secondlife/viewer#1037]
### Environment

Second Life Test 7.1.4.8351851435 (64bit)
Release Notes

You are at 150.6, 186.8, 36.9 in webRTC1 located at simhost-0142872bd2be1d5c3.aditi
SLURL: secondlife://Aditi/secondlife/webRTC1/151/187/37
(global coordinates 259,991.0, 245,435.0, 36.9)
WebRTC-Voice 2024-03-15.8291114706
Release Notes

CPU: AMD Ryzen 9 5900HX with Radeon Graphics         (3293.82 MHz)
Memory: 15792 MB
OS Version: Microsoft Windows 10 64-bit (Build 19044.3086)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 30.0.15.1278
OpenGL Version: 4.6.0 NVIDIA 512.78

Window size: 1655x848
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Advanced Lighting Model: Enabled
Texture memory: 7273MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/384 (0.0%)
March 22 2024 16:34:39

### Description

When selecting different audio devices in the WebRTC viewer, there's a click.  This happens on both Windows and Mac.

### Reproduction steps

1. Open Preferences
2. Select 'Sound & Media'
3. Press 'Voice Input/Output Devices'
4. Note a click.
5. Select devices.
6. Note clicks.

**Comment by kylelinden** [comment]
Added to new WebRTC Milestone

**Comment by roxanneskelly** [comment]
Unfortunately, starting rendering on the speaker (at least on the tuning device) causes a click, so for now, I've disabled rendering.  I may have to re-enable it and find some other way of resolving this issue if we use the webrtc mechanism for echoback for voice tuning.  I'll tackle that if/when that comes.
