### ISSUE TITLE
Auto-exposure quality pass

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1046]
### Test plan
1. 

### Description

Now that we have HDRI sky preview, take another pass at auto-exposure quality against a realistic sky.

See conversation in https://discord.com/channels/677442248157167619/681997089290715193/1221152654470676510

White object should not appear grey unless they are being silhouetted against a bright sky.

**Comment by RunitaiLinden** [comment]
Added debug setting "RenderDiffuseLuminanceScale" that controls an adjustment for luminance that's applied only to non-sky pixels during auto-exposure calcuations.  Lower values "darken" the measured luminance of non-sky pixels.  Initial value is 0.5, will send to discord testers for feedback.

**Comment by RunitaiLinden** [comment]
See discord conversation for side-by-side snapshots and discussion:

https://discord.com/channels/677442248157167619/681997089290715193/1223011149302464573

**Comment by georgebproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.5.8472515256 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/178.
