### ISSUE TITLE
Update boost to 1.84.0

### ISSUE THREAD

**Issue by bennettgoble** [secondlife/viewer#1057]
Update boost from 1.81.0 (2022/12) to 1.84.0 (2023/12) and build it with the `json` module.

- [1.84.0 Release Notes](https://www.boost.org/users/history/version_1_84_0.html)
- [1.83.0 Release Notes](https://www.boost.org/users/history/version_1_83_0.html)
- [1.82.0 Release Notes](https://www.boost.org/users/history/version_1_82_0.html)

## 3p approach

Boost shifted its 160+ folder module directory between versions 1.81.0 and 1.84.0. This poses a problem for our 3p-boost repository as our in-tree vendoring strategy is not compatible with git's rename resolution. As a solution: we should create a new 3p-boot repository that a git submodule containing boost:

https://github.com/secondlife/3p-boost-new

This new 3p repo will not contain the prior boost repo's history, making it significantly lighter (It doesn't have hundreds of MB of boost versions in its objects.) and will make updating boost simpler: `cd` into the boost directory, and checkout the desired version.

```[tasklist]
### Tasks
- [x] Bump 3p-boost to 1.84.0
- [x] Update dependent: 3p-colladadom
```

**Comment by AtlasLinden** [comment]
Passing QA as no issues were spotted through the latest viewer regression test.
