### ISSUE TITLE
Mirrors should be disabled when Graphics setting is set to Low

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1059]
### Environment

Second Life Release 7.1.4.8270899680 (64bit)
Release Notes

You are at 168.0, 38.5, 23.6 in Rumpus Room 2048 located at simhost-01129fe6e38889eb3.aditi
SLURL: secondlife://Aditi/secondlife/Rumpus%20Room%202048/168/38/24
(global coordinates 36,520.0, 14,118.5, 23.6)
PMFP 2024-02-08.7835620080
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4170)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 3840x2066
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 64m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 0
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (18.3% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 223/10,861 (2.1%)
March 26 2024 14:43:53

### Description

Mirrors should be disabled when Graphics setting is set to Low because graphics challenged machines need all the frames they can get.

### Reproduction steps

1. Set Preferences > Graphics > Quality & speed slider to Low.
2. Verify Advanced menu > Debug Settings > RenderMirrors is False

**Comment by Dan-Linden** [comment]
Reopened on 7.1.7.8852879962.
After setting Graphics quality slider to low, the Mirrors checkbox is still checked in Advanced Graphics Preferences.
![Second Life 4_29_2024 5_29_45 AM](https://github.com/secondlife/viewer/assets/119471733/bccde960-c3b5-440a-8ffc-5ec6f4228229)

**Comment by katerynamproductengine** [comment]
Failed QA.
After setting Graphics quality slider to low, the Mirrors checkbox is unchecked automatically in Advanced Graphics Preferences as expected. But this checkbox can be checked manually in Low Graphic.

Could you please clarify at what graphics setting the Mirrors checkbox should be enabled automatically ? Now it turns on from the high setting, is this expected ?
Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of secondlife/iqa#231.

**Comment by Dan-Linden** [comment]
The Mirrors checkbox will be enabled automatically for High and above.

Based on your results:
after setting Graphics quality slider to low, the Mirrors checkbox is unchecked automatically 
and 
mirrors checkbox turns on from the high setting
I'm going to pass QA on this.
