### ISSUE TITLE
Display Proper Pricing for new 2k Texture uploads

### ISSUE THREAD

**Issue by brad-linden** [secondlife/viewer#1081]
As implemented in secondlife/server#798, texture upload pricing is now variable according to the account's premium status and the texture resolution. 

### 1) Upload menu

Second Life's upload menu includes `(L$10)` in the upload texture option under `Build → Upload → Image (L$10)`. The pricing on this should be removed so that it reads `Build → Upload → Image`

<img alt="build_upload_image" src="https://github.com/secondlife/viewer/assets/151138/8e77765e-baa2-4f8a-83ac-61691825608e" width="300" />

_Remove the price from the image upload option so that it doesn't imply a static value._

### 2) Image upload preview floater

1. The price calculation should be updated to reflect large texture pricing (See https://github.com/secondlife/server/issues/798)

<img alt="texture_upload_preview" src="https://github.com/secondlife/viewer/assets/151138/691dfa4d-2444-454f-96cd-97445b84604d" width="300" />

### 3) Bulk image upload

When image are bulk uploaded through the `Build → Upload → Bulk...` option the resulting confirmation window needs to display the correct value:

<img alt="bulk_upload_confirmation" src="https://github.com/secondlife/viewer/assets/151138/cf8205e4-266e-4512-8a60-af866a944d6e" width="300" />

### 4) Material upload

Download [ORM.zip](https://github.com/secondlife/viewer/files/15205668/ORM.zip) and unzip it.
In Second Life choose Build menu > Upload > Material and choose ORM.gltf
The price calculation in the materials preview window reflect the large texture pricing.

### 5) Material via bulk upload

Download [ORM.zip](https://github.com/secondlife/viewer/files/15205668/ORM.zip) and unzip it.
In Second Life choose Build menu > Upload > Bulk and choose ORM.gltf
The price calculation in the materials preview window reflect the large texture pricing.

## Pricing

Getting the pricing to match between server and viewer is critical here, as we do not want users to ever be charged more than what they should. See "Implementation Details" under https://github.com/secondlife/server/issues/798 for a detailed explanation on pricing behavior for large textures.

## Test Plan

When preparing to upload a texture, the upload UI should display the accurate pricing prediction according to the table in secondlife/server#798

**Comment by akleshchev** [comment]
Other places that include price:
- Inventory (upload option)
- Material upload

**Comment by kylelinden** [comment]
Confirmed with Steeltoe that PE Dev may implement as depicted.

**Comment by katerynamproductengine** [comment]
**Results**: 

1) Upload menu
Passed QA.
Pricing in "Upload → Image" is removed.

2) Image upload preview floater
Passed QA.
The price calculation reflects the correct prices for light and large textures.

3) Bulk image upload
Passed QA.
When bulk uploading images using the "Build → Upload → Bulk" option the correct value is displayed in the confirmation window that appears.

4) Inventory (upload option)
Passed QA.
Pricing in "Upload → Image" is removed. The price calculation reflects the correct prices for light and large textures.

5) Material upload
Failed QA.

**Downloading large textures via Material does not show the correct price.**

Steps to reproduce:

1. Download [ORM.zip](https://github.com/secondlife/viewer/files/15205668/ORM.zip) and unzip it.
2. In Second Life choose Build menu > Upload > Material and choose ORM.gltf
3. Observe materials preview window.

Actual result:
Total upload fee: L$10

4. Click "save" button.

Actual result:
"You paid L$50 to upload" message appears. Balance decrease L$50.

**Downloading large textures via Bulk does not show the correct price.**

Steps to reproduce:

1. Download [ORM.zip](https://github.com/secondlife/viewer/files/15205668/ORM.zip) and unzip it.
2. In Second Life choose Build menu > Upload > Bulk and choose ORM.gltf

Actual result:
"This will upload 1 items at a total cost of L$10. Do you wish to continue with the upload?" message appears.

3. Click "Upload" button.

Actual result:
"You paid L$50 to upload" message appears. Balance decrease L$50.
 
Video is attached:

https://github.com/secondlife/viewer/assets/150451913/189c18c9-f6b8-4f38-8d35-0765b27f8507



Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of secondlife/iqa#231.
