### ISSUE TITLE
[WebRTC] Crash when adjusting someone elses mute/gain in a vivox region.

### ISSUE THREAD

**Issue by roxanneskelly** [secondlife/viewer#1102]
### Environment

Second Life Test 7.1.4.8414833386 (64bit)
Release Notes

You are at 101.8, 75.2, 28.8 in Hanley located at simhost-0268fa637d406630a.agni
SLURL: http://maps.secondlife.com/secondlife/Hanley/102/75/29
(global coordinates 261,990.0, 258,891.0, 28.8)
Second Life RC Ferrari 2024-03-18.8333615376
Release Notes

CPU: AMD Ryzen 9 5900HX with Radeon Graphics         (3293.81 MHz)
Memory: 15792 MB
OS Version: Microsoft Windows 10 64-bit (Build 19044.3086)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 30.0.15.1278
OpenGL Version: 4.6.0 NVIDIA 512.78

Window size: 1655x848
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Advanced Lighting Model: Enabled
Texture memory: 7273MB
Disk cache: Max size 1638.4 MB (100.7% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 0/3,642 (0.0%)
April 01 2024 10:24:25

### Description

When bringing up the dialog to adjust someone elses gain or mute status on a vivox region, the viewer crashes.

### Reproduction steps

1. Hover the mouse pointer over another avatar.
2. Click on the control that comes up.
3. Crash.

**Comment by roxanneskelly** [comment]
>	secondlife-bin.exe!LLWebRTCVoiceClient::sessionState::findParticipantByID(const LLUUID & id) Line 1189	C++
 	secondlife-bin.exe!LLWebRTCVoiceClient::getUserVolume(const LLUUID & id) Line 1563	C++
 	secondlife-bin.exe!LLVoiceClient::getUserVolume(const LLUUID & id) Line 747	C++
 	secondlife-bin.exe!LLInspectAvatar::updateVolumeSlider() Line 329	C++
 	secondlife-bin.exe!LLInspectAvatar::onOpen(const LLSD & data) Line 215	C++
 	secondlife-bin.exe!LLFloater::openFloater(const LLSD & key) Line 705	C++
 	secondlife-bin.exe!LLFloaterReg::showInstance(const std::string & name, const LLSD & key, int focus) Line 261	C++
 	secondlife-bin.exe!show_inspector(const char * inspector, const char * param, const LLUUID & source_id) Line 1264	C++
 	[Inline Frame] secondlife-bin.exe!boost::function4<void,LLUICtrl *,int,int,unsigned int>::operator()(LLUICtrl *) Line 763	C++
 	[Inline Frame] secondlife-bin.exe!boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke(boost::function<void __cdecl(LLUICtrl *,int,int,unsigned int)> &) Line 105	C++
 	[Inline Frame] secondlife-bin.exe!boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()(boost::function<void __cdecl(LLUICtrl *,int,int,unsigned int)> &) Line 90	C++

**Comment by roxanneskelly** [comment]
Fixed and in the webrtc-voice branch.

**Comment by maestrolinden** [comment]
I can't reproduce this crash on MacOS or Win10 with WebRTC viewer  7.1.4.8610505473 (64bit).   Changing the volume in either a webRTC version (WebRTC-Voice 2024-04-09.8610484336) or a Vivox region (Second Life Server 2024-03-18.8333615376) has the expected effect on the other user's incoming voice volume.  Likewise, muting or unmuting another agent via the "block voice" toggle has the intended effect.  Passes QA.
