### ISSUE TITLE
Remove xmlrpc-epi

### ISSUE THREAD

**Issue by bennettgoble** [secondlife/viewer#1111]
The xmlrpc-epi library is 15 years old and only used in two small areas: login and when buying land. Let's replace it with basic HTTP calls so that we no longer have to maintain it.

## Test Plan

Run test plans for the following:

- Login behavior
- Buying land flows

**Comment by bennettgoble** [comment]
Removing this dependency will simplify updating expat --as xmlrpc-epi is a dependent.

**Comment by akleshchev** [comment]
We can implement a LLSDSerialize::toXMLRPC() instead, but won't it be better to just get rid of XMLRPC entirely? What benefits does it have over LLSD or JSON that cause viewer<-> to use XMLRPC?

**Comment by bennettgoble** [comment]
@akleshchev I agree, it would be better to eliminate the need to do XML-RPC completely. I wonder if we add an alternative login method that used a basic JSON or LLSD POST over HTTP. We'd need to keep XML-RPC on the server side to support existing viewers, but at least the XML-RPC behavior could be eliminated from the client.

**Comment by akleshchev** [comment]
Created https://github.com/secondlife/server/issues/1195

**Comment by brad-linden** [comment]
I'm not sure that login is the only xmlrpc dependency, aren't there also some buy currency operations that go to an xmprpc endpoint?  probably will want something like what @akleshchev mentiond ( https://github.com/secondlife/viewer/issues/1111#issuecomment-2045691021 ) and serialize "RPC structured" llsd to xml and then manually send HTTP post to the endpoint

**Comment by LLGuru** [comment]
Done in https://github.com/secondlife/viewer/pull/1893

**Comment by akleshchev** [comment]
Fixing issue's state since it didn't go through testing (not that there is much to test)

Test plan:
1. Confirm login orks
2. Confirm buying land works

**Comment by igorlproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10516785745 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
