### ISSUE TITLE
Use attachment info to prevent accidental nudity

### ISSUE THREAD

**Issue by vir-linden** [secondlife/viewer#1117]
Server work in https://github.com/secondlife/server/issues/679 includes list of attachment asset ids in the appearance message. We should be able to use this information to help prevent accidental nudity, by keeping the avatar clouded until all expected attachments have rezzed fully.

**Comment by vir-linden** [comment]
This work should go in Maint A or later, since Maint A is the first viewer that contains support for the new message payload.

**Comment by vir-linden** [comment]
Related: viewer#676

**Comment by nat-goodspeed** [comment]
Prevent "wardrobe malfunction"

**Comment by beqjanus** [comment]
I hope that this is made optional. We will almost certainly make it so. We get far more complaints about the time it takes to "de-cloud" than we ever get about accidental nudity. If people are really that concerned then they need to wear BOM undies.

**Comment by akleshchev** [comment]
> I hope that this is made optional. We will almost certainly make it so. We get far more complaints about the time it takes to "de-cloud" than we ever get about accidental nudity.

The right solution is probably to add load priorities (ex: sort mSkinRequests by priority or avatar, the same for whatever requests attachments). So that avatars would load one at a time instead of all at once.

**Comment by vir-linden** [comment]
Grouping requests by avatar and requesting info for nearby avatars first should improve the declouding experience for everyone. 

How much people care about accidental nudity is certainly going to vary based on the person and the context, so if this check substantial slows down loading it might make sense to have a preference setting

**Comment by sldevel** [comment]
> I hope that this is made optional.

I, for one, will not even bother implementing this in the Cool VL Viewer... :-D

**Comment by akleshchev** [comment]
>I'm echoing Beq's and Henri's feedback for Kokua - time spent de-clouding is a major source of pain already

The whole point of getting attachment count was to reduce 'wait for unknown attachments' decloud time. Because now we know that no more attachments are pending thus no need to wait.

I can add a debug setting that would return those extra 30s wait time instead of checking attachment count, but it isn't practical.

**Comment by akleshchev** [comment]
For QA:
1. Please record avatar decloud time on an agent heavy region prior and after this change.
2. Confirm all agents decloud and don't get stuck as cloud indefinetely

**Comment by georgebproductengine** [comment]
Failed QA.
Verified on the Second Life Release 7.1.7.8993168213 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/226. After clearing cache some avatars have decloud time 120-150 seconds on testing build versus 20-40 seconds on production.

**Comment by akleshchev** [comment]
Looks like I missed some cases where attachments have null id(?).

**Comment by valeriiaaproductengine** [comment]
Passed QA.

On average, all avatars load correctly in a busy location after 50 seconds.

Verified on the Second Life Release 7.1.9.9473057952 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/260.

**Comment by akleshchev** [comment]
> On OSX, all avatars in the busy (http://maps.secondlife.com/secondlife/London%20City/90/192/23) location did not load completely. The check was carried out several times during an average of 10-20 minutes of stay at this place.

Did you check on default Relase? Code added in scope of this task is platform idnependent and I wasn't able to repro, all avatars loaded under a minute.

**Comment by valeriiaaproductengine** [comment]
Hi @akleshchev ! 
I checked the busy  (http://maps.secondlife.com/secondlife/London%20City/90/192/23) location on the Release  7.1.8.9375512768 build on OSX. Within about 2 minutes, all avatars were loaded. Thank you.

**Comment by AtlasLinden** [comment]
Let's review the decloud time in a DeltaFPS build. Moving milestone and sending to testing again.
