### ISSUE TITLE
GLTF Scene Import Prototype

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1126]
Add Develop->Render Tests->GLTF Scene Preview

Prototype loading and rendering of a simple GLTF scene (damaged helmet, for example).

Use currently selected object as a handle to the scene.

**Comment by RunitaiLinden** [comment]
Integrated.  Not sure on how we want to QA GLTF scene support during this stage of development, will follow up with Dan and Atlas.

**Comment by AtlasLinden** [comment]
Setting to Pending Release followed by closing as this _prototype_ has already been out in the wild since the promotion of Featurettes 7.1.8.9375512768 and it's possible to load in some GLTF models locally into the viewer.
Verified on both Win10 and Mac

**Comment by aiaustin** [comment]
Folks, the glTF models works fine in the WebRTC RC (Second Life Release 7.1.9.10084807842 ) but not in the Atlasaurus RC (Second Life Release 7.1.9.9981869229) or a lot of other in development viewers versions. I believe that RunotaiLinden is aware of the issue and what causes the problems.

See https://github.com/secondlife/viewer/issues/1873
