### ISSUE TITLE
On moving the build method to github.

### ISSUE THREAD

**Issue by AiraYumi** [secondlife/viewer#1135]
### Description

Do you think it's okay to move to github just for the build method, or what do you think?

**Comment by AiraYumi** [comment]
I think this is useful because it allows you to reflect changes in the compilation procedure due to code modifications.

**Comment by kylelinden** [comment]
Hello AiraYumi,

Please consider attending a public user group to discuss! https://community.secondlife.com/blogs/entry/6509-introducing-the-second-life-public-calendar/ 

Thanks

**Comment by Dan-Linden** [comment]
The "TPVD/Developers User Group" meeting is probably the best meeting to discuss this.
