### ISSUE TITLE
Terrain textures are not free. Discard them when done.

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#1163]
Especially with PBR terrain and 2K textures.

## Test plan

https://github.com/secondlife/viewer/blob/release/materials_featurette/doc/testplans/terrain_loading.md

**Comment by cosmic-linden** [comment]
Alternatively, don't use `setBoostLevel`

**Comment by cosmic-linden** [comment]
Separate ticket for not using `setBoostLevel`:

https://github.com/secondlife/viewer/issues/1169

**Comment by Dan-Linden** [comment]
Is there a test plan for this?

**Comment by cosmic-linden** [comment]
@Dan-Linden The essence of this is, "terrain should still load". I have linked a relevant test plan in the OP

**Comment by georgebproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/239.
