### ISSUE TITLE
The "google.com" string in the chat floater isn't displayed as a link

### ISSUE THREAD

**Issue by igorlproductengine** [secondlife/viewer#1180]
### Environment

Second Life Release 7.1.5.8472515256 (64bit)
Release Notes

You are at 11.0, 157.0, 21.6 in Product Engine 2 located at simhost-0c02dc844b4a49e20.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%202/11/157/22
(global coordinates 336,907.0, 307,357.0, 21.6)
Second Life Server 2024-03-18.8333615376
Release Notes

CPU: AMD Ryzen 5 3600 6-Core Processor               (3600.01 MHz)
Memory: 16334 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4170)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 2060/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.5212
OpenGL Version: 4.6.0 NVIDIA 552.12

Window size: 1920x1017
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 5186MB
Disk cache: Max size 1638.4 MB (2.7% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 

Packets Lost: 4/9,862 (0.0%)
April 10 2024 04:02:05

### Description

Please take a look at the Reproduction steps.

### Reproduction steps

1. Login to the viewer.
2. Open the Chat floater.
3. Input the "google.com" in the text field.
4. Press the "Enter" button.

**Actual result:** The "google.com" string in the chat floater isn't displayed as a link.
**Expected result:** The "google.com" string should be displayed as a link in the chat floater.

**Note:** 
This issue is reproduced on the production build. (7.1.5.8443591509)
This issue is reproduced with all types of chats and floaters.

Actual1:
![7894](https://github.com/secondlife/viewer/assets/150452270/a2a2c3a3-6294-4dd5-93dc-46c02395d23c)

**Comment by kylelinden** [comment]
Expected behavior. @Dan-Linden @AtlasLinden please update test plans

**Comment by Dan-Linden** [comment]
Test plan is at https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2696347816/FUI+URLs+Regression+Test+Plan
