### ISSUE TITLE
Mirror resolution does not change without a restart.

### ISSUE THREAD

**Issue by Geenz** [secondlife/viewer#1185]
### Environment

Second Life Test 7.1.6.241011703 (64bit)

### Description

Changing the mirror resolution at runtime does not apply without restarting the viewer.

### Reproduction steps

1. Stand in front of a mirror with mirrors enabled.
2. Change the `RenderHeroProbeResolution` debug setting.
3. Note that the resolution does not change.

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/239.
