### ISSUE TITLE
Add mirrors settings to Advanced Graphics Settings

### ISSUE THREAD

**Issue by Geenz** [secondlife/viewer#1191]
We don't have a good way to control mirrors and hero probe updates from the UI.  We need an advanced graphics preferences setup for this.

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/239.

The "Mirror" checkbox, "Mirror  Resolution" and "Mirror Update Rate" dropdowns are presented in the Advanced Graphics Settings.
