### ISSUE TITLE
Newly-created sculpted prims do not render until the next session

### ISSUE THREAD

**Issue by maestrolinden** [secondlife/viewer#1209]
### Environment

Second Life Release 7.1.5.8443591509 (64bit)
Release Notes

You are at 65.6, 39.7, 38.8 in Danger! Danger! located at simhost-0704ac148bb93a5a6.agni
SLURL: http://maps.secondlife.com/secondlife/Danger%21%20Danger%21/66/40/39
(global coordinates 261,186.0, 249,640.0, 38.8)
Second Life Server 2024-03-18.8333615376
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4170)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1645x1264
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (1.4% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 8/2,936 (0.3%)
April 11 2024 14:54:31

### Description

In the Maint-W Release viewer, if one rezzes a new box and sets it to be a sculpt from the build tool, the object stops rendering to the viewer (though observing viewers see it).  Additional instances of the object remain invisible until relog.  This issue also occurs if changing the sculpt map of an existing sculpt to a different sculpt map.

I suspect this issue has to do with the viewer trying to render the sculpted object progressively as the texture is fetched.

### Reproduction steps

1. Clear the viewer's cache, then log in. 
2. Rez a box
3. In the build tool's Object tab, set the type to 'Sculpted'
4. If the object starts rendering as the default apple-shaped sculpt, click on the sculpt map thumbnail and set it to another valid sculpt map from your inventory ('Banana' from Library worked for me)

Expected results:
The object should render as a sculpted object in steps (3) and (4).  

Actual results:
The object does not render in (3) or (4).  

Workaround: Open all the Sculpt Textures in the Library so they are cached. Relog and run the repro steps. The sculpties will work as expected.

**Comment by LLGuru** [comment]
- Fixed by https://github.com/secondlife/viewer/pull/1843

**Comment by igorlproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10516785745 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
