### ISSUE TITLE
[Workflows] cla.yaml references incorrect repo branch for the CLA document

### ISSUE THREAD

**Issue by FelixWolf** [secondlife/viewer#1214]
### Environment

N/A

### Description

Workflow currently references `master` instead of `main` for it's sourcing of the contributor license agreement. This may cause issues if the CLA is updated in the `main` (Default) repository, where the CLA bot will incorrectly reference a old version.
See: https://github.com/secondlife/viewer/blob/7507abb566fe90fb96f866418d68a3635baf9806/.github/workflows/cla.yaml#L22C11-L22C81

### Reproduction steps

N/A

**Comment by FelixWolf** [comment]
I'd create a PR for this but I don't want to mess up the CLA workflow by accident, considering it is important. I'd rather let someone who knows what they are doing change it.

**Comment by kylelinden** [comment]
@vir-linden please update appropriate milestone.
