### ISSUE TITLE
Bug in XMLPRC to LLSD parsing caused issues with LLSD arrays

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#1220]
### Description

During implementation of https://github.com/secondlife/viewer/issues/1081 it came out that viewer can't properly parse 2K texture upload benefits, investigation revealed a bug in XMLPRC. Issue was fixed in scope of https://github.com/secondlife/viewer/issues/1081, but it potentially affects other areas that needs to be fixed separately.

### Testing

Suspects that might have been affected:
- inventory-root
- login-flags
- buddy-list
- last look at and last position

Inventory, first time login, where avatar looks at after login and friend list require testing to make sure nothing broke.

**Comment by igorlproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.6.8666822239 (64bit) on Win10/OSX in the scope of [IQA#187](https://github.com/secondlife/iqa/issues/187).
