### ISSUE TITLE
Viewer tries to detach attachments in inventory on shutdown.

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#1253]
### Environment

Second Life Release 7.1.5.8443591509 (64bit)

### Description

Warning on shutdown:
2024-04-17T00:05:04Z WARNING #Inventory# newview/llviewerinventory.cpp(1495) remove_inventory_item : Tried to use inventory without AIS API

Viewer shouldn't be attempting to manipulate inventory on shutdown

### Reproduction steps

Login, then close viewer, check logs.

**Comment by AtlasLinden** [comment]
Moving to DeltaFPS and sending to testing

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.10.10708851543 (64bit) on Win10/OSX in the scope of [secondlife/iqa#326](https://github.com/secondlife/iqa/issues/326).
