### ISSUE TITLE
Material with a Masked alpha texture applied to an object makes it completely transparent

### ISSUE THREAD

**Issue by valeriiaaproductengine** [secondlife/viewer#1267]
### Environment

Second Life Release 7.1.6.8666822239 (64bit)
Release Notes

You are at 180.9, 66.3, 21.4 in Product Engine located at simhost-0b8467dd2eb270db7.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/181/66/21
(global coordinates 336,821.0, 307,266.0, 21.4)
Second Life Server 2024-03-18.8333615376
Release Notes

CPU: 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz (2611.2 MHz)
Memory: 16111 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4291)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.2879
OpenGL Version: 4.6.0 NVIDIA 528.79

Window size: 1920x1001
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 4095MB
Disk cache: Max size 1638.4 MB (3.5% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 0/1,888 (0.0%)
April 18 2024 02:13:42

### Description

See Reproduction steps

### Reproduction steps

1. Login to the Second Life Release 7.1.6.8666822239 (64bit).
2. Create a material in inventory.
3. Select any texture in inventory and apply it to "Base color" of the material.
4. Change the Alpha and Alpha Cutoff to 0.0 value and select the Masking mode.
5. Rez the cube and apply the material to the whole cube.

**Actual:** 
Material with a Masked alpha texture applied to an object makes it completely transparent.

**Expected:** The cube should not be transparent. Its color will be determined depending on the selected parameters of the "Base color", "Metallic-Roughness", "Emissive" and "Normal" settings.

**Additional :**
This issue is reproduced on Win10/OSX.
This issue was found when checking the https://github.com/secondlife/jira-archive-internal/issues/71091 ticket.
Also, if change the Alpha value from 0.000 to 0.010, the cube with the material ceases to be transparent.

Actual.png screenshot:
![actual](https://github.com/secondlife/viewer/assets/150451911/ef20e363-06fc-4ac7-b6d6-c123a5c57d61)

Expected.png screenshot:
![expected](https://github.com/secondlife/viewer/assets/150451911/6fb600b5-5cc9-42fe-856b-76cb33efe369)

**Comment by kylelinden** [comment]
From GLTF spec:
"When alphaMode is set to MASK the alphaCutoff property specifies the cutoff threshold. If the alpha value is greater than or equal to the alphaCutoff value then it is rendered as fully opaque, otherwise, it is rendered as fully transparent. alphaCutoff value is ignored for other modes."

**Comment by RunitaiLinden** [comment]
Turns out we are in fact off spec.  alpha cutoff of zero and base color factor alpha of zero should be visible, not invisible.

**Comment by RunitaiLinden** [comment]
Fixed in release/materials_featurette

Also unblocks testing of https://github.com/secondlife/jira-archive-internal/issues/71091

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/239.

<details><summary>OSX system info</summary>
<p>

CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (2200 MHz)
Memory: 16384 MB
OS Version: Mac OS X 12.6.0 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-4.8.101

</p>
</details> 


<details><summary>Win10 system info</summary>
<p>

CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (3302.39 MHz)
Memory: 16076 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4412)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5585
OpenGL Version: 4.6.0 NVIDIA 555.85

</p>
</details>
