### ISSUE TITLE
Add support for mirrors that don't render avatars.

### ISSUE THREAD

**Issue by Geenz** [secondlife/viewer#1271]
### Test plan
1. Create a mirror using the Mirror (Environment) option.

> ![image](https://github.com/secondlife/viewer/assets/119471733/c23a5bdb-7bdd-40da-8c75-075a66036ad6)

2. Verify your avatar and other avatars and their attachments do not reflect in the mirror. 
3. Verify everything besides avatars reflects in the mirror. 

### Description

Useful for clubs and builds with various polished surfaces (such as a near-mirror finish floor).

**Comment by sergiiiproductengine** [comment]
Could you please provide test plan for verifying this ticket?

**Comment by Dan-Linden** [comment]
Passed QA on 7.1.8.9375512768. Tested on Windows/OSX
