### ISSUE TITLE
GLTF Animation -- Nodes

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1285]
### Description

Add support for GLTF Node animations to GLTF Preview

**Comment by brad-linden** [comment]
It looks like the branch that these commits were in was abandoned.  Should this be moved back to ToDo?

**Comment by brad-linden** [comment]
never mind, I think I found it.  looks like they got sqashed: cadc1a02cc7289dabd368dd1a1d237c042e9f82e

**Comment by RunitaiLinden** [comment]
No QA needed.

**Comment by AtlasLinden** [comment]
Setting status to Pending Release
Only negative test cases performed. That is, no visible changes spotted outside of what can be accessed via the Develop menu.
