### ISSUE TITLE
Mirrors are offset on build 7.1.6.8757451456 

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1298]
### Environment

Second Life Release 7.1.6.8757451456 (64bit)
Release Notes

You are at 183.3, 20.5, 23.1 in Rumpus Room 2048 located at simhost-01129fe6e38889eb3.aditi
SLURL: secondlife://Aditi/secondlife/Rumpus%20Room%202048/183/21/23
(global coordinates 36,535.3, 14,100.5, 23.1)
PMFP 2024-04-13.8669470587
Release Notes

CPU: AMD Ryzen 9 5980HX with Radeon Graphics         (3293.82 MHz)
Memory: 15775 MB
OS Version: Microsoft Windows 10/11 64-bit (Build 22000.2538)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon RX 6800M

Windows Graphics Driver Version: 30.0.15020.1001
OpenGL Version: 4.6.14800 Core Profile Context 21.50.20.01 30.0.15020.1001

Window size: 1024x768
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 96m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 11474MB
Disk cache: Max size 1638.4 MB (38.2% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Not Connected
Packets Lost: 0/12,807 (0.0%)
April 22 2024 06:46:12

### Description

Reflection looks too low in a mirror, and when looking in some directions the mirror gets very fish-eye. 
This does not reproduce in the 7.1.5.8472515256 Featurettes RC

### Reproduction steps

1. Look at the mirror at secondlife://Aditi/secondlife/Rumpus%20Room%202048/185/20/23
2. Move the camera around.

Observe: The mirror does not behave as a mirror. See screenshots:
![Second Life 4_22_2024 6_46_42 AM](https://github.com/secondlife/viewer/assets/119471733/213c7410-3e08-4ff4-8a90-2c9a90ec7fcd)
![Second Life 4_22_2024 6_48_20 AM](https://github.com/secondlife/viewer/assets/119471733/9aab5e00-a4de-4c9b-bcf7-ecc43118d480)

**Comment by igorlproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.6.8790244846 (64bit) build in the scope of https://github.com/secondlife/iqa/issues/207.
The reflection in the mirror is shaken during the verification of this issue. I created a new ticket about it: https://github.com/secondlife/viewer-private/issues/232
