### ISSUE TITLE
The animation with null id is attempted to fetch

### ISSUE THREAD

**Issue by LLGuru** [secondlife/viewer#1331]
### Environment

Second Life Release 7.1.6.8745209917 (64bit)

### Description

Looking into the log after visiting locations with many people we see multiple lines of kind:
> LLKeyframeMotion::onInitialize : Attempted to fetch animation  with null id

### Reproduction steps

- Start the viewer
- Visit any location with many people
- Close the viewer
- Analyze the log

Actual behavior:
There are multiple lines in the log related to an animation with null id

Expected behavior:
There are no lines in the log related to an animation with null id

**Comment by dmytrohproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.7.8993168213 (64bit) on Win10/OSX in the scope of [secondlife/iqa#226](https://github.com/secondlife/iqa/issues/226).
