### ISSUE TITLE
BOOL to bool conversion leftovers: ternaries

### ISSUE THREAD

**Issue by marchcat** [secondlife/viewer#1333]
After replacing the `BOOL` macros with the proper `bool` type, we still have multiple occurrences of now-redundant code involving ternary operations. For example:
```
void LLFloaterEmojiPicker::showPreview(bool show)
{
    //mPreview->setIcon(nullptr);
    mDummy->setVisible(show ? false : true);
    mPreview->setVisible(show ? true : false);
}
```
They should be updated to reflect the correct boolean type.

## Test Plan

Non-testable. Build exists = accept.

**Comment by LLGuru** [comment]
Fixed in https://github.com/secondlife/viewer/pull/1416

**Comment by sergiiiproductengine** [comment]
<details><summary>Passed QA.</summary>
<p>

according provided test plan - "Non-testable. Build exists = accept."

</p>
</details> 


Verified on the Second Life Release 7.1.9.9620320242 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/266.
