### ISSUE TITLE
Mirrors cause 100% GPU utilization in empty scenes when enabled

### ISSUE THREAD

**Issue by DarlCat** [secondlife/viewer#1370]
### Environment

Second Life Release 7.1.5.8472515256 (64bit)
Release Notes

You are at 105.5, 152.6, 4,097.7 in Drogon located at simhost-06d6c896ef8ca5c8b.agni
SLURL: http://maps.secondlife.com/secondlife/Drogon/105/153/4098
(global coordinates 150,633.0, 257,177.0, 4,097.7)
Second Life Server 2024-03-18.8333615376
Release Notes

CPU: AMD Ryzen 7 3800X 8-Core Processor              (3900.26 MHz)
Memory: 65485 MB
OS Version: Microsoft Windows 10/11 64-bit (Build 22631.3447)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.5152
OpenGL Version: 4.6.0 NVIDIA 551.52

Window size: 1918x1024
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 9285MB
Disk cache: Max size 1638.4 MB (42.7% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 17/24,685 (0.1%)
April 30 2024 11:53:46

### Description

At a height of 4096 with mirrors enabled and no mirrors or probes within view distance my GPU usage spikes to 100%, but disabling mirrors restores normal GPU usage.

### Reproduction steps

1. Fly up in the sky with no objects, mirrors, or probes around
2. Enable mirrors
3. Observe absurdly high GPU usage and degraded FPS
4. Disable mirrors
5. Observe nominal idle GPU usage and FPS

**Comment by Geenz** [comment]
The release viewer has the same behavior, but this did give me an opportunity to further tighten up our probe selection and add some early outs to always skip rendering when we have no viable hero probes nearby.

**Comment by georgebproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/231.
