### ISSUE TITLE
[Featurettes] Occlusion Channel of ORM Maps Being Dropped on glTF Material Upload

### ISSUE THREAD

**Issue by Zanibar** [secondlife/viewer#1382]
### Test plan
1. Download [ORM.zip](https://github.com/secondlife/viewer/files/15205668/ORM.zip) and unzip it.
2. In Second Life choose Build menu > Upload > Material and choose ORM.gltf
3. Verify the material looks like the attached "correct ORM.png"
![correct ORM](https://github.com/secondlife/viewer/assets/119471733/bbd39e28-9ada-403e-96d7-615335a77c0c)

### Environment

Second Life Release 7.1.7.8903236980 (64bit)
Release Notes

You are at 121.1, 23.6, 10.2 in Fractal located at simhost-0bafefdd96f0a0b93.agni
SLURL: http://maps.secondlife.com/secondlife/Fractal/121/24/10
(global coordinates 151,417.0, 256,536.0, 10.2)
Second Life Preflight 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Core(TM) i7-14700K (3417.6 MHz)
Memory: 98060 MB
OS Version: Microsoft Windows 10/11 64-bit (Build 22631.3447)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon RX 6800

Windows Graphics Driver Version: 31.0.24027.1012
OpenGL Version: 4.6.0 Core Profile Context 24.3.1.240312

Window size: 2560x1017
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 16337MB
Disk cache: Max size 1638.4 MB (29.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 2/5,098 (0.0%)
May 01 2024 12:00:53

### Description

It appears that the Occlusion (Red) channel of ORMs are being dropped on upload. I didn't notice it at first until I was working with a material that explicitly needed it.
Latest Release:
![SecondLifeViewer_2024-05-01_13-27-41](https://github.com/secondlife/viewer/assets/91260002/e194c9f1-279b-4058-a243-a2a065b568c9)
Latest Featurettes:
![SecondLifeViewer_2024-05-01_13-36-06](https://github.com/secondlife/viewer/assets/91260002/091e655a-692d-41e4-81fd-46bc69040863)

### Reproduction steps

1. Attempt to upload a gltf material with known use of the occlusion channel
4. Compare ORM shown in the upload panel vs the source file from the glTF

**Comment by RunitaiLinden** [comment]
Fixed.  Flubbed the meaning of no occlusion image in a previous fix for local GLTF preview.

**Comment by vladyslavasproductengine** [comment]
Pass QA. 
Verified on the Second Life Release 7.1.8.9103842320 (64 bit) Win10/OSX in scope [IQA#221](https://github.com/secondlife/iqa/issues/221) .

**Comment by vladyslavasproductengine** [comment]
Pass QA  in scope [IQA#231](https://github.com/secondlife/iqa/issues/231).
