### ISSUE TITLE
Mesh Upload - Physics - Bounding Box is not working as expected.

### ISSUE THREAD

**Issue by KrsityKu** [secondlife/viewer#1418]
### Environment

Second Life Release 7.1.6.8745209917 (64bit)

### Description

When uploading a mesh, selecting Physics and Bound Box, should apply bounding box to all objects in the mesh, however, it only applies it to just one of them.

![image](https://github.com/secondlife/viewer/assets/120577588/e0ee53f2-6128-46b8-8556-b215cd3001cc)

I don't know which version caused this change, but it worked around a year ago. (I don't upload meshes too often).

Official viewer and Firestorm Beta viewer have this issue. Alchemy viewer applies bounding box to all parts.

### Reproduction steps

1. Build -> Upload -> Model and use this file (or any model with multiple objects): 
[TestSpheres.zip](https://github.com/secondlife/viewer/files/15233279/TestSpheres.zip)
2. In the physics tab of the mesh uploader, pick Bounding Box
3. Observe the preview - only the middle sphere has a bounding box and the log says:
PHYS Model GeoSphere001Mesh loaded
No physics model specified for GeoSphere003Mesh
No physics model specified for GeoSphere002Mesh

Expected result - all 3 spheres should have their own bounding box.

**Comment by LLGuru** [comment]
Fixed in https://github.com/secondlife/viewer/pull/1467
![image](https://github.com/secondlife/viewer/assets/124201357/df47080c-b7b8-4510-a38b-7c2dece643aa)

**Comment by valeriiaaproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.9.9473057952 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/260.
