### ISSUE TITLE
Names in Chat are shifted to the side

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#1420]
### Environment

Second Life Release 7.1.7.8980192090 (64bit)
Release Notes

You are at 118.0, 110.8, 22.6 in Pasta Cake located at simhost-08b3fdbedc477d3b3.agni
SLURL: http://maps.secondlife.com/secondlife/Pasta%20Cake/118/111/23
(global coordinates 332,150.0, 305,519.0, 22.6)
Second Life Server 2024-03-18.8333615376
Release Notes

CPU: 12th Gen Intel(R) Core(TM) i9-12900HK (2918.39 MHz)
Memory: 32440 MB
OS Version: Microsoft Windows 10 64-bit (Build 19044.3086)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.4659
OpenGL Version: 4.6.0 NVIDIA 546.59

Window size: 1278x1368
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 10000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 4095MB
Disk cache: Max size 1638.4 MB (2.2% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 2/2,432 (0.1%)
May 07 2024 07:07:29

### Description

Occurs on latest [Maint A build](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2315d4db0-a) 7.1.7.8980192090 for both Win and Mac
![image](https://github.com/secondlife/viewer/assets/114031241/dbecc08b-a58a-497e-bee6-cc6cd4273eae)

### Reproduction steps

1. Open Chat
2. Observe names for users, objects and locations

**Comment by akleshchev** [comment]
They are showing, but they are shifted to the side, all except first one
![image](https://github.com/secondlife/viewer/assets/117672381/69c678a6-59bf-4443-b3fb-ca4b4b079078)

**Comment by sergiiiproductengine** [comment]
OSX Failed QA.

Verified on the Second Life Release 7.1.7.8993168213 (64bit) in the scope of https://github.com/secondlife/iqa/issues/225.

The issue is not reproduced on Win10 but reproduced on OSX.

**Comment by valeriiaaproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.9.9473057952 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/260.
