### ISSUE TITLE
The environment changed immediately after clicking on the "Apply only to Myself" menu item in the inventory floater

### ISSUE THREAD

**Issue by igorlproductengine** [secondlife/viewer#1428]
### Environment

Second Life Release 7.1.7.8974243247 (64bit)
Release Notes

You are at 20.4, 193.3, 22.0 in Product Engine 2 located at simhost-0fd65f59a8c98f104.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%202/20/193/22
(global coordinates 336916.0, 307393.0, 22.0)
Second Life Server 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2600 MHz)
Memory: 16384 MB
OS Version: Mac OS X 14.4.1 Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-5.5.17

Window size: 1680x921
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (0.5% used)
HiDPI display mode: 0

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 8/12262 (0.1%)
May 08 2024 08:02:01

### Description

See reproduction steps.

### Reproduction steps

1. Login to the viewer.
2.  Open inventory. (ctrl+I)
3.  Click on the "+" button.
4. Select create a new Sky.
5. Open the "Fixed Environment" floater.
6. Change any setting to see effects from them immediately. (e.g. Blue Horizon)
7. Click the "Save" button and close the "Fixed Environment" floater.
8. Right-click on the edited new sky in the inventory floater and select "Apply only to Myself".

**Actual result:** The environment changed immediately after clicking on the "Apply only to Myself" menu item.
**Expected result:** The environment should be changed smoothly after clicking on the "Apply only to Myself" menu item.

**Note:** 
This issue is reproduced on Win10/OSX.
This issue is reproduced on the production build.(7.1.6.8745209917)

Actual: 
[Actual1.webm](https://github.com/secondlife/viewer/assets/150452270/bcd717dd-df34-4f4e-b245-56a1b87be7f1)

**Comment by AtlasLinden** [comment]
This is expected behaviour. Apply Only To Myself, selecting presets from World>Environment or opening EEP setting floater will show environment changes immediately.
Any changes made to parcel or region should still show the gradual EEP change.
