### ISSUE TITLE
Haze is missing from some EEP settings in Featurettes viewer

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1466]
### Environment

Second Life Release 7.1.7.9020640347 (64bit)
Release Notes

You are at 217.9, 46.2, 21.8 in By Design located at simhost-0ed1af4f6c09b0a7a.agni
SLURL: http://maps.secondlife.com/secondlife/By%20Design/218/46/22
(global coordinates 261,594.0, 246,830.0, 21.8)
Second Life Preflight 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4291)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1636x1283
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 2/6,772 (0.0%)
May 14 2024 08:20:52

### Description

The haze in this EEP setting looks very different in Featurettes than in Release.
<img width="1629" alt="Screenshot (20)" src="https://github.com/secondlife/viewer/assets/119471733/25b72c8c-3f97-4b66-9373-5091009dc71c">

### Reproduction steps

1. Get the EEP setting from the box at http://maps.secondlife.com/secondlife/Danger!%20Danger!/73/83/39
2. Apply the EEP setting to a parcel.
3. Compare how the Environment looks on Featurettes 7.1.7.9020640347 and Release 7.1.7.8974243247

Observed: The environment is very dark with no purple haze in the Featurettes viewer.

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/239.

<details><summary>OSX system info</summary>
<p>

CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (2200 MHz)
Memory: 16384 MB
OS Version: Mac OS X 12.6.0 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-4.8.101

</p>
</details> 


<details><summary>Win10 system info</summary>
<p>

CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (3302.39 MHz)
Memory: 16076 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4412)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5585
OpenGL Version: 4.6.0 NVIDIA 555.85

</p>
</details>
