### ISSUE TITLE
Remove offset at region edge for PBR terrain

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#1474]
Given work on PBR terrain texture transforms (see https://github.com/secondlife/viewer/issues/907 ), we should make sure the featurettes viewer has no visible offset which would interfere with the application of the transform.

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of [IQA #239](https://github.com/secondlife/iqa/issues/239).
During testing with different PBR materials (our own and from the library), no visual offset was observed at the boundaries of the regions.
See the attached ‘Expected - 7.1.8.9103842320.png’ screenshot.
<img width="1680" alt="Expected - 7 1 8 9103842320" src="https://github.com/secondlife/viewer/assets/136308794/1b10a8a9-6deb-4ce1-b154-10fe9d756b64">
