### ISSUE TITLE
The arrow keys don't move avatar with checked ‘Arrow keys always move me’ checkbox

### ISSUE THREAD

**Issue by katerynamproductengine** [secondlife/viewer#1479]
### Environment

Second Life Release 7.1.7.8944739879 (64bit)
Release Notes

You are at 178.5, 98.0, 21.5 in Product Engine located at simhost-01c8d8f6993b20562.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/179/98/21
(global coordinates 336819.0, 307298.0, 21.5)
Second Life Server 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (1600 MHz)
Memory: 16384 MB
OS Version: Mac OS X 13.5.1 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64
Graphics Card Vendor: Intel Inc.
Graphics Card: Intel(R) UHD Graphics 617

OpenGL Version: 4.1 INTEL-20.6.4

Window size: 922x779
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 96m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 1536MB
Disk cache: Max size 1638.4 MB (13.0% used)
HiDPI display mode: 0

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 0/6648 (0.0%)
May 15 2024 06:50:40

### Description

See reproduction steps

### Reproduction steps

Steps to reproduce:
1. Log in to the viewer.
2. Open Preferences floater.
3. Left-click on the Move & View tab.
4. Check ‘Arrow keys always move me checkbox’.

Actual result: The arrow keys do NOT move your avatar while focus is remained in the Preferences floater and also on other floaters except the Chat.
Expected result: The arrow keys always move your avatar.

Additional:
This issue is reproduced on Win10/OSX.
This issue was found according to test plan: https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2698117145/Viewer+Preferences+Test+Plan#7.-Move-&-View > 7.4.1 Arrow keys always move me > 2. Check ‘Arrow keys always move me checkbox’.
This issue is reproduced on Production.

**Comment by Dan-Linden** [comment]
I believe this option affects only Chat and IMs in the Conversations window. All other UI is unaffected by this option.
When the chat history pane has focus, the arrow keys will move the avatar rather than scroll the chat history. 
When the Nearby chat box has focus the arrow keys will move the avatar rather than move the cursor within the text field. 
Can Product confirm that this is the correct behavior? 
If it is correct, please assign back to me to update the test plan.

**Comment by Dan-Linden** [comment]
Updated https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2698117145/Viewer+Preferences+Test+Plan#7.4.1-Arrow-keys-always-move-me

**Comment by Dan-Linden** [comment]
Reviewed by Atlas. Closed.
