### ISSUE TITLE
Mirrors stops updating when the camera is pointed down a little.

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1494]
### Environment

Second Life Release 7.1.8.9103842320 (64bit)
Release Notes

You are at 60.7, 245.0, 22.9 in Rumpus Room 2050 located at simhost-01129fe6e38889eb3.aditi
SLURL: secondlife://Aditi/secondlife/Rumpus%20Room%202050/61/245/23
(global coordinates 36,412.7, 14,581.0, 22.9)
PMFP 2024-04-13.8669470587
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4291)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1560x1184
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/1,540 (0.0%)
May 16 2024 11:29:34

### Description

Mirrors stops updating when the camera is pointed down a little.
This is a new regression in build 7.1.8.9103842320, and did not exist in build 7.1.5.8472515256

### Reproduction steps

1. Look at a mirror reflection.
2. Point your camera down at about a 45° angle.

Observed: The reflection stops updating, and sometimes you can see an overhead view of yourself.

https://github.com/secondlife/viewer/assets/119471733/7de78a0a-219e-43ba-bfe8-41d0bca812ba

https://gyazo.com/1fc5409f732f73a11764f47d4c592c67

Expected: The mirror should continue to reflect the scene.

**Comment by Dan-Linden** [comment]
Reopened on Second Life Release 7.1.8.9357006492 (64bit)
SLURL: secondlife://Aditi/secondlife/Rumpus%20Room%202050/66/242/23
OS Version: Microsoft Windows 10 64-bit (Build 19045.4412)
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

I'm still seeing this: 

https://github.com/secondlife/viewer/assets/119471733/253fd183-f085-43fb-b766-68be8098f6b1

**Comment by Geenz** [comment]
@Dan-Linden This is not the same issue.  This is as different one that looks like probe stealing.

**Comment by Dan-Linden** [comment]
The original bug (the mirror stops updating) is fixed in 7.1.8.9375512768

I've filed a separate issue for the probe stealing at https://github.com/secondlife/viewer/issues/1643
