### ISSUE TITLE
Ambiance and Near Clip fields for a Mirror probe should be grayed out for Mirror (Everything)

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1497]
### Test plan
Test needed.
Update https://lindenlab.atlassian.net/wiki/spaces/QA/pages/edit-v2/3054436428#2.12-Mirrors-test-cases step 20 with expected behavior.

### Environment

Second Life Release 7.1.8.9103842320 (64bit)
Release Notes

You are at 9.8, 245.9, 22.9 in Rumpus Room 2050 located at simhost-01129fe6e38889eb3.aditi
SLURL: secondlife://Aditi/secondlife/Rumpus%20Room%202050/10/246/23
(global coordinates 36,361.8, 14,581.9, 22.9)
PMFP 2024-04-13.8669470587
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4291)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1560x1184
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/1,274 (0.0%)
May 16 2024 15:56:17

### Description

The Ambiance and Near Clip fields should be grayed out for Mirror (Everything)

### Reproduction steps

1. Create a Mirror (Everything)
2. Attempt to change the Ambiance and Near Clip

Observed: The Ambiance and Near Clip fields can be changed although they are meaningless for a mirror and have no effect.
![image](https://github.com/secondlife/viewer/assets/119471733/44ce3028-6b1e-414a-b363-c1f94c8740b1)

Expected: The Ambiance and Near Clip fields should be grayed out for Mirror (Everything) as they are for Mirror (Environment)
![image](https://github.com/secondlife/viewer/assets/119471733/fa8042a7-ff74-4923-9c46-d4aeb89b6434)

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.9.9620320242 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/266.
