### ISSUE TITLE
The Dynamic probe checkbox does not set or display the value correctly

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1506]
### Environment

Second Life Release 7.1.8.9103842320 (64bit)
Release Notes

You are at 233.7, 247.6, 23.0 in Bug Island 2 located at simhost-0bce1fdff42fd9e51.agni
SLURL: http://maps.secondlife.com/secondlife/Bug%20Island%202/234/248/23
(global coordinates 260,586.0, 249,592.0, 23.0)
Second Life Server 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4291)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1560x1184
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 17/66,871 (0.0%)
May 17 2024 08:12:38

### Description
When mirrors are disabled, a Dynamic probe checkbox is present in Edit tools that allows switching a probe between Static and Dynamic. This checkbox does not work.

Workaround: When mirrors are enabled, the UI for switching a probe between Static and Dynamic functions correctly.

### Reproduction steps

Test for setting the Dynamic flag:
1. Disable Mirrors: Uncheck the Mirror checkbox in Preferences > Graphics Advanced Settings.
2. Create a box. In the Features tab, click Reflection Probe, then OK, then OK
3. Enable the Dynamic checkbox, which is below the Reflection Probe checkbox.
4. Deselect the Reflection Probe then select it again.

Observed: The Dynamic checkbox is unchecked.

Expected: The Dynamic checkbox should be checked.

5. Enable Mirrors: Check the Mirror checkbox in Preferences > Graphics Advanced Settings.
6. Select the Reflection Probe you previously made.
7. Notice that the Probe Update is Static. This shows that the Dynamic checkbox did not set the Dynamic flag.

Test for displaying the Dynamic flag:
1. Enable Mirrors: Check the Mirror checkbox in Preferences > Graphics Advanced Settings.
2. Create a box. In the Features tab, click Reflection Probe, then OK, then OK
3. From the Probe Update menu, choose Dynamic.
4. Deselect the Reflection Probe then select it again.
5. Verify the Reflection Probe is still Dynamic.
6. Disable Mirrors: Uncheck the Mirror checkbox in Preferences > Graphics Advanced Settings.
7. Select the Reflection Probe

Observed: The Dynamic checkbox is unchecked. This shows that the Dynamic checkbox does not display the current Dynamic flag.

**Comment by akleshchev** [comment]
There is no longer any 'Dynamic probe' checkboxes in GLTF development branch (instear there is a dropbox), should this be closed?

**Comment by Dan-Linden** [comment]
@akleshchev If you disable mirrors, eg. Set Graphics Quality to Mid, then the edit tool UI changes, and the drop down is replaced with a "Dynamic" checkbox. I still see it in Develop 7.1.9.9618671499
![image](https://github.com/secondlife/viewer/assets/119471733/c5d77d2b-6a74-438f-9178-553e0d10e2b0)

**Comment by Dan-Linden** [comment]
Reopening. This fix has not shipped yet. I don't know why github closed this.

**Comment by akleshchev** [comment]
> Reopening. This fix has not shipped yet. I don't know why github closed this.
Github sometimes does that when an attached pull request closes.

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10516785745 (64bit) on Win11/OSX in the scope of [IQA #316](https://github.com/secondlife/iqa/issues/316).
