### ISSUE TITLE
Actual Mirror Update Rate seems lower than the setting.

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1517]
### Environment

Second Life Release 7.1.8.9103842320 (64bit)
Release Notes

You are at 236.5, 247.3, 23.0 in Bug Island 2 located at simhost-0bce1fdff42fd9e51.agni
SLURL: http://maps.secondlife.com/secondlife/Bug%20Island%202/236/247/23
(global coordinates 260,588.0, 249,591.0, 23.0)
Second Life Server 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4291)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1560x1184
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 54/325,155 (0.0%)
May 17 2024 11:22:59

### Description

When the viewer is getting 60 FPS and the Mirror Update Rate is set to Every 3rd Frame, I would expect the mirror to update 20 times per second. It appears to update closer to 5 times per second.

### Reproduction steps

1. Make a mirror
2. Adjust the Mirror Update Rate to Every 2rd Frame in Preferences > Graphics > Advanced Settings.
3. Verify the update rate for the mirror is about half of the framerate.

Observed: The mirror update rate looks lower than half of the framerate.
(This video demonstrates Every 3rd Frame, then Every 2nd Frame)

https://github.com/secondlife/viewer/assets/119471733/a41fdac6-f3b5-4169-92eb-11b7ac746b2f

Expected: The mirror update rate should be close to half of the framerate

**Comment by brad-linden** [comment]
is this integrated?

**Comment by igorlproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.9.9620320242 (64bit) on Win10/OSX in scope https://github.com/secondlife/iqa/issues/266.
