### ISSUE TITLE
PBR reflections in Linden Home Houseboat show internal steps as flattened

### ISSUE THREAD

**Issue by aiaustin** [secondlife/viewer#1522]
### Environment

Second Life Release 7.1.8.9103842320 (64bit)
Release Notes

You are at 68.2, 16.5, 22.0 in Damiano located at simhost-0f598e8cc0068c39c.agni
SLURL: http://maps.secondlife.com/secondlife/Damiano/68/17/22
(global coordinates 262,212.0, 249,105.0, 22.0)
Second Life Server 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (3491.59 MHz)
Memory: 32713 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4412)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 980/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.5244
OpenGL Version: 4.6.0 NVIDIA 552.44

Window size: 1151x813
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 256m
Bandwidth: 2400kbit/s
LOD factor: 2
Render quality: 6
Texture memory: 4095MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 26/47,746 (0.1%)
May 20 2024 01:59:16

### Description

I am trying the latest Materials Featurettes RC (Second Life Release 7.1.8.9103842320) and inside my LL Bellisseria Houseboat I have a simple box reflection probe that just about fits the box shape of the interior.  But when I look at a shiny surface some items in the reflection are flattened, like steps, with a shadow below them, not at all like the actual items in the room. Note this is a standard RP (dynamic) on a simple PBR shiny surface, not a mirror setup. See attached image...

![LL-Houseboat-Internal-Steps-Direct-View](https://github.com/secondlife/viewer/assets/4630885/7943b505-9a7d-42a7-a169-68cb158bbb5e)
![Reflection_has_flattened_items-2](https://github.com/secondlife/viewer/assets/4630885/583c975d-9041-4843-9fb5-1257bcf621f8)
![Reflection_has_flattened_items-1_](https://github.com/secondlife/viewer/assets/4630885/89426f50-7719-46bd-abeb-40c4f02f856d)

May be worth checking other types of Linden Homes for similar issues too.

### Reproduction steps

1. Go to a Linden Home Houseboat internally
2. Look at the internal steps
3. Set up a suitable Reflection probe for the internal area (e.g. a box)
4. Set up a reflective surface somewhere suitable.
5. Look at the reflection and note the internal steps are flattened and float a metre off the ground with a shadow underneath. Note this is nothing like the actual room view of the steps.

(LOD handling was a possible explanation offered on the Discord Second Life Discussion Group)

**Comment by aiaustin** [comment]
A related suggestion is to improve Linden Homes for PBR use by adding in suitable box shaped reflection probes for the internal volumes to every home style.

**Comment by KrsityKu** [comment]
> A related suggestion is to improve Linden Homes for PBR use by adding in suitable box shaped reflection probes for the internal volumes to every home style.

There's a Canny for that part already https://feedback.secondlife.com/ldpw/p/update-linden-homes-and-their-regions-for-pbr

**Comment by kylelinden** [comment]
Hi AI,
We were unable to reproduce the issue on any of the Linden Home stairs. Please reopen this issue if you can continue to reproduce the problem.
Thanks!

**Comment by aiaustin** [comment]
Using Second Life Release 7.1.8.9375512768 I have set up a large reflective surface at this location in my Houseboat at http://maps.secondlife.com/secondlife/Damiano/69/18/22 to make the issue more obvious. Please pop over there and see what is happening. Look at various angles to the reflective surface to see the internal Houseboat stairs reflection is flattened. This is using the normal box reflection probe for the space, NOT a mirror probe of any kind.

Can you reopen this issue, as I don't seem to be able to so that Kyle.

![Stairs-Flattened-in-Reflection](https://github.com/secondlife/viewer/assets/4630885/d32350d2-c038-424d-837d-14bb74bdd7b9)

**Comment by KrsityKu** [comment]
I'm only on this tracker because I've shared the relevant link in a previous post... but - I had a quick look - I think this is working as intended, the stairs are basically under the centre of the reflection probe, therefore the probe renders them from the top, and that is what the probe would see.

Also reflection probes are not meant to be used as mirrors for exactly this type of reason. They have a specific projection that is used to provide ambient light and diffuse reflection to the scene.

**Comment by aiaustin** [comment]
ah
