### ISSUE TITLE
Consistent crash on exit with Lua viewer

### ISSUE THREAD

**Issue by vir-linden** [secondlife/viewer#1534]
Steps:
- Build RelWithDebInfo viewer on windows and run it in the VS2022 IDE
- Immediately pick Exit in the first menu
- Crash in singleton deletion

**Comment by vir-linden** [comment]
Call stack:

![Image](https://github.com/secondlife/viewer/assets/60274682/21889726-b7ad-4147-bfcc-0132b93dc818)

**Comment by nat-goodspeed** [comment]
fwiw I don't believe this has anything to do with the Lua viewer specifically. It has to do with destroying LLImageGLThread, which is unchanged by the release/luau-scripting branch. Continuing to dig nonetheless.

**Comment by vir-linden** [comment]
It's fine to bounce it to maint if it repros on default viewer
