### ISSUE TITLE
Standard bake textures can be applied to terrain textures

### ISSUE THREAD

**Issue by DmitrySProductengine** [secondlife/viewer#1552]
### Environment

<details><summary>Environment</summary>
<p>

Second Life Release 7.1.8.9103842320 (64bit)
Release Notes

You are at 114.3, 115.7, 22.8 in Product Engine 3 located at simhost-0d21bec691a88cebe.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%203/114/116/23
(global coordinates 336754.0, 307060.0, 22.8)
Second Life Server 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2600 MHz)
Memory: 16384 MB
OS Version: Mac OS X 13.6.7 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Mon Apr 22 20:54:28 PDT 2024; root:xnu-8796.141.3.705.2~1/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-4.14.1

Window size: 1680x1050
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (1.3% used)
HiDPI display mode: 0

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/586 (0.0%)
May 23 2024 05:06:38

</p>
</details> 

### Description

This issue was found during Ad hoc testing in the scope of [IQA #239](https://github.com/secondlife/iqa/issues/239).
This issue is reproduced on Win10 and OSX.

This issue is not reproduced on the current release 7.1.7.8974243247 build.
Standard bake textures can be selected, but when applying them to terrain textures, it gives an image mismatch error.
See the attached ‘Expected - current release 7.1.7.8974243247.png’ screenshot:
<img width="1680" alt="Expected - current release 7 1 7 8974243247" src="https://github.com/secondlife/viewer/assets/136308794/ec2fed76-4935-4cce-bff1-e050f10db367">

This may be a new expected behavior, but this bug is similar to the existing one (https://github.com/secondlife/viewer/issues/1195), and perhaps there is no need to use a baked texture here either.
Also, not the bake textures specified in the attached universal are used - but standard pictures of bake textures.

See the attached ‘Actual - 7.1.8.9103842320.png’ screenshot:
<img width="1680" alt="Actual - 7 1 8 9103842320" src="https://github.com/secondlife/viewer/assets/136308794/3c030e3a-4c9d-4c03-9edd-1bc44669d7d8">

When using PBR materials, bake textures can also be selected, but when you try to use them, they also issue a warning about the invalid material.
See the attached ‘PBR materials - 7.1.8.9103842320.png’ screenshot:
<img width="1680" alt="PBR materials - 7 1 8 9103842320" src="https://github.com/secondlife/viewer/assets/136308794/d601120a-2821-4fdb-a9f9-dfdb52a839be">

### Reproduction steps

1. Download and install the Second Life Release 7.1.8.9103842320 viewer (https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2365c9386-pmfp).
2. Log in to Agni as an estate manager in your region.
3. Open the Region/Estate floater (World - Region/Estate).
4. Select the Terrain tab.
5. Click on any terrain texture and select ‘Bake’.
6. Select any bake texture and click on the ‘Ok’ button.
7. Click on the ‘Apply’ button in the Terrain tab and observe terrain textures in the World.
 
**Actual result:**
Standard bake textures can be applied to terrain textures.

**Expected result:** 
Standard bake textures should not be applied to terrain textures.

**Comment by vladyslavasproductengine** [comment]
Pass QA.
Verified on the Second Life Release 7.1.9.9620320242 (64bit) on Win10/OSX in scope https://github.com/secondlife/iqa/issues/266.
