### ISSUE TITLE
Local PBR materials are not applied to the terrain

### ISSUE THREAD

**Issue by DmitrySProductengine** [secondlife/viewer#1553]
### Environment

<details><summary>Environment</summary>
<p>

Second Life Release 7.1.8.9103842320 (64bit)
Release Notes

You are at 114.3, 115.7, 22.8 in Product Engine 3 located at simhost-0d21bec691a88cebe.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%203/114/116/23
(global coordinates 336754.0, 307060.0, 22.8)
Second Life Server 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2600 MHz)
Memory: 16384 MB
OS Version: Mac OS X 13.6.7 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Mon Apr 22 20:54:28 PDT 2024; root:xnu-8796.141.3.705.2~1/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-4.14.1

Window size: 1680x1050
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (1.3% used)
HiDPI display mode: 0

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/586 (0.0%)
May 23 2024 05:06:38

</p>
</details> 

### Description

According to the ‘Featurettes Test Plan’ - 1. 2K textures - 1.5 Verify 2k textures work for Local textures - 5. Region / Estate > Terrain > Terrain Materials (when region uses materials). (https://lindenlab.atlassian.net/wiki/spaces/QA/pages/3054436428/Featurettes+Test+Plan#1.5-Verify-2k-textures-work-for-Local-textures)
This issue was found in the scope of [IQA #239](https://github.com/secondlife/iqa/issues/239).
This issue is reproduced on Win10 and OSX.

See the attached ‘Actual - 7.1.8.9103842320.png’ screenshot:
<img width="1680" alt="Actual - 7 1 8 9103842320" src="https://github.com/secondlife/viewer/assets/136308794/813d3ab5-0b10-4880-b95e-6651b054e06a">

This issue is not reproduced on the current release 7.1.7.8974243247 build - this feature has not been implemented yet.

This behavior may be related to the ticket (https://github.com/secondlife/viewer/issues/1006).
But by analogy with the ability to apply local textures to the terrain, it would be logical to allow the user to apply local PBR materials.
If you upload a PBR material example separately, it will be applied to the terrain.
See the attached ‘Expected - PBR material from inventory - 7.1.8.9103842320.png’ screenshot:
<img width="1680" alt="Expected - PBR material from inventory - 7 1 8 9103842320" src="https://github.com/secondlife/viewer/assets/136308794/64a5906a-0a1f-4cee-86f6-69b6067d65db">

Example of PBR material with 2k texture:
[33-gltf-wolf.zip](https://github.com/secondlife/viewer/files/15417090/33-gltf-wolf.zip)

### Reproduction steps

1. Download and install the Second Life Release 7.1.8.9103842320 viewer (https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2365c9386-pmfp).
2. Log in to Agni as an estate manager in your region.
3. Open the Region/Estate floater (World - Region/Estate).
4. Select the Terrain tab.
5. Enable the ‘PBR Metallic Roughness’ checkbox.
6. Click on any terrain material (for example 4) and select ‘Local’.
7. Add any PBR material with 2k texture (example added below)ю
8. Select the added PBR material and click on the ‘Ok’ button.
9. Click on the ‘Apply’ button in the Terrain tab.
 
**Actual result:**
Local PBR materials are not applied to the terrain.

**Expected result:**
Local PBR materials should be applied to the terrain.

**Comment by valeriiaaproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.9.9620320242 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/266.
