### ISSUE TITLE
All avatars using base are sunken in floor

### ISSUE THREAD

**Issue by makidoll** [secondlife/viewer#1568]
### Test plan
1. Buy https://marketplace.secondlife.com/p/OP-OPEN-PONY-Basic-Pony-Avatar/22771877
2. Rez the box, and click the BUY NOW button on the box.
3. Accept the "[OP] OpenPony Packaging (Rez)" it sends to you, and rez *that*.
4. Click the box and then "Only copy to inventory"
5. Open that folder in inventory and rez the "[OP] Stallion Box (Rez) v1.6.1" or "[OP] Mare Box (Rez) v1.6.1" box.
6. Click the box and then "Only copy to inventory"
7. Find that folder, right click it and Replace current outfit.
8. Install and run the Maint-YZ viewer; https://releasenotes.secondlife.com/viewer/7.1.6.8745209917.html
9. Adjust Avatar menu > Hover Height so the feet are correctly on the ground.
10. Run the viewer in test and **verify** the feet are still correctly on the ground.

### Environment

Latest main branch on Linux (through Firestorm)

### Description

This PR https://github.com/secondlife/viewer/pull/579 causes all avatars using the [OpenPony base](https://marketplace.secondlife.com/p/OP-OPEN-PONY-Basic-Pony-Avatar/22771877) to be sunken into the floor. I'm not sure how many other avatar bases are going to break. The sim I hang out in often gets close to 100 avatar limit and there are many others who use this base with the default included shape. It's fixable by updating the avatar shape's hover height. Will it be up to creators to push out updates for their avatar bases? I don't know how receptive others will be, e.g. "your pony still has the old shape where you're sunken", "oh i still haven't updated my viewer, what do you mean" kind of thing.

![broken](https://github.com/secondlife/viewer/assets/8362329/33caf384-780d-4dc8-8a4d-21efd1286953)

![fixed](https://github.com/secondlife/viewer/assets/8362329/6e38e4b1-5fdd-40c1-8d72-acfbfb13fd34)

### Reproduction steps

1. Use OpenPony avatar: https://marketplace.secondlife.com/p/OP-OPEN-PONY-Basic-Pony-Avatar/22771877
2. Sunken in floor unless you increase avatar shape's hover height

**Comment by akleshchev** [comment]
I checked new logic and some other avatars and it seems like new logic is faulty. Ex: calculated height is significantly below what real height is, some avatars are crouching slightly, some are tiptoeing. For now I'm going to revert https://github.com/secondlife/viewer/pull/579

Note for QA: this reverts https://github.com/secondlife/jira-archive-internal/issues/67771, so it will need to be tested and reopened, or a new issue created (since old one is in a non-public archive).

**Comment by georgebproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.8.9357006492 (64bit) on OSX/Win10 in the scope of https://github.com/secondlife/iqa/issues/249.
