### ISSUE TITLE
[Win] Viewer fails to detect more than 4Gb of video memory

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#1583]
### Description

VMI detects only up to 4095Mb

> LLGLManager::initGL : VRAM Detected (WMI):4095

DX9 detects more, but fails to apply it.

Task:
At minimum fix DX9 code to properly apply (and report) value, consider updating to DX11 or using GL_NVX_gpu_memory_info

**Comment by georgebproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.9.9473057952 (64bit) on Win10 in the scope of https://github.com/secondlife/iqa/issues/260.
