### ISSUE TITLE
Fix GLTF Orientation Test

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1597]
Test model: https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/OrientationTest

Test plan
1. Download each of the assets from the glTF folder of the Test model. 
2. Create a box in Second Life.
3. While the box is selected in edit mode, click Develop menu > GLTF > Open....
4. Choose the .gltf file of the Test model.
5. Verify the model appears in-world and matches the Screenshot on Test model page.

----
Orientation test is failing, fix it:

https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/OrientationTest/README.md

**Comment by vladyslavasproductengine** [comment]
Pass QA.
Verified on the Second Life Release 7.1.9.9620320242 (64bit) on Win10/OSX in scope https://github.com/secondlife/iqa/issues/266.
