### ISSUE TITLE
New variation of the LLRender::flush on GLTF dev branch

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1601]
### Environment

Second Life Release 7.1.8.9293650293 (64bit)
Release Notes

CPU: AMD Ryzen 9 5980HX with Radeon Graphics         (3293.81 MHz)
Memory: 15775 MB
OS Version: Microsoft Windows 10/11 64-bit (Build 22000.2538)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon RX 6800M

Windows Graphics Driver Version: 30.0.15020.1001
OpenGL Version: 4.6.14800 Core Profile Context 21.50.20.01 30.0.15020.1001

Window size: 1680x979
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 11474MB
Disk cache: Max size 1638.4 MB (12.1% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Not Connected
May 30 2024 11:24:19

### Description

Crash to desktop with the latest GLTF Dev viewer.

### Reproduction steps

1. Start the viewer from https://github.com/secondlife/viewer/releases/tag/Second_Life_Test%2324.05.29-gltf on my AMD machine.

Observed: Crash to desktop. https://app.bugsplat.com/v2/crash?database=SecondLife_Viewer_2018&id=1479008

Note 1: This seems to be a variation of https://github.com/secondlife/viewer/issues/1531

Note 2: The 7.1.8.9103842320 Featurettes viewer (which does not have the fix for 1531) runs fine on this machine - https://releasenotes.secondlife.com/viewer/7.1.8.9103842320.html

**Comment by Geenz** [comment]
Potentially integrated with https://github.com/secondlife/viewer/pull/1620

**Comment by Dan-Linden** [comment]
This works now and can be closed.

Second Life Project Gltf Development 7.1.8.9374099973 (64bit)
Release Notes

You are at 64.8, 39.3, 38.8 in Danger! Danger! located at simhost-09bc298009ab77a02.agni
SLURL: http://maps.secondlife.com/secondlife/Danger%21%20Danger%21/65/39/39
(global coordinates 261,185.0, 249,639.0, 38.8)
Second Life Server 2024-04-13.8669470296
Release Notes

CPU: AMD Ryzen 9 5980HX with Radeon Graphics         (3293.81 MHz)
Memory: 15775 MB
OS Version: Microsoft Windows 10/11 64-bit (Build 22000.2538)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon RX 6800M

Windows Graphics Driver Version: 30.0.15020.1001
OpenGL Version: 4.6.14800 Core Profile Context 21.50.20.01 30.0.15020.1001
