### ISSUE TITLE
PBR materials exhibit striation/moiré-patterns in specular highlights

### ISSUE THREAD

**Issue by Viscerous** [secondlife/viewer#1614]
### Environment

Second Life Project Gltf Development 7.1.8.9309468311 (64bit)
Release Notes

You are at 85.9, 168.0, 23.0 in Rumpus Room 4 located at simhost-040b83eb1ef209ed9.aditi
SLURL: secondlife://Aditi/secondlife/Rumpus%20Room%204/86/168/23
(global coordinates 35,925.9, 12,712.0, 23.0)
PMFP 2024-05-31.9321100266
Release Notes

CPU: 12th Gen Intel(R) Core(TM) i7-12700K (3609.6 MHz)
Memory: 32510 MB
OS Version: Microsoft Windows 10/11 64-bit (Build 26100.712)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 4090/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5585
OpenGL Version: 4.6.0 NVIDIA 555.85

Window size: 2560x1417
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 4095MB
Disk cache: Max size 1638.4 MB (48.8% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/20,537 (0.0%)
June 01 2024 06:35:06

### Description

In the latest Gltf/materials builds, specular highlights appear to exhibit striation/moiré-patterns, especially on lower roughness materials, this can significantly darken lower roughness materials. Sometimes this can be manifested as flickering. The issue does not occur on the latest release viewer (7.1.7.8974243247)

A set of prims with materials exhibiting issues can be found here:
secondlife://Aditi/secondlife/Rumpus%20Room%204/83/171/23

https://github.com/secondlife/viewer/assets/7198087/cb2ad7a0-7d9c-4493-8bf6-0539707d4586

https://github.com/secondlife/viewer/assets/7198087/f0e33054-9c00-4274-9d5d-e2bf5501a6b7

### Reproduction steps

1. Rez a sphere
2. Apply a PBR material of low roughness (something like 0.1), optionally with black base colour for visibility
3. Provide a light source and observe specular highlights

**Comment by Viscerous** [comment]
[secondlife://Aditi/secondlife/Rumpus%20Room%204/83/171/23](url)

**Comment by Dan-Linden** [comment]
The striation/moiré-patterns in specular highlights passes QA on Featurettes build 7.1.8.9375512768.

The dark left sphere that is seen at 4 seconds of 7.1.8.9309468311.mp4 is still visible on Mac. I'll file a separate bug for that.
