### ISSUE TITLE
Sphere mirror reflections should not flicker

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1628]
### Test plan to Ensure that spherical mirrors will be disabled.
- Sphere mirror probes should no longer function
- Setting up a mirror in the build floater should force it to a box probe
- Changing the shape should not be available if it's a mirror

----
### Environment
Also reproduces in build 7.1.8.9276569711

Second Life Release 7.1.8.9357006492 (64bit)
Release Notes

You are at 31.2, 224.2, 22.9 in Rumpus Room 2050 located at simhost-01129fe6e38889eb3.aditi
SLURL: secondlife://Aditi/secondlife/Rumpus%20Room%202050/31/224/23
(global coordinates 36,383.2, 14,560.2, 22.9)
PMFP 2024-05-31.9321100266
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4412)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1506x1184
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (36.2% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/5,206 (0.0%)
June 04 2024 11:38:34

### Description

Sphere mirrors flicker while box mirrors do not.

### Reproduction steps

1. Create a box mirror and observe that it looks correct.
2. Change the mirror's reflection probe shape to sphere

Observe: The reflection flickers rapidly.

https://github.com/secondlife/viewer/assets/119471733/631db52b-e50b-4148-aa7b-3f0db73767f7

Expected: No flickering

**Comment by Geenz** [comment]
To test:
- Sphere probes should no longer function
- Setting up a mirror in the build floater should force it to a box probe
- Changing the shape should not be available if it's a mirror

**Comment by Dan-Linden** [comment]
Verified on Featurettes build 7.1.8.9375512768 for Windows/Mac.
