### ISSUE TITLE
PBR material "2k-test1" prim is not visible on HUD

### ISSUE THREAD

**Issue by katerynamproductengine** [secondlife/viewer#1637]
### Environment

Second Life Release 7.1.8.9375512768 (64bit)
Release Notes

You are at 196.0, 70.6, 21.5 in Product Engine located at simhost-00983d904a8f2c6f5.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/196/71/21
(global coordinates 336836.0, 307271.0, 21.5)
Second Life Server 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (1600 MHz)
Memory: 16384 MB
OS Version: Mac OS X 13.5.1 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64
Graphics Card Vendor: Intel Inc.
Graphics Card: Intel(R) UHD Graphics 617

OpenGL Version: 4.1 INTEL-20.6.4

Window size: 794x779
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 96m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 1536MB
Disk cache: Max size 1638.4 MB (0.6% used)
HiDPI display mode: 0

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/7612 (0.0%)
June 05 2024 07:10:15

### Description

See reproduction steps

### Reproduction steps

Steps to reproduce:

1. Download and unzip the 2k.upload.test.zip material from [Featurettes Sample Files](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/3080814598).
2. Login to the viewer.
3. Upload the material and create a prim with it.
4. Attach the prim to your HUD.

Actual result :
Prim is white on HUD.
Expected result: 
PBR material "2k-test1" prim is visible on HUD.

Actual screenshot:
<img width="1439" alt="Screenshot 2024-06-05 at 2 11 00 PM" src="https://github.com/secondlife/viewer/assets/150451913/2e17bd92-f6ca-417e-b5e2-203a43aae1c6">

Additional info:
The issue is reproduced on the Win10/OSX.
The issue is reproduced on Production Second Life Release 7.1.7.8974243247.
This issue was found during [IQA#252](https://github.com/secondlife/iqa/issues/252) .
According to the test plan "Featurettes Test Plan" -> 1. 2K textures -> 1.3 Verify 2k textures work in all places.(https://lindenlab.atlassian.net/wiki/spaces/QA/pages/3054436428/Featurettes+Test+Plan#1.3-Verify-2k-textures-work-in-all-places.)

**Comment by Dan-Linden** [comment]
The Emissive tint of that Material is white. If the Emissive tint is changed to black then other textures are visible.
What is the expected behavior for a HUD object with a white Emissive tint?

**Comment by RunitaiLinden** [comment]
Expected behavior.  HUDs are unlit, so their final color is the sum of the basecolor and emissive color, and for that UV layout, the result is white.  HUDs also don't receive auto-exposure.  Here's a fun video showing the text disappearing in direct sunlight with a metallic factor of zero:

https://github.com/secondlife/viewer/assets/23218274/6ad9afdb-156a-434e-b150-c0740f0309fa

**Comment by Dan-Linden** [comment]
Closed as expected.
