### ISSUE TITLE
Add permissions check for Develop->GLTF->Save As/Upload...

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1638]
You should only be able to Upload or Save an object as GLTF if you are the owner and creator of the object according to SL permissions.

When Upload/Save is disabled, the corresponding buttons in Develop->GLTF menu should be disabled.

**Comment by brad-linden** [comment]
looks like this should be in state integrated, is that right?

**Comment by RunitaiLinden** [comment]
No QA needed.

**Comment by Dan-Linden** [comment]
Fractal on Aditi has GLTF content to test with. Develop->render metadata->GLTF Nodes will highlight the GLTF content.

**Comment by Dan-Linden** [comment]
This should get some QA attention anyway.

**Comment by AtlasLinden** [comment]
Setting status to Pending Release.
Negative test cases performed. That is, no visible changes spotted outside of what can be accessed via the Develop menu. GLTF->Save As/Upload menu items are only enabled on the PMFP channel on aditi and using the 2024.06 Atlasaurus builds. Tested on 7.1.9.9865199239 Win10/MacOS
