### ISSUE TITLE
Alpha mode on blinn-phong materials getting permanently corrupted on occasion

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1641]
### Description

A book has been written about this issue: https://github.com/secondlife/jira-archive-internal/issues/156809

TL;DR -- if the Blinn-Phong diffuse map reports isMissingAsset(), the viewer will set alpha mode to none, and if current viewer has mod permissions on the item in question, it will _actually modify the object so alpha mode will always be none_.

**Comment by akleshchev** [comment]
A simple way of causing a missing asset: assign a local texture and an alpha mode then relog. After relog that texture will be missing.

**Comment by akleshchev** [comment]
For now marking as Needs more info since I can't repro and davep asked whirly for more info, but added a commit that shows more accurate value in case of a missing asset (keeps the field disabled)

**Comment by Dan-Linden** [comment]
What info do we need from Whirly? A recipe to reproduce this bug?

**Comment by akleshchev** [comment]
Idealy a scenario, otherwise circumstances and any other data whirly is willing to provide.

**Comment by akleshchev** [comment]
Moved linked commit into its own issue as https://github.com/secondlife/viewer/issues/1962, hopefully it will help.

**Comment by Dan-Linden** [comment]
Whirly says she does not have a repro for this issue. It's just random.

**Comment by Dan-Linden** [comment]
Temporarily opened this so I could link a canny issue, and closed again.
