### ISSUE TITLE
Add support for GLTF KHR_texture_transform

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1687]
### Test plan:
1. Download each of the assets from the Test model: https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/TextureTransformTest/glTF
2. Create a box in Second Life.
3. While the box is selected in edit mode, click Develop menu > GLTF > Open....
4. Choose the "TextureTransformTest.gltf" file
5. **Verify** the model appears in-world and the arrows and green boxes match the Screenshot on https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/TextureTransformTest

### Description

See [KHR_texture_transform](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_texture_transform/README.md)

Test model:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/TextureTransformTest

**Comment by brad-linden** [comment]
is this complete?  should it me marked integrated?

**Comment by katerynamproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.9.9620320242 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/266.
