### ISSUE TITLE
UI overlap in Advanced graphics preferences

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#1733]
### Environment

Maint-A (but should partially be in release build 7.1.8.9375512768)

### Description

Both buttons and 'border' overlap other UI elements

![image](https://github.com/secondlife/viewer/assets/117672381/a1318208-f3a2-4ea0-b96c-5f6157d03a6c)

### Reproduction steps

Go to graphical settings->advanced

**Comment by katerynamproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.9.9620320242 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/266.
