### ISSUE TITLE
Audit texture image unit usage on OS X

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1736]
Various crashes and bugs can be attributed to running out of texture image units.  OpenGL guarantees we get at least 16, and OS X provides exactly that many _and_ doesn't optimize out unused samplers (GLSL representation of texture image units).  

Audit texture image unit usage on OS X and refactor shaders so that we don't rely on the shader compiler to optimize out unused samplers.

Test:
1. Run viewer against old intel GPUs and intel macbooks.
2. Enable shadows
3. Verify transparent objects don't disappear

**Comment by brad-linden** [comment]
is this done?  do we need a test plan?

**Comment by igorlproductengine** [comment]
Needs more info. 
Verified on the 7.1.9.9865199239 build in the scope of IQA282 in the OSX systems.

Could you please clarify:
 What specific old Intel GPUs should be targeted for testing?
 Are the transparent objects in question using transparent textures or transparency settings within the objects?

**Comment by AtlasLinden** [comment]
@igorlproductengine please test with any Intel GPUs on mac that you have available. Or update the status of this issue if it has already been covered via the OSX systems you mentioned.

**Comment by dmytrohproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.9.9981869229 (64bit) on OSX in the scope of [secondlife/iqa#286](https://github.com/secondlife/iqa/issues/286).

<details><summary>Environment</summary>
<p>
Second Life Release 7.1.9.9981869229 (64bit)
Release Notes

You are at 213.5, 108.2, 21.5 in Product Engine located at simhost-0c3dd673f1c1c8987.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/214/108/22
(global coordinates 336854.0, 307308.0, 21.5)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (2300 MHz)
Memory: 8192 MB
OS Version: macOS 13.6.4 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Sun Dec 17 22:18:09 PST 2023; root:xnu-8796.141.3.703.2~2/RELEASE_X86_64 x86_64
Graphics Card Vendor: Intel Inc.
Graphics Card: Intel(R) Iris(TM) Plus Graphics 640

OpenGL Version: 4.1 INTEL-20.6.4

Window size: 1440x785
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 1536MB
Disk cache: Max size 1638.4 MB (0.1% used)
HiDPI display mode:

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 61/822 (7.4%)
July 19 2024 00:44:50
</p>
</details> 

For checking this behavior were used:

Object#1: Non-transparent object, transparent texture;
Object#2: 100% transparent object, non texture;
Object#3: 50% transparent object, transparent texture.

Please, see the results in "iqa#286_OSX.png":
**iqa#286_OSX.png**
![iqa#286_OSX](https://github.com/user-attachments/assets/d31bebfc-496e-4d90-b154-fac7c765fd8d)
