### ISSUE TITLE
Fix missing LSL constant INVENTORY_SETTING in keywords_lsl_default.xml

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#1744]
## Test plan

The LSL constant `INVENTORY_SETTING` may or may not already be highlighted in the script editor before this change, but it definitely is now.

**Comment by vladyslavasproductengine** [comment]
Pass QA.
Verified on the Second Life Release 7.1.9.9620320242 (64bit) on Win10/OSX in scope https://github.com/secondlife/iqa/issues/266.
