### ISSUE TITLE
Mirrors not displaying correctly

### ISSUE THREAD

**Issue by beckhanra** [secondlife/viewer#1748]
### Environment

Second Life Release 7.1.8.9375512768 (64bit)
Release Notes

You are at 135.3, 25.9, 3,700.5 in Highview located at simhost-03ce186632c26acf6.agni
SLURL: http://maps.secondlife.com/secondlife/Highview/135/26/3701
(global coordinates 119,687.0, 314,906.0, 3,700.5)
Second Life Server 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz (3700.06 MHz)
Memory: 16303 MB
OS Version: Microsoft Windows 10 64-bit (Build 19044.4412)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5599
OpenGL Version: 4.6.0 NVIDIA 555.99

Window size: 1917x1006
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 512m
Bandwidth: 10000kbit/s
LOD factor: 4
Render quality: 6
Texture memory: 10338MB
Disk cache: Max size 819.2 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Not Connected
Packets Lost: 0/17,357 (0.0%)
June 13 2024 00:54:24

### Description

The surface with reflective material seem to be broken into 2 parts - the bottom is a regular "env mirror", and the top is "the mirror" from recent update. When you move the probe up and down, the border between two versions moves as well.

https://gyazo.com/d622095e4355e801163228144a6b1661

### Reproduction steps

1 make a prim/rez a mesh surface
2 make its face(s) reflective(env 255 or material of your choice)
3 add a probe
3.1 try different update modes
4 observe the results

**Comment by KrsityKu** [comment]
You didn't rotate the mirror properly, the top of the mirror probe needs to be facing away from the mirror, while in the clip it points up.
