### ISSUE TITLE
Viewer crash when connecting to webRTC voice with certain settings.xml

### ISSUE THREAD

**Issue by maestrolinden** [secondlife/viewer#1776]
### Environment

Second Life Release 7.1.9.9477703110 (64bit)
Release Notes

You are at 147.1, 98.4, 43.6 in WebRTC Voice 1 located at simhost-0907b59fedca3f5c1.agni
SLURL: http://maps.secondlife.com/secondlife/WebRTC%20Voice%201/147/98/44
(global coordinates 330387.0, 305762.0, 43.6)
Pop Rocks 2024-05-08.9009748043
Release Notes

CPU: Apple M1 Pro (2400 MHz)
Memory: 16384 MB
OS Version: Mac OS X 14.5.0 Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 x86_64
Graphics Card Vendor: Apple
Graphics Card: Apple M1 Pro

OpenGL Version: 4.1 Metal - 88.1

Window size: 1201x790
Font Size Adjustment: 96pt
UI Scaling: 0.75
Draw distance: 96m
Bandwidth: 10000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 10922MB
Disk cache: Max size 1638.4 MB (0.2% used)
HiDPI display mode: 0

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/383 (0.0%)
June 14 2024 14:33:52

### Description

Using the 7.1.9.9477703110 webRTC viewer, I found that my viewer would consistently crash when connecting to a webRTC region with voice enabled.   The viewer would crash when either first connecting to a webRTC region (if "Voice Chat" enabled in prefs) or when enabling "Voice Chat" while connected to a webRTC region.

I was able to reproduce this consistently many times with the attached settings.xml (which has "Voice Chat" enabled), though the crash goes away when I deleted settings.xml and reconnected (this file also attached).  It would appear that something in the settings.xml broke webRTC.  

I suspect this is the same issue as #1732 but think it's better to report it separately, as it occurs when no preferences have been touched in the crashing viewer session.

### Reproduction steps

1. Create a backup copy of the viewer's `user_settings/settings.xml`
2. Download [settings_crashes_maestros_7.1.9.9477703110_on_webrtc_connect.xml.txt](https://github.com/user-attachments/files/15844103/settings_crashes_maestros_7.1.9.9477703110_on_webrtc_connect.xml.txt) and overwrite settings.xml with it
3. Launch the viewer
4. Visit a webRTC region such as "webrtc voice 1" on Agni

Expected results:
The viewer should visit the region without issue and connect to voice chat in webRTC mode.

Actual results:
The viewer crashes as soon as it connects to the region.  

Other notes:
- If the start location is an SLS region in Vivox mode, the viewer connects to the region and joins voice chat without issue.  However, if the user teleports to a webRTC region in this case, the viewer immediately crashes.
- If the viewer connects to a webRTC region with voice disabled, then enables "Voice Chat" while in the region, the crash occurs immediately when enabling the preference
- There are no crash reports for any of the crashes
- The crash also reproduces when connecting to the new WebRTC-Voice 2024-06-12.9490472357 simulator
- When I delete the bad settings.xml and connect again, the viewer generated [settings_nocrash_7.1.9.9477703110.xml.txt](https://github.com/user-attachments/files/15844137/settings_nocrash_7.1.9.9477703110.xml.txt) as its replacement, which does not reproduce the bug for me.

**Comment by maestrolinden** [comment]
I can no longer reproduce this crash when using viewer build 7.1.9.9573202536 roxie/webrtc-voice branch, using the settings.xml attached to the repro test:

## Mac env

```
Second Life Test 7.1.9.9573202536 (64bit)
Release Notes

You are at 148.7, 150.5, 23.0 in webRTC1 located at simhost-07c23d76c83837d55.aditi
SLURL: secondlife://Aditi/secondlife/webRTC1/149/150/23
(global coordinates 259989.0, 245398.0, 23.0)
WebRTC-Voice 2024-06-12.9490472357
Release Notes

CPU: Apple M1 Pro (2400 MHz)
Memory: 16384 MB
OS Version: Mac OS X 14.5.0 Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 x86_64
Graphics Card Vendor: Apple
Graphics Card: Apple M1 Pro

OpenGL Version: 4.1 Metal - 88.1

Window size: 2522x1640
Font Size Adjustment: 96pt
UI Scaling: 0.75
Draw distance: 96m
Bandwidth: 10000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 10922MB
Disk cache: Max size 3993.6 MB (3.0% used)
HiDPI display mode: 1

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/3466 (0.0%)
June 18 2024 16:59:40
```

## Windows env

```
```

**Comment by maestrolinden** [comment]
I retested this in release/webrtc-voice build 7.1.9.9574256458, which includes the merge with the fix.  The crash is also fixed with this build.  Passes QA.

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.9.9604591078 (64bit) on Win10/Win11/OSX in the scope of [IQA #264](https://github.com/secondlife/iqa/issues/264).
Tested on Agni: 
Region: WebRTC Voice 1
Sim: Pop Rocks 2024-05-08.9009748043
Voice: Secondlife WebRTC Gateway
