### ISSUE TITLE
Disabling the Media preference should not disable the Noise Suppression preference

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1788]
### Environment

Second Life Release 7.1.9.9477703110 (64bit)
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4412)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1729x1344
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (4.6% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version:  

June 17 2024 10:48:09

### Description

Disabling the Media preference should not disable the Noise Suppression preference.

### Reproduction steps

1. Open Preferences > Sound & Media in a WebRTC viewer.
2. Uncheck the checkbox next to the Media volume slider.

Observed: The Noise Suppression drop-down menu becomes gray/unavailable. https://gyazo.com/5b1e24866c82bd23137b71855ed0e365

Expected: The Noise Suppression drop-down menu is related to voice and should not be affected by the Media setting.

**Comment by maestrolinden** [comment]
This might be related to #1732 - if there's a collision in some the preferences keys, I could see both the viewer crash (which is associated with certain settings.xml files) and this unexpected disable change occurring.

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.9.9604591078 (64bit) on Win10/Win11/OSX in the scope of [IQA #264](https://github.com/secondlife/iqa/issues/264).
Tested on Agni, Product Engine 3
Second Life Server 2024-06-11.9458617693
Vivox 4.10.0000.32327.5fc3fe7c.5942f08
