### ISSUE TITLE
Apple error appeared after quitting the WebRTC viewer

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1790]
### Environment

<details>
<summary>Environment</summary>
Second Life Release 7.1.9.9552740516 (64bit)

Release Notes

You are at 156.7, 173.4, 23.1 in webRTC1 located at simhost-07c23d76c83837d55.aditi

SLURL: secondlife://Aditi/secondlife/webRTC1/157/173/23

(global coordinates 259997.0, 245421.0, 23.1)

WebRTC-Voice 2024-06-12.9490472357

Release Notes

CPU: Apple M1 (2400 MHz)

Memory: 8192 MB

OS Version: Mac OS X 14.5.0 Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 x86_64

Graphics Card Vendor: Apple

Graphics Card: Apple M1

OpenGL Version: 4.1 Metal - 88.1

Window size: 1440x774

Font Size Adjustment: 96pt

UI Scaling: 1

Draw distance: 96m

Bandwidth: 3000kbit/s

LOD factor: 1.125

Render quality: 1

Texture memory: 5461MB

Disk cache: Max size 1638.4 MB (24.4% used)

HiDPI display mode: 0

J2C Decoder Version: KDU v7.10.4

Audio Driver Version: FMOD Studio 2.02.13

Dullahan: 1.14.0.202310131309

  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54

  Chromium: 118.0.5993.54

LibVLC Version: 3.0.16

Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/663 (0.0%)

June 17 2024 15:05:54
</details>

### Description

An Apple error appeared after quitting the WebRTC viewer.

### Reproduction steps

1. Logged in the WebRTC 7.1.9.9552740516 viewer for the first time on Mac.
2. Nothing special?
3. Exited the viewer.

Observed: An Apple error window was open, containing the following text:
[apple error.txt](https://github.com/user-attachments/files/15877738/apple.error.txt)

Here is the SecondLife.log file for that session in case it contains a clue:
[apple error appeared after quittting SecondLife.log](https://github.com/user-attachments/files/15877744/apple.error.appeared.after.quittting.SecondLife.log)

Expected: No Apple error dialogs.

Note: I have not yet reproduced this error on subsequent runs.

**Comment by roxanneskelly** [comment]
@akleshchev might this be related to the shutdown code that you fixed?

**Comment by akleshchev** [comment]
> might this be related to the shutdown code that you fixed?

Yes, this should be already fixed.

voiceConnectionCoro was remade into an 'idle' instead of 'coro' in develop branch so coroutines outliving parent shouln't affect it even if it is still somehow an issue.

**Comment by Dan-Linden** [comment]
I haven't seen this repro again. Closing this.
