### ISSUE TITLE
Advanced Graphics Preferences looks corrupted

### ISSUE THREAD

**Issue by sergiiiproductengine** [secondlife/viewer#1793]
**Steps to reproduce:**
1. Login to the [viewer](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%230870539-a).
2. Go to the Me > Preferences > Graphics > Advanced Settings.

**Actual result:**
Advanced Graphics Preferences looks corrupted.

<details><summary>actual screenshot:</summary>
<p>

![corrupted](https://github.com/secondlife/viewer/assets/150452325/a91c577e-1e84-4e34-a41e-63d9dfdca392)

</p>
</details> 

**Expected result:**
Advanced Graphics Preferences should not be corrupted.

<details><summary>expectedAsOnProd screenshot:</summary>
<p>

![expectedProd](https://github.com/secondlife/viewer/assets/150452325/ae998377-1cb3-4364-9f35-5dec6f96fa11)

</p>
</details> 

**Additional info:**
The issue is reproduced on Win10/OSX.
The issue is not reproduced on current production Second Life Release 7.1.8.9375512768 (64bit)
 due to new slider for lights into advanced graphical settings feature has not been implemented yet.

<details><summary>Environment</summary>
<p>

Second Life Release 7.1.9.9473057952 (64bit)
Release Notes

You are at 211.9, 231.9, 23.7 in Product Engine 2 located at simhost-028aef69f591c75f4.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%202/212/232/24
(global coordinates 337,108.0, 307,432.0, 23.7)
Second Life Server 2024-04-13.8669470296
Release Notes

CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (3302.41 MHz)
Memory: 16076 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4529)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5599
OpenGL Version: 4.6.0 NVIDIA 555.99

Window size: 1920x1027
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 5228MB
Disk cache: Max size 1638.4 MB (0.6% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 

Packets Lost: 2/4,603 (0.0%)
June 18 2024 02:09:35

</p>
</details>

**Comment by akleshchev** [comment]
Dupplicate of https://github.com/secondlife/viewer/issues/1733
