### ISSUE TITLE
When other user disconnects from our p2p call, I cannot see their voice dot in spatial chat.

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1802]
### Environment

Second Life Release 7.1.9.9552740516 (64bit)
Release Notes

You are at 151.3, 149.0, 22.9 in webRTC1 located at simhost-07c23d76c83837d55.aditi
SLURL: secondlife://Aditi/secondlife/webRTC1/151/149/23
(global coordinates 259,991.0, 245,397.0, 22.9)
WebRTC-Voice 2024-06-12.9490472357
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4529)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1665x1316
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (12.6% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 15/20,034 (0.1%)
June 18 2024 16:47:52

### Description

When other user disconnects from our p2p call, I cannot see their voice dot in spatial chat.

### Reproduction steps

1. User A, B, and C are in local voice. User C will be an observer.
2. User A and B start a person to person call with each other. It doesn't matter who initiates the call.
3. User A, disconnect the person to person call.
4. Verify both users rejoin local voice and everyone can see everyone else's voice dot.

Observed: User B will not see User A's voice dot in spatial chat or over User A's head. User B _can_ hear User A in spatial chat.

Expected: All 3 users should be able to see the other's voice dots.

**Comment by Dan-Linden** [comment]
This issue does not repro on an Agni vivox region with the WebRTC 7.1.9.9552740516 viewer. Thus this is not a blocker for the first RC viewer.

**Comment by Dan-Linden** [comment]
This still reproduces on WebRTC viewer 7.1.9.9688089989.

Second Life Release 7.1.9.9688089989 (64bit)
You are at 126.2, 125.9, 22.7 in webRTC1 located at simhost-02bfc572742fa99b4.aditi
SLURL: secondlife://Aditi/secondlife/webRTC1/126/126/23
(global coordinates 259,966.0, 245,374.0, 22.7)
WebRTC-Voice 2024-06-24.9652733849
CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.91 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4529)

**Comment by Dan-Linden** [comment]
This is User B's view in the repro.
https://github.com/user-attachments/assets/b5d39ed5-f8a4-4d43-8236-57d75e623e53

**Comment by roxanneskelly** [comment]
This required a server fix as well, and the server is currently deployed to Aditi.

**Comment by dmytrohproductengine** [comment]
Deferred QA.
Verified on the Second Life Release 7.1.9.10479800881 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/311.

A new issue on WebRTC regions:
[secondlife/viewer/issues/2376](https://github.com/secondlife/viewer/issues/2376) - The viewer (Atlasaurus RC 7.1.9.10479800881) freezes on WebRTC regions if logged in with Voice Chat enabled.

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.9.10495892574 (64bit) on Win11/OSX in the scope of [IQA #312](https://github.com/secondlife/iqa/issues/312).
Tested on Aditi:
1. WebRTC:  
secondlife://Aditi/secondlife/webRTC2/83/247/23
Sim: WebRTC-Voice 2024-08-15.10397494850
Voice: Secondlife WebRTC Gateway 

2. Vivox:
secondlife://Aditi/secondlife/vivox2/85/18/23
Sim: Second Life Server 2024-07-22.10048683488
Voice: Vivox 4.10.0000.32327.5fc3fe7c.5942f08
