### ISSUE TITLE
[win] Support bugsplat's setAttribute

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#1808]
Update bugplat on windows and fill it with application state and any other crash relevant data.

Test plan: new fields should appear in bugplat.

**Comment by akleshchev** [comment]
![image](https://github.com/secondlife/viewer/assets/117672381/666df636-c57c-410d-b1b5-d48b5c181176)

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.9.9620320242 (64bit) on Win10 in the scope of https://github.com/secondlife/iqa/issues/266.
