### ISSUE TITLE
Person to person calls should not work if blocked in Windows Defender Firewall

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1845]
### Environment

Second Life Release 7.1.9.9604591078 (64bit)
Release Notes

You are at 151.3, 148.8, 22.9 in webRTC1 located at simhost-02bfc572742fa99b4.aditi
SLURL: secondlife://Aditi/secondlife/webRTC1/151/149/23
(global coordinates 259,991.0, 245,397.0, 22.9)
WebRTC-Voice 2024-06-24.9652733849
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4529)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1665x1316
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/2,696 (0.0%)
June 25 2024 16:02:11

### Description

For investigation. This may not be a bug.
Person to person calls work despite being blocked in Windows Defender Firewall.

### Reproduction steps

1. After installing WebRTC viewer and logging in the first time, I click Cancel on the UAC for Windows Defender Firewall.
2. Person to person calls that I initiate are never received by the other party. I believe this is expected behavior.
3. Person to person calls that the other person initiates are received by me can be accepted by me, and they work. Is this expected? I don't know.
4. After disconnecting, I initiate a Person to person call to the other person again.

Observed: Person to person calls that I initiate now work! I've checked the firewall rule and it still says blocked.

Expected: Person to person calls should continue to be blocked.

Note: This expected behavior is based on intuition, not any documentation or test plan, and may be incorrect.

**Comment by bridie-linden** [comment]
Closing, working as expected!
