### ISSUE TITLE
Negative UV scale causes wrong lighting on PBR materials

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#1847]
### Description

Applying a negative scale u or scale v to a prim with the PBR material causes the lighting to shine from the wrong direction.

These other tickets are related but not equivalent:

- https://github.com/secondlife/jira-archive/issues/10768
- https://feedback.secondlife.com/bug-reports/p/normal-map-tangents-are-wrong-if-normal-map-is-mirrored-with-the-edit-tool

**Comment by igorlproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10622905308 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
