### ISSUE TITLE
SLPlugin.exe

### ISSUE THREAD

**Issue by ghost** [secondlife/viewer#1854]
### Environment

Second Life Develop 7.1.9.9618671499 (64bit)

### Description

Faulting application name: SLPlugin.exe, version: 0.0.0.0, time stamp: 0x6675d543
Faulting module name: libcef.dll_unloaded, version: 118.4.1.0, time stamp: 0x651cb3d9
Exception code: 0xc0000005
Fault offset: 0x00000000046433f0
Faulting process id: 0x32ac
Faulting application start time: 0x01dac86eb8167060
Faulting application path: C:\Users\name\Downloads\Second_Life_Develop_7_1_9_9618671499_x86_64_Setup\SLPlugin.exe
Faulting module path: libcef.dll
Report Id: 592fdd1b-3c8c-4413-ba69-2ee1f7c76ff8
Faulting package full name: 
Faulting package-relative application ID: 

### Reproduction steps

n/a

**Comment by kylelinden** [comment]
Not enough information to action. Please file in https://feedback.secondlife.com
