### ISSUE TITLE
Lower-end optimization pass

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1870]
### Test plan:
- Test on an machine with an Intel HD 4000, 4400, or Iris Xe video card 
- Test on Nvidia GT 1030 if available
- Test on a laptop that has an AMD video card if available.
- Test on a Mac with a M1, M2, or M3 chip

1. Go to http://maps.secondlife.com/secondlife/Bug%20Island%202/107/14/23
2. Open the Texture Console. (Enable Preferences > Advanced > Show Develop Menu, then enable Develop > Consoles > Texture Console.)
3. To make the texture console easier to read, take a copy of the black object on the ground and attach it. It will attach to the HUD.
4. Look at the gray walls of textures to the South of you with the goal of loading as many as possible and causing the "Sys Free" number to fall below 512 in the texture console.
6. If "Sys Free" falls below 512, verify there is a log message in SecondLife.log, "Low system memory detected, emergency downrezzing off screen textures"
7. Verify Bias goes to 2.0 and Sys Free should immediately go up to around 500 MB.
8. Verify the framerate is smooth through all this without any noticable stalls or freezes.

### Description

Profile and optimize viewer on laptop with Intel Iris Xe and 8GB of ram.

**Comment by Dan-Linden** [comment]
Reopened to go through QA.
