### ISSUE TITLE
Lua table not printed in output

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#1876]
### Environment

Second Life Test 7.1.7.9018993715 (64bit)
Release Notes

You are at 121.0, 110.0, 22.6 in Pasta Cake located at simhost-04f8d08eec622ee3a.agni
SLURL: http://maps.secondlife.com/secondlife/Pasta%20Cake/121/110/23
(global coordinates 332,153.0, 305,518.0, 22.6)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: 12th Gen Intel(R) Core(TM) i9-12900HK (2918.4 MHz)
Memory: 32440 MB
OS Version: Microsoft Windows 10 64-bit (Build 19044.3086)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.4659
OpenGL Version: 4.6.0 NVIDIA 546.59

Window size: 2560x1377
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 10000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 4095MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 15/4,593 (0.3%)
June 28 2024 08:21:34

### Description

Found while comparing outputs between SL viewer and Roblox Studio.
Roblox Studio allows tables to be output over multiple lines after clicking to open them
https://gyazo.com/7fd2e6ff1744ce9089bb207e963c5889 

Whereas the SL viewer outputs the following:
![image](https://github.com/secondlife/viewer/assets/114031241/aeaf4676-a5ec-4d34-9670-63c664102928)

### Reproduction steps

Run the following lua script:
```
-- Tables!

-- creating and indexing table
local exampleTable = {10, 35, 2, -33} --array

print(exampleTable[1]) --first value
print(exampleTable[#exampleTable]) --last value

-- table library
local newNum = 20
table.insert(exampleTable, newNum)
print(exampleTable)
local index = table.find(exampleTable, 20)
table.remove(exampleTable, index)
print(exampleTable)

local clone = table.clone(exampleTable)
table.clear(clone)
print(clone)

-- dictionary vs array
local dictExample = {Key1 = "Hello", Key2 = "World"} --key value pair
print(dictExample["Key1"])
print(dictExample.Key2)
dictExample.Key1 = "G'day!"
print(dictExample.Key1)
dictExample.Key1 = nil
print(dictExample)

```

**Comment by nat-goodspeed** [comment]
We bundle the `inspect` module, so this is how you print a table:
```
inspect = require 'inspect'
-- construct table t ...
print(inspect(t))
```
Do we expect `print()` to be among the primary use cases for Lua in the viewer?

**Comment by AtlasLinden** [comment]
Closing as expected behaviour.
Printing a table will require use of the `inspect` module as given above
