### ISSUE TITLE
[Aditi]Users except creator are dropped from ad-hoc voice conversation on Vivox

### ISSUE THREAD

**Issue by georgebproductengine** [secondlife/viewer#1890]
### Environment

Second Life Release 7.1.9.9688089989 (64bit)
Release Notes

You are at 128.0, 129.8, 23.2 in Product Engine Hera1 located at simhost-06f1d9607bd9be574.aditi
SLURL: secondlife://Aditi/secondlife/Product%20Engine%20Hera1/128/130/23
(global coordinates 337,024.0, 307,586.0, 23.2)
Spring Break 2024-06-11.9458617693
Release Notes

CPU: AMD Ryzen 7 5700U with Radeon Graphics          (1796.63 MHz)
Memory: 14198 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4529)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon(TM) Graphics

Windows Graphics Driver Version: 27.20.15026.8004
OpenGL Version: 4.6.14822 Core Profile Context 20.50.26.08 27.20.15026.8004

Window size: 1200x991
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 8418MB
Disk cache: Max size 1638.4 MB (4.3% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/14,328 (0.0%)
July 01 2024 02:30:09

### Description

See Reproduction steps

**Reproduction steps:**

 1. User A ,User B and User C Login to the Viewer on   Vivox region(e.g. secondlife://Aditi/secondlife/Product%20Engine%20Hera1/128/130/23).
 2. User A start a voice conversation with User B and User C.
 3. User B and User C answer.

**Actual behavior:** User B and User C are dropped to the nearby voice chat
**Expected behavior:** User B and User C are connected to the Ad-hoc voice conversation

**Additional information:**
 This issue is reproduced on Win10 and OSX.
This issue also reproduces on 7.1.9.9604591078 (the current WebRTC RC viewer)
This issue does not reproduce on the current Release viewer - 7.1.8.9375512768 - Materials Featurettes.

**Comment by bridie-linden** [comment]
Vivox - closing/ 'won't fix'
