### ISSUE TITLE
Incorrect white display of the entire viewer menu

### ISSUE THREAD

**Issue by valeriiaaproductengine** [secondlife/viewer#1894]
### Environment

Second Life Release 7.1.9.9620320242 (64bit)
Release Notes

You are at 192.1, 70.5, 21.5 in Product Engine located at simhost-0afb4afe97480773f.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/192/71/21
(global coordinates 336,832.0, 307,271.0, 21.5)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz (2611.2 MHz)
Memory: 16111 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4529)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.2879
OpenGL Version: 4.6.0 NVIDIA 528.79

Window size: 1920x1001
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 4095MB
Disk cache: Max size 1638.4 MB (2.1% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 5/2,003 (0.2%)
July 01 2024 05:42:33

### Description

See Reproduction steps

### Reproduction steps

1. Login to the Second Life Release 7.1.9.9620320242 Viewer on Agni.
2. Download each of the assets from the glTF folder of the Test model: https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/TextureTransformTest/glTF.
3. Create a box in Second Life.
4. While the box is selected in edit mode, click Develop menu > GLTF > Open....
5. Choose the .gltf or .glb file of the Test model.
6. Observe the behavior of the viewer.

**Actual:** Incorrect white display of the entire viewer menu.
**Expected:** The viewer should work correctly after downloading the  Test model .gltf or .glb file.

**Additional:**
This issue is reproduced on Win10.
This issue appeared when checking the https://github.com/secondlife/viewer/issues/1677 ticket.
Also, this issue is reproduced when trying to open Test model .gltf or .glb file on  Agni grid. Sometimes just going to the secondlife://Aditi/secondlife/Fractal/128/136/2 location on Aditi grid can reproduce the issue.

See actual.mp4 video:

https://github.com/secondlife/viewer/assets/150451911/d68348e5-73c4-4804-bbbb-b9b2e5afe240

**Comment by AtlasLinden** [comment]
When this fix is integrated, please update status of https://github.com/secondlife/viewer/issues/1677 to In QA

**Comment by Crexon1** [comment]
Just as a note tested the latest Atlasaurus build 7.1.9.10220184061 and this issue still happens with some GlTF object at Fractal on the beta grid Aditi.
secondlife://Aditi/secondlife/Fractal/128/128/3

![image](https://github.com/user-attachments/assets/5a6ac1eb-bc19-4b5a-b368-56e44f90b198)

**Comment by RunitaiLinden** [comment]
I remember seeing this but cannot repro it now... likely fixed.

**Comment by georgebproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10516785745 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
