### ISSUE TITLE
The "Share" and "Pay" buttons are active when selecting multiple avatars in Nearby tab

### ISSUE THREAD

**Issue by valeriiaaproductengine** [secondlife/viewer#1905]
### Environment

Second Life Release 7.1.9.9620320242 (64bit)
Release Notes

You are at 186.6, 62.9, 21.5 in Product Engine located at simhost-0afb4afe97480773f.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/187/63/21
(global coordinates 336,827.0, 307,263.0, 21.5)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz (2611.2 MHz)
Memory: 16111 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4529)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.2879
OpenGL Version: 4.6.0 NVIDIA 528.79

Window size: 1888x907
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 4095MB
Disk cache: Max size 1638.4 MB (19.9% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/1,342 (0.0%)
July 02 2024 05:59:24

### Description

See Reproduction steps

### Reproduction steps

1. Login to the Second Life Release 7.1.9.9620320242 (64bit) Viewer.
2. Open People- > Nearby tab and select more than one avatar.
3. Select the "Gear" button.
4. Observe the "Share" and "Pay" buttons.

**Actual behavior:** The "Share" and "Pay" buttons are active when selecting multiple avatars in Nearby tab.

**Expected behavior:** Only the ‘IM’, ’Call’, ’Offer Teleport’ buttons should be active.

**Additional information:**

This issue was found according to test plan: https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2693562379/FUI+People+Nearby+Panel+Regression+Test+Plan#6.-Verb-buttons. -> 6. Verb buttons.
This issue is reproduced on Win10 and OSX.
This issue is not reproduced on the current production build Second Life Release 7.1.8.9375512768.
Also, this issue occurs when call the context menu with selected avatars.

See actual.png screenshot:
![actual](https://github.com/secondlife/viewer/assets/150451911/6fee9cbb-48e9-4e95-a02c-024f03e9040f)

**Comment by georgebproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10516785745 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
