### ISSUE TITLE
Mirrors hitting performance from the grave

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#1914]
### Environment

Second Life Release 7.1.9.9620320242 (64bit)
Release Notes

You are at 96.4, 149.1, 22.6 in Preflight8 located at simhost-06c9a56af17a2102e.agni
SLURL: http://maps.secondlife.com/secondlife/Preflight8/96/149/23
(global coordinates 332,640.0, 305,813.0, 22.6)
Second Life Preflight 2024-06-11.9458617693
Release Notes

CPU: 12th Gen Intel(R) Core(TM) i9-12900HK (2918.4 MHz)
Memory: 32440 MB
OS Version: Microsoft Windows 10 64-bit (Build 19044.3086)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.4659
OpenGL Version: 4.6.0 NVIDIA 546.59

Window size: 2560x1377
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 10000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 4095MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/9,686 (0.0%)
July 02 2024 12:26:18

### Description

Discovered while testing https://github.com/secondlife/viewer/issues/1814 and observing the FPS after hiding the mirror from the camera. 
FPS goes up when a mirror is hidden from view but this behaviour still persists after deleting the mirror **until a relog**.
i.e Mirrors are still hitting performance from the grave

https://gyazo.com/c24ff56de0b7938ee97dd4e7a18df448

### Reproduction steps

Observe performance after deleting a mirror in an empty region

**Comment by KrsityKu** [comment]
Same as https://github.com/secondlife/viewer/issues/1721 ?

**Comment by AtlasLinden** [comment]
So it is! Thanks @KrsityKu!
Closing this as a duplicate of https://github.com/secondlife/viewer/issues/1721
