### ISSUE TITLE
Default Chat Window Behavior on First Login

### ISSUE THREAD

**Issue by darcylinden** [secondlife/viewer#1916]
We recently ran an experiment which tested the hypothesis: "If we make it better known where the Chat button is, new Residents will send more messages, increase their connections, and retain longer."

Initial data shows that there was an impact with more Residents sending messages.

To further test this hypothesis:

1. Let's have the Conversations window open by default via the relevant user settings XML.
2. Update the location of the Chat window (currently lower right, see image below) to be on the lower left, which the Design team has cited as being the better location for left-to-right language speakers.

![image](https://github.com/secondlife/viewer/assets/42617016/32a5b344-5776-4b28-b937-debc96225623)

**Comment by akleshchev** [comment]
> Let's have the Conversations window open by default via the relevant user settings XML.

First login only or default in general?

**Comment by darcylinden** [comment]
On first login only, please!

**Comment by akleshchev** [comment]
Seems to be already there, llfloaterimcontainer.cpp:

```
    //We should expand nearby chat participants list for the new user
    if(gAgent.isFirstLogin() || !gSavedPerAccountSettings.getBOOL("ConversationsParticipantListCollapsed"))
    {
        expandConversation();
    }
```

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.10.10516785745 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
