### ISSUE TITLE
The  'No emoji selected' message appears and overlaps emoji name in the Choose Emoji floater

### ISSUE THREAD

**Issue by sergiiiproductengine** [secondlife/viewer#1917]
**Steps to reproduce:**
1. Login to the [viewer](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2308f2236-atlasaurus).
2. Type ":hand" in Nearby chat.
3. Observe the Choose Emoji floater.

**Actual result:** 
The  "No emoji selected" message appears and overlaps emoji name.

**Expected result:**
The message should not appear
(or should be appeared without overlapping).

<details><summary>actual screenshot</summary>
<p>

![actual](https://github.com/secondlife/viewer/assets/150452325/ad26cb1a-4fbf-434e-a58e-e9e68333a754)

</p>
</details> 
<details><summary>expected screenshot</summary>
<p>

![expectedRelease](https://github.com/secondlife/viewer/assets/150452325/2a933d20-4166-45af-9753-5c95e0ad3370)

</p>
</details> 

**Additional info:**
The issue is reproduced on Win10/OSX.
The issue was found during ad-hoc testing.
The issue is not reproduced on the current production build (7.1.8.9375512768).

<details><summary>Environment</summary>
<p>

Second Life Release 7.1.9.9620320242 (64bit)
Release Notes

CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (3302.4 MHz)
Memory: 16076 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4529)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5612
OpenGL Version: 4.6.0 NVIDIA 556.12

Window size: 1920x1027
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 5228MB
Disk cache: Max size 1638.4 MB (0.4% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version:  

July 02 2024 23:33:17

</p>
</details>

**Comment by LLGuru** [comment]
Fixed in https://github.com/secondlife/viewer/pull/1920

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.10.10516785745 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
