### ISSUE TITLE
Make PBR scale and offset crosshair work like Texture crosshair do

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#1922]
Note white crosshair on the image, it shows texture's center for textures yet face's center for PBR.

I think they should be identical, PBR should be showing 4 markers, not 1. Texture vs PBR:
<img width="322" alt="Screenshot 2024-07-03 at 17 49 14" src="https://github.com/secondlife/viewer/assets/117672381/b6303750-3bba-46f4-a174-c99d5b5b8abe">
<img width="269" alt="Screenshot 2024-07-03 at 17 50 54" src="https://github.com/secondlife/viewer/assets/117672381/d21f9691-13a9-4f32-9ab5-1ad88e81b0c7">

## Test Plan

- Set two cubes side by side
- Switch build tools to 'select face'
- Open texture tab and assign a pbr to one of the cubes (Material->'PBR Material roughtness' then click the image)
- Change scale U and V (or vertical and horizontal in texture tab) for both cubes to 2.

**Comment by KrsityKu** [comment]
There was Canny about this https://feedback.secondlife.com/scripting-features/p/make-texture-offsets-work-the-same-way-for-phong-and-pbr-textures 

And my thinking was:

> I believe the glTF standard specifies that the textures need to be mapped this way so they either have to make it not conform to the standard, making glTF compatible imports not compatible, or change legacy materials to match, breaking all existing content.

Thought it would be nice to hear from the dev team if that is actually the case, as that canny was closed without elaborating on it.

**Comment by akleshchev** [comment]
I'm not suggesting to make texture offset work similarly, I'm suggesting to fix markers. The white round with a cross in the middle should be in the middle of an offseted par, not in the middle of the object and should properly highlight where texture ends.

**Comment by akleshchev** [comment]
Here is a better example:
<img width="425" alt="Screenshot 2024-07-03 at 19 32 17" src="https://github.com/secondlife/viewer/assets/117672381/39a6c4ba-4a28-4e64-b447-43e8811d33c8">
<img width="377" alt="Screenshot 2024-07-03 at 19 32 33" src="https://github.com/secondlife/viewer/assets/117672381/8deefeb3-ade6-4976-8b64-a31cd2803333">

**Comment by KrsityKu** [comment]
> I'm not suggesting to make texture offset work similarly, I'm suggesting to fix markers and borders.

Oh, my bad.

**Comment by sergiiiproductengine** [comment]
Win10/Win11 Passed QA.

OSX - Deferred QA.
The issue cannot be verified on the OSX due to new https://github.com/secondlife/viewer/issues/2437 issue.

The ticket status has not been changed yet.

**Comment by igorlproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.10.10708851543 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/326.
