### ISSUE TITLE
Make "Sys Free" in texture console (LLMemory::sAvailPhysicalMemInKB) tell the truth

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1943]
### Description

Open texture console (Ctrl-Shift-3) and observe "Sys Free" value.  

On Windows, this value should agree with resource monitor -> performance -> memory -> available.
On OS X, this value should be activity monitor -> memory -> (physical memory - memory used)

**Comment by RunitaiLinden** [comment]
Fixed.

Made LLMemory defer to LLMemoryInfo for "getAvailableMemoryKB" and added OS X and Linux implementation for same.

NOTE:  The OS X implementation is not perfect, but should be good enough.  It will often report a different value than Activity Monitor would suggest, but the particulars of how much memory is "free" according to the OS are elusive.  I tried various encantations of vm_stat, sysctl, etc and the closes I could get was using the sum of "free_count" and "inactive_count" from host_statistics64.

**Comment by sergiiiproductengine** [comment]
Win10: Passed QA.

OSX: Failed QA.
<details><summary>OSX screenshot</summary>
<p>

<img width="1680" alt="Screenshot 2024-08-29 at 10 55 18 AM" src="https://github.com/user-attachments/assets/8b71b9ee-b753-4dde-a248-c4a03cfc2b67">

</p>
</details> 

Verified on the Second Life Release 7.1.10.10582490681 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
