### ISSUE TITLE
The different behavior of translators when translating text with SLURL

### ISSUE THREAD

**Issue by DmitrySProductengine** [secondlife/viewer#1956]
### Environment
<details><summary>Environment</summary>
<p>

Second Life Release 7.1.9.9620320242 (64bit)
Release Notes

You are at 130.5, 118.4, 22.8 in Product Engine 3 located at simhost-02329e0edf37d025f.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%203/131/118/23
(global coordinates 336770.0, 307062.0, 22.8)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2600 MHz)
Memory: 16384 MB
OS Version: macOS 14.5.0 Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-5.5.17

Window size: 1920x1200
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (0.5% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/668 (0.0%)
July 09 2024 06:36:03

</p>
</details> 

### Reproduction steps

1. Download and install the Second Life Release 7.1.9.9620320242 viewer (https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2308f2236-atlasaurus).
2. Launch the Viewer.
3. Enable chat translation and set it up to Azure Translator. The required credentials are indicated in the [FUI: Chat Translation Test Plan](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2693005397/FUI+Chat+Translation+Test+Plan#1.-Test-Setup)
4. Enter any text with SLURL in the Nearby chat and press the "enter" button.
For example: 
a) test secondlife:///app/agent/1b35fbc4-bc3f-4b8a-b49a-b2287506ca35/inspect test
b) link secondlife:///app/agent/1b35fbc4-bc3f-4b8a-b49a-b2287506ca35/inspect link and some text
5. Observe the translation in the Nearby chat.
6. Repeat steps 3-5 with Google and DeepL translators.

**Actual result:**
The different behavior of translators when translating text with SLURL.

**Expected result:**
All translators should translate the text and not change the SLURL during translation.

**Additional information:**
According to the ‘FUI: Chat Translation Test Plan’ - 2.2. Chat translation - 2.2.3. Text-specific cases
 - [Text with SLURLs](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2693005397/FUI+Chat+Translation+Test+Plan#2.2.3.-Text-specific-cases).
This issue was found in the scope of [IQA #245](https://github.com/secondlife/iqa/issues/245).
This issue is reproduced on Win10 and OSX.

This issue is reproduced on the current release 7.1.8.9375512768 build (taking into account the new bug https://github.com/secondlife/viewer-private/issues/250).

This behavior was described in a [comment](https://github.com/secondlife/jira-archive-internal/issues/70426#issuecomment-1911029649) in ticket https://github.com/secondlife/jira-archive-internal/issues/70426.
I decided to file a separate ticket for this behavior, but perhaps after investigating, it’s worth dividing it into each translator separately (but it can and will be fixed in the context of this general ticket).

**The behavior of different translators (translating to Russian):**
Sample 1:  test secondlife:///app/agent/1b35fbc4-bc3f-4b8a-b49a-b2287506ca35/inspect test
1. Azure:
test  djimmy2.com (djimmy.carami) test (test %3Cdiv translate%3D%22no%22%3Esecondlife%3A%2F%2F%2Fapp%2Fagent%2F1b35fbc4-bc3f-4b8a-b49a-b2287506ca35%2Finspect%3C%2Fdiv%3E test)

in this case, the behavior of a new bug https://github.com/secondlife/viewer-private/issues/250 may be manifested

2. Google: 
test  djimmy2.com (djimmy.carami) test (тест Secondlife:///app/agent/1b35fbc4-bc3f-4b8a-b49a-b2287506ca35/inspect test)

in this case, the first text is translated, then SLURL is not inserted in the correct format (it does not work like SLURL) and the text after SLURL is not translated

3. DeepL:
test  djimmy2.com (djimmy.carami) test

in this case, there is no translation at all

Sample 2:  link secondlife:///app/agent/1b35fbc4-bc3f-4b8a-b49a-b2287506ca35/inspect link and some text
1. Azure:
link  djimmy2.com (djimmy.carami) link and some text (link %3Cdiv translate%3D%22no%22%3Esecondlife%3A%2F%2F%2Fapp%2Fagent%2F1b35fbc4-bc3f-4b8a-b49a-b2287506ca35%2Finspect%3C%2Fdiv%3E ссылка и немного текста)

in this case, the text after SLURL is translated and the behavior of a new bug https://github.com/secondlife/viewer-private/issues/250 may be manifested

2. Google: 
link  djimmy2.com (djimmy.carami) link and some text (ссылка Secondlife:///app/agent/1b35fbc4-bc3f-4b8a-b49a-b2287506ca35/inspect ссылка и немного текста)

in this case, the text before and after the SLURL is translated, then SLURL is not inserted in the correct format (does not work like SLURL)

3. DeepL:
link  djimmy2.com (djimmy.carami) link and some text (ссылка secondlife:///app/agent/1b35fbc4-bc3f-4b8a-b49a-b2287506ca35/обнаружить ссылку и некоторый текст)

in this case, the text before and after the SLURL is translated, but also the SLURL itself is partially translated

See attached screenshots:
1. Actual - 7.1.9.9620320242
<img width="997" alt="Actual - 7 1 9 9620320242" src="https://github.com/secondlife/viewer/assets/136308794/b5aca414-023b-431c-a195-56cdf9158390">

2. Actual - current release 7.1.8.9375512768
<img width="992" alt="Actual - current release 7 1 8 9375512768" src="https://github.com/secondlife/viewer/assets/136308794/24d731aa-24f8-4ca3-b597-58a20fe38ca8">

**Comment by kylelinden** [comment]
Expected behavior. We cannot control what the translators do with the formatting of SLapps.

**Comment by akleshchev** [comment]
> Expected behavior. We cannot control what the translators do with the formatting of SLapps.

Some translators allow 'do not translate this' markers.
