### ISSUE TITLE
Show accurate Alpha mode if asset is missing

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#1962]
Block dropbox and show actual value of alpha mode if asset is missing. Prevent user from accidentally commiting changed alpha.

## Test Plan

1. Rez a cube
2. Assign a local texture
3. Change alpha mode
4. Relog
5. Check the object

Local textures become 'missing assets' after a relog and that should
1. Disable alpha related controls
2. Show values that were set at step 3

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.9.9865199239 (64bit) on Win10/OSX in the scope of [secondlife/iqa#282](https://github.com/secondlife/iqa/issues/282).
