### ISSUE TITLE
Debug setting VoiceMorphingEnabled should default to True

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1968]
### Environment

Second Life Release 7.1.9.9688089989 (64bit)
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4529)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1665x1316
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (99.9% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version:  

July 09 2024 13:21:47

### Description

Debug setting VoiceMorphingEnabled should default to True.
It currently defaults to False on the WebRTC viewer.

### Reproduction steps

1. Start the viewer, and stay at the login screen.
2. Enable Preferences > Advanced > Show Advanced Menu. Click OK
3. Open Debug menu > Show Debug Settings
4. Search for VoiceMorphingEnabled and find the state

Observed: It is set to FALSE in 7.1.9.9688089989.

Expected: It should be set to TRUE.

**Comment by brad-linden** [comment]
Is this integrated as of PR secondlife/viewer#1915?

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.9.10084807842 (64bit) on Win10/OSX in the scope of [IQA #293](https://github.com/secondlife/iqa/issues/293).
