### ISSUE TITLE
OpenGL Vertex Buffer

### ISSUE THREAD

**Issue by ghost** [secondlife/viewer#1971]
need option setting back in settings for OpenGL Vertex Buffer to disable it on by default lags and crashes to much

https://developer.valvesoftware.com/wiki/VERTEX_BUFFER_SIZE

**Comment by brad-linden** [comment]
I'm sorry we do not plan to add a setting for diabling Vertex Buffers.  Please file issues about your lag problems or crashes at https://feedback.secondlife.com/
