### ISSUE TITLE
The "Region/Estate Environment" floater is closed after teleporting to another location or region

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#1974]
### Environment

Second Life Release 7.1.9.9620320242 (64bit)
Release Notes

You are at 213.5, 106.7, 21.5 in Product Engine located at simhost-0e1ba50d324fbebb0.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/213/107/22
(global coordinates 336,853.0, 307,307.0, 21.5)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3696 MHz)
Memory: 32688 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4598)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT

Windows Graphics Driver Version: 26.20.15029.27017
OpenGL Version: 4.6.13587 Core Profile Context 20.4.2 26.20.15029.27017

Window size: 1920x1017
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (1.9% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/1,661 (0.0%)
July 10 2024 04:55:51

### Description

See Reproduction steps.

### Reproduction steps

1. Open the viewer and log in.
2. Open "World"→"Region/Estate"→"Environment" tab.
3. Teleport to another location/region.

**Actual result:**
The "Region/Estate Environment" floater is closed after teleporting to another location or region.

**Expected result:**
The "Region/Estate Environment" floater should be opened after teleporting to another location or region.

**Note:**
This issue is reproduced on Win10/OSX.

According to the [FUI: Environment Settings (WRLS) Test Plan](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2699788968/FUI+Environment+Settings+WRLS+Test+Plan#1.4-Region%2FEstate-%3E-Environment-UI-controls).
**Section**: 1.4 Region/Estate > Environment UI controls.
**Step**: 6. Teleport or fly to the region you don’t own w/o closing the floater
Verify controls become disabled as soon as you cross the border or teleport finishes.

**Also**, this issue is not reproduced when crossing region borders.

This issue is **reproduced** on the current production build Second Life Release 7.1.8.9375512768.

**Comment by AtlasLinden** [comment]
Treating this as expected behaviour.
The test plan will be updated to reflect this.
