### ISSUE TITLE
The "Main dictionary" option is switched to the previous value after rechecking the "Enable spell checker" checkbox in the "Preferences" "Chat" tab "Spell checker settings" floater

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#1990]
### Environment

Second Life Release 7.1.9.9620320242 (64bit)
Release Notes

You are at 213.4, 107.8, 21.5 in Product Engine located at simhost-0e1ba50d324fbebb0.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/213/108/22
(global coordinates 336,853.0, 307,308.0, 21.5)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3696 MHz)
Memory: 32688 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4651)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT

Windows Graphics Driver Version: 26.20.15029.27017
OpenGL Version: 4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27017

Window size: 1920x1017
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (0.1% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/2,649 (0.0%)
July 11 2024 05:34:57

### Description

See Reproduction steps.

### Reproduction steps

1. Open the viewer and log in.
2. Click "Me"→"Preferences"→"Chat" tab.
3. Click the "Spell Checking..." button.
4. Check the "Enable spell checker" checkbox.
5. Click the "Main dictionary" dropdown menu and choose any other dictionary option.
6. Toggle to uncheck the "Enable spell checker" checkbox.
7. Toggle to check the "Enable spell checker" checkbox.
8. Observe the "Main dictionary" option.

**Actual result:**
The "Main dictionary" option is switched to the previous value after rechecking the "Enable spell checker" checkbox in the "Preferences" "Chat" tab "Spell checker settings" floater.

**Expected result:**
The "Main dictionary" option should have the same value after rechecking the "Enable spell checker" checkbox in the "Preferences" "Chat" tab "Spell checker settings" floater.

**Note:**
This issue is reproduced on Win10/OSX.

This issue was found during ad-hoc testing.

**Also**, the "Main dictionary" option is saved after closing and reopening the "Spell checker settings" floater.

This issue is **reproduced** on the current production build Second Life Release 7.1.8.9375512768.

**actual.mp4**
https://github.com/secondlife/viewer/assets/150431068/8f995caa-4df3-4897-9b86-5766bd1fe74a

**Comment by katerynamproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.10.10516785745 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
