### ISSUE TITLE
The application of terrain textures and texture elevation ranges does not occur as expected in the "Terrain" tab in the "Region/Estate" floater

### ISSUE THREAD

**Issue by DmitrySProductengine** [secondlife/viewer#2006]
### Environment
<details><summary>Environment</summary>
<p>

Second Life Release 7.1.9.9620320242 (64bit)
Release Notes

You are at 109.1, 110.3, 22.7 in Product Engine 3 located at simhost-0824be1f81f5cc42f.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%203/109/110/23
(global coordinates 336749.0, 307054.0, 22.7)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2600 MHz)
Memory: 16384 MB
OS Version: macOS 14.5.0 Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-5.5.17

Window size: 1172x1061
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (31.8% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/3993 (0.0%)
July 12 2024 01:59:52

</p>
</details> 

### Reproduction steps

1. Download and install the Second Life Release 7.1.9.9620320242 viewer (https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2308f2236-atlasaurus).
2. Launch the Viewer and log in as an estate manager or owner.
3. Open the Terrain tab (World - Region/Estate - Terrain).
4. Change any terrain texture and click the ‘Apply’ button.
5. Change any other terrain texture and click the “Apply” button again.

**Actual result:**
The application of terrain textures and texture elevation ranges does not occur as expected in the "Terrain" tab in the "Region/Estate" floater.
Each time you click the “Apply" button, some changes are applied, but some previous changes are also returned.

**Expected result:**
The application of terrain textures and texture elevation ranges should occur as expected in the "Terrain" tab in the "Region/Estate" floater.
All current values should be applied each time you click the “Apply” button.

**Additional information:**
According to the ‘FUI: Region/Estate Test Plan’ - 3. Terrain Tab - [3.3 Set ground textures - 3.5 Texture Elevation Ranges](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2699919361/FUI+Region+Estate+Test+Plan#3.3-Set-ground-textures).
This issue was found in the scope of [IQA #245](https://github.com/secondlife/iqa/issues/245).
This issue is reproduced on Win10 and OSX.

This issue is reproduced for terrain textures and texture elevation ranges.
Also, this issue is reproduced for PBR Metallic Roughness.

This issue is not reproduced on the current release 7.1.8.9375512768 build.

The current behavior is like changes to textures and parameters are applied - but these changes are not reflected in the floater. And when you further change other textures, you get an overlay of different settings.

See attached videos:
1. ‘Actual - 7.1.9.9620320242 - terrain textures.mp4’:

https://github.com/user-attachments/assets/dffd133c-4e57-43c5-b8be-f94f9828edba

2. ‘Actual - 7.1.9.9620320242 - texture elevation ranges.mp4’:

https://github.com/user-attachments/assets/ff7b12a6-947f-4a02-9004-a5c7138b35e5

**Comment by AtlasLinden** [comment]
Reopening for testing

**Comment by georgebproductengine** [comment]
Passed QA.
Verified  on the Second Life Release 7.1.10.10516785745 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
