### ISSUE TITLE
OSMessageBoxWin32 shows message box behind the viewer window

### ISSUE THREAD

**Issue by LLGuru** [secondlife/viewer#2029]
### Environment

SecondLife viewer any win64 build

### Description

In some cases (e.g., runtime error message and user click the window)
OSMessageBoxWin32 shows message box behind the viewer window

As a result, the user doesn't see this message box and can't interact with it until switches between windows

### Reproduction steps

- Start viewer
- Double click top menu `Develop` | `Force an Error` | `Force LLError And Crash`
![image](https://github.com/user-attachments/assets/c3cad4a3-408a-4041-a3e5-81465dea3433)

**Comment by LLGuru** [comment]
- Fixed in https://github.com/secondlife/viewer/pull/2031

**Comment by AtlasLinden** [comment]
Reopening for testing

**Comment by valeriiaaproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10582490681 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
