### ISSUE TITLE
Bugsplat crash reports differ between Mac and Windows 

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2043]
### Environment

Second Life Release 7.1.9.9865199239 (64bit) on Win10/OS X

### Description

As commented from [vladyslavasproductengine](https://github.com/vladyslavasproductengine) here: https://github.com/secondlife/viewer/issues/1826#issuecomment-2230595873 and https://github.com/secondlife/viewer/issues/1839#issuecomment-2230609573

Forced crashes are being reported differently between Windows and Mac. Mac OS crashes fail to resolve.

### Reproduction steps

Force LLError crash https://github.com/secondlife/viewer/issues/1826
Force Watchdog crash https://github.com/secondlife/viewer/issues/1839

**Comment by akleshchev** [comment]
Likely cause: https://github.com/secondlife/viewer/commit/45cd21f7e1f87da60bfe16944267371f8a518799

At the moment I'm not sure if I should change it back or update upload script.
I manually uploaded symbols and crashes reprocessed correctly, so this isn't a blocker for the viewer, just an inconvinience,

**Comment by igorlproductengine** [comment]
This issue is reproduced on the Second Life Release 7.1.9.9981869229 (64bit) in the scope of https://github.com/secondlife/iqa/issues/286 on Win10/OSX system.

Actual: 
<img width="1659" alt="Screenshot 2024-07-19 at 14 29 06" src="https://github.com/user-attachments/assets/dbac63b7-55f6-4ad4-a793-a5df8115186b">

**Comment by valeriiaaproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10622905308 (64bit) on Win11/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
