### ISSUE TITLE
Crash in ~LLScriptEdCore()

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#2061]
### Environment

Second Life Release 7.1.9.9851691213 (64bit)

### Description

Crash in ~LLScriptEdCore() on "delete script_search"

### Reproduction steps

Potential scenario:
- Open a script
- Open script's search floater (edit->Search/Replace), detach it from parent floater
- Force a Disconnect
- Wait for half a minute
- Quit

Bugsplat example: https://app.bugsplat.com/v2/crash?database=SecondLife_Viewer_2018&id=1490806

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.10.10516785745 (64bit) on Win11/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
