### ISSUE TITLE
After crossing from a WebRTC region to another WebRTC region the spatial voice dot of nearby people is off.

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#2064]
### Environment

Second Life Release 7.1.9.9688089989 (64bit)
Release Notes

You are at 19.4, 121.4, 22.9 in webRTC2 located at simhost-02bfc572742fa99b4.aditi
SLURL: secondlife://Aditi/secondlife/webRTC2/19/121/23
(global coordinates 260,115.0, 245,369.0, 22.9)
WebRTC-Voice 2024-06-24.9652733849
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4651)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1665x1316
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/3,977 (0.0%)
July 18 2024 09:39:42

### Description

After crossing into a region the spatial voice dot of nearby people is off.

### Reproduction steps

Repro:
1. User1 log into the middle of WebRTC1 region on Aditi
2. User2 log into the middle of WebRTC2 region on Aditi
3. User2 fly over to User1 on WebRTC2

Observed: User1 and User2 cannot see a voice dot for each other. User1 and User2 **can** hear each other.

https://github.com/user-attachments/assets/5143490d-e133-4823-8039-0c20d4d76eed

Attached [testerd2 SecondLife.log](https://github.com/user-attachments/files/16286748/testerd2.SecondLife.log) who is User2 in the test scenario.

Expected: User1 and User2 should see the voice dot for each other.

**Comment by akleshchev** [comment]
Still a problem. Dot is missing, but voice works.

**Comment by akleshchev** [comment]
Appears to be server sided. LLVoiceWebRTCConnection::OnDataReceived() did not trigger, I expected server to provide info that a client joined, but it didn't.

**Comment by roxanneskelly** [comment]
Okay, I think I fixed most of the cases where this might happen.  There are associated server fixes which have been applied to Aditi, WebRTC1 and WebRTC2.

**Comment by dmytrohproductengine** [comment]
Deferred QA.
Verified on the Second Life Release 7.1.9.10479800881 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/311.

A new issue on WebRTC regions:
[secondlife/viewer/issues/2376](https://github.com/secondlife/viewer/issues/2376) - The viewer (Atlasaurus RC 7.1.9.10479800881) freezes on WebRTC regions if logged in with Voice Chat enabled.

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.9.10495892574 (64bit) on Win11/OSX in the scope of [IQA #312](https://github.com/secondlife/iqa/issues/312).
Tested on Aditi:
1. WebRTC-WebRTC:  
secondlife://Aditi/secondlife/webRTC1/128/128/23
secondlife://Aditi/secondlife/webRTC2/128/128/23
Sim: WebRTC-Voice 2024-08-15.10397494850
Voice: Secondlife WebRTC Gateway 

2. Vivox-Vivox:
secondlife://Aditi/secondlife/vivox1/128/128/23
secondlife://Aditi/secondlife/vivox2/128/128/23
Sim: Second Life Server 2024-07-22.10048683488
Voice: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

3. WebRTC-Vivox:  
secondlife://Aditi/secondlife/webRTC2/83/247/23
Sim: WebRTC-Voice 2024-08-15.10397494850
Voice: Secondlife WebRTC Gateway 
secondlife://Aditi/secondlife/vivox1/128/128/23
Sim: Second Life Server 2024-07-22.10048683488
Voice: Vivox 4.10.0000.32327.5fc3fe7c.5942f08
