### ISSUE TITLE
Add UI for Region Restart functionality

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2065]
### Environment

Second Life Release 7.1.8.9375512768 (64bit)
Release Notes

You are at 6.6, 200.2, 23.1 in Pasta Cake located at simhost-0bcc34323c1ea6cea.agni
SLURL: http://maps.secondlife.com/secondlife/Pasta%20Cake/7/200/23
(global coordinates 332,039.0, 305,608.0, 23.1)
Second Life Server 2024-06-11.9458617693

### Description

Add UI for the Region Restart functionality that currently exists via the Region Debug console.

### Reproduction steps

See https://github.com/secondlife/roadmap/issues/165 and [wiki](https://wiki.secondlife.com/wiki/Region_Debug_Console#:~:text=ENTER%7D%7D%0Arestart%20%7B%7BENTER%7D%7D-,Schedule%20region%20restarts,-Private%20region%20owners) 

### Notes
https://github.com/secondlife/server/issues/463

**Comment by dmytrohproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10582490681 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.

**Also**, the "Restart the region on following days:" text is shown in the "Region Restart Schedule" floater (see "iqa#320_7.1.10.10582490681.png").
According to https://github.com/secondlife/roadmap/issues/165, the text should be "Restart the region on **the** following days:".

**iqa#320_7.1.10.10582490681.png**
![iqa#320_7 1 10 10582490681](https://github.com/user-attachments/assets/76d34bf7-f275-480f-be6c-50517faff719)
