### ISSUE TITLE
WebRTC viewer occasionally does not see spatial voice dot for other user on vivox region.

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#2067]
### Environment

Second Life Release 7.1.9.9688089989 (64bit)

### Description

No voice dot

### Reproduction steps

1. User1 (Mac) and User2 (Windows) logged into vivox1 region on Aditi with WebRTC 7.1.9.9688089989 viewers.

Observed: Neither person could see the others' voice dot. Hopefully the logs have clue.

Expected: The users should be able to chat in spatial voice.

Log for User1 [User1 mac SecondLife.log](https://github.com/user-attachments/files/16287214/User1.mac.SecondLife.log)

Log for User2 [User2 windows SecondLife.log](https://github.com/user-attachments/files/16287167/User2.windows.SecondLife.log)

Note: This also reproduces on Agni with the WebRTC viewer. [User2 windows AGNI SecondLife.log](https://github.com/user-attachments/files/16289900/User2.windows.AGNI.SecondLife.log) I relogged user2 until the failure happened while User1 remained logged in.

**Comment by roxanneskelly** [comment]
The logs say the connection should have been fine.  Vivox issue?  We should try to repro this a bit more, I fear.

**Comment by bridie-linden** [comment]
See https://github.com/secondlife/triage/issues/304 for repro

**Comment by bridie-linden** [comment]
Closing, Vivox - 'won't fix'
