### ISSUE TITLE
After transition through WebRTC -> Vivox -> WebRTC regions, voice dot is on but no voice is transmitted.

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#2074]
### Environment

Second Life Release 7.1.9.9688089989 (64bit)
Release Notes

You are at 128.0, 127.8, 22.7 in webRTC2 located at simhost-02bfc572742fa99b4.aditi
SLURL: secondlife://Aditi/secondlife/webRTC2/128/128/23
(global coordinates 260,224.0, 245,376.0, 22.7)
WebRTC-Voice 2024-06-24.9652733849
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.91 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4651)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1665x1316
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/432 (0.0%)
July 19 2024 15:46:58

### Description

 WebRTC -> Vivox -> WebRTC region transition breaks voice. In this case it caused transmitting voice to fail.

### Reproduction steps

1. Log 2 WebRTC viewers into WebRTC2 on Aditi, and verify they can chat in spatial voice.
2. Teleport both to Vivox1, and verify they can chat in spatial voice.
3. Fly both to WebRTC1, and verify they can chat in spatial voice.

Observed: The voice dot is on but there are no green waves when I speak, and the other person cannot hear me.
I had a 3rd user logged into WebRTC1. The 2 test users could hear that third user speak.

Expected: The 2 users should be able to speak to each other.

Log for User2: [user2 voice dot on but cannot transmit SecondLife.log](https://github.com/user-attachments/files/16317580/user2.voice.dot.on.but.cannot.transmit.SecondLife.log)

**Comment by vladyslavasproductengine** [comment]
Deferred QA. 
A new issue on WebRTS regions:
secondlife/viewer/issues/2376 -  The viewer (Atlasaurus RC 7.1.9.10479800881) freezes on WebRTS regions if logged in with Voice Chat enabled.
	
Verified on the Second Life Release 7.1.9.10479800881 (64bit) on Win10/OSX in the scope of secondlife/iqa#311.
