### ISSUE TITLE
Scroll wheel support for LLComboBox

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#2082]
Contribution by [RyeMutt](https://github.com/RyeMutt) https://github.com/secondlife/viewer/pull/2081

## Test Plan

1. Hover mouse over a combo box without opening it
2. Use mouse wheel

Notes:
- At the moment this only work with the list collapsed.
- Not directly related but needs checking: wheel event pass right through the list and interract with the lement underneath it, not directly related, because it's the same for any menu (doesn't have a ticket yet).

**Comment by dmytrohproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10582490681 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.

**Also**, scrolling by the mouse wheel does not scroll up in the destination field on the regular login screen (see [secondlife/viewer/issues/2454](https://github.com/secondlife/viewer/issues/2454)).
