### ISSUE TITLE
[Contribution] Replace uriparser with boost::url

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#2139]
Replace liburiparser with boost::url
Benefits include:

- Removing the mac signal handler hack
- Fixing several obscure crashes by not relying on liburiparser
- Reducing dependency chain size

Includes updated boost to vertion 1.85

Link: https://github.com/secondlife/viewer/pull/2136

## Test Plan

1. Confirm boost was updated to version 1.85 or higher (help->about -> licenses)
2. Confirm uriparser was excluded (help->about -> licenses)
3. Confirm basic Url and Slurl functionality works (links appear in chat and work), location in navigation bar display path corretly.

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10622905308 (64bit) on Win11/OSX in the scope of [IQA #316](https://github.com/secondlife/iqa/issues/316).
