### ISSUE TITLE
Add tooltip to the region Object Return button to clarify who "someone else" means.

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#2144]
### Environment

Second Life Release 7.1.9.9620320242 (64bit)

### Description

Some unclear terminology was highlighted in https://github.com/secondlife/server/issues/1246. 
In World -> Region/Estate -> Debug, there is an option to return objects ‘On someone else's land.' 
It could be read to mean "return the selected users' objects that are not on land owned by the person pushing the button" (an estate owner or estate manager).
Change the UI or tooltip to make it clear the "On someone else's land" means any parcel on the region that is not owned by the selected user.
![image](https://github.com/user-attachments/assets/6a48755c-0c82-4059-a5e1-5b84a8c59a0b)

### Reproduction steps

1. Launch the Viewer and log in as User A (an estate manager or owner) and User B.
2. User B - create a new object on a parcel owned by User A.
3. User A - open the Debug tab (World - Region/Estate - Debug).
4. User A - choose User B in the Object Return field and select the option ‘On someone else's land.
5. Confirm that the UI clearly communicates that the Return button will return all objects owned by the selected user from any parcel on the region that is not owned by the selected user.

**Comment by vladyslavasproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.10.10516785745 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
