### ISSUE TITLE
The “position indicator” does not appear when dragging a button from a toolbar to a new location on the toolbar

### ISSUE THREAD

**Issue by valeriiaaproductengine** [secondlife/viewer#2157]
### Environment

Second Life Test 7.1.9.10164740217 (64bit)
Release Notes

You are at 187.1, 68.0, 21.5 in Product Engine located at simhost-0da6f9eb199bf00ca.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/187/68/21
(global coordinates 336,827.0, 307,268.0, 21.5)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz (2611.2 MHz)
Memory: 16111 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4651)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.2879
OpenGL Version: 4.6.0 NVIDIA 528.79

Window size: 1920x1001
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 4095MB
Disk cache: Max size 1638.4 MB (33.4% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 218/108,238 (0.2%)
July 31 2024 03:13:20

### Description

See Reproduction steps.

### Reproduction steps

1. Log into the Second Life Test 7.1.9.10164740217 (64bit) viewer.
2. Hold any button on the Left or Bottom toolbar and try dragging it.

**Actual result:** The “position indicator” does not appear when dragging a button from a toolbar to a new location on the toolbar.
**Expected result:** The “position indicator” should appear when dragging a button from a toolbar to a new location on the toolbar.

**Note:**
This issue was found according to the full test plan: https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2691694612/FUI+ToyBox+Toolbars+Regression+Test+Plan.  ->
5. Toolbar buttons re-ordering.
с. Verify there is a “position indicator” when you point near another button.

This issue is not reproduced on the production viewer. (Second Life Release 7.1.8.9375512768).
This issue is reproduced on WIn10 and OSX.

See actual.mp4 videorecording:

https://github.com/user-attachments/assets/cb894564-5d1c-4ba4-bd28-ea618b8e4aa4

See expected.png screenshot: 
![expected](https://github.com/user-attachments/assets/938a90b8-008c-4bca-9323-89d98fd084f7)

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.10.10516785745 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
