### ISSUE TITLE
Loaded chat logs have no limits on the number of lines

### ISSUE THREAD

**Issue by DmitrySProductengine** [secondlife/viewer#2158]
### Environment
<details><summary>Environment</summary>
<p>

Second Life Test 7.1.9.10164740217 (64bit)
Release Notes

You are at 100.8, 118.0, 21.5 in Product Engine 3 located at simhost-06c92da1cee01d90f.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%203/101/118/22
(global coordinates 336741.0, 307062.0, 21.5)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2600 MHz)
Memory: 16384 MB
OS Version: macOS 14.5.0 Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-5.5.17

Window size: 1132x1061
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (0.2% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/579 (0.0%)
July 31 2024 07:04:22

</p>
</details> 

### Reproduction steps

**Steps to reproduce:**
1. Download and install the Second Life Test 7.1.9.10164740217 viewer (https://github.com/secondlife/viewer/releases/tag/Second_Life_Project_B_Develop%232ee039c).
2. Launch 2 viewer instances and log in as residents A and B.
3. Resident B: send more than 50 messages to Resident A via IM, group chat, and Nearby chat.
4. Resident A: re-enter the viewer and open all chats with Resident B.

**Actual result:**
Loaded chat logs have no limits on the number of lines.

**Expected result:**
Loaded chat logs should have a limit of 46-49 lines (possibly 35).

**Additional information:**
According to the ‘Chat Logging Test plan’ - [Loading Logs](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2693038153/Chat+Logging+Test+plan#Loading-Logs).
This issue was found in the scope of [IQA #295](https://github.com/secondlife/iqa/issues/295).
This issue is reproduced on Win10 and OSX.

This issue is reproduced on the current release 7.1.8.9375512768 build.

This limit change is most likely related to implementing a new feature for the group chat log - https://github.com/secondlife/jira-archive-internal/issues/68484.

The lack of a limit may be the new expected behavior, but then the test plan needs to be updated. But it is also possible that this behavior is erroneous and the limit on loaded lines should still be present.

See attached screenshots:
1. Actual - Second Life Test 7.1.9.10164740217:
<img width="1920" alt="Actual - Second Life Test 7 1 9 10164740217" src="https://github.com/user-attachments/assets/72510630-c9aa-4ab8-89a6-c8e17fa998e0">

2. Actual - current release 7.1.8.9375512768:
<img width="1920" alt="Actual - current release 7 1 8 9375512768" src="https://github.com/user-attachments/assets/61781168-fa4f-4a10-951f-256dbfd7564d">

**Comment by AtlasLinden** [comment]
This chat log limit that is displayed upon logging in was actually increased in order to support emojis (i.e. multibyte characters) as part of https://github.com/secondlife/viewer-private/issues/61.
It seems the limit was multiplied by 10. 
So there is still a limit to the displayed chat log upon login. It's now just a lot larger than before. 
Notes will be added to the mentioned test plan.

Closing this as expected behaviour.
