### ISSUE TITLE
Replace jpeglib with libjpeg-turbo

### ISSUE THREAD

**Issue by RyeMutt** [secondlife/viewer#2161]
This would replace jpeglib with the modern and jpeglib api compatible libjpeg-turbo library for faster encoding/decoding of jpeg format images. Also upside it updates away from a library version from 2011.

I'll need https://github.com/RyeMutt/3p-libjpeg-turbo imported and a build published to go forward with the viewer contribution.

## Test Plan
- Save a screenshot in jpeg format
- Upload a jpeg format image

**Comment by bennettgoble** [comment]
Reviewed, forked and published an initial release here, https://github.com/secondlife/3p-libjpeg-turbo --thanks, Rye.
