### ISSUE TITLE
The "Voice morphs are not supported by this viewer" notification does not have a correct description in the settings 'Always show/Never show' for notifications

### ISSUE THREAD

**Issue by valeriiaaproductengine** [secondlife/viewer#2195]
### Environment

Second Life Release 7.1.9.10205353598 (64bit)
Release Notes

You are at 94.0, 202.2, 21.5 in Product Engine located at simhost-0da6f9eb199bf00ca.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/94/202/21
(global coordinates 336,734.0, 307,402.0, 21.5)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz (2611.2 MHz)
Memory: 16111 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4651)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.2879
OpenGL Version: 4.6.0 NVIDIA 528.79

Window size: 1920x1001
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 4095MB
Disk cache: Max size 1638.4 MB (4.1% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 13/4,044 (0.3%)
August 05 2024 07:50:24

### Description

See Reproduction steps.

### Reproduction steps

1. Launch the Second Life Release 7.1.9.10205353598 viewer.
2. Open debug settings at the login screen and set VoiceMorphEnabled to true and VoiceEffectDefault to 'f0000000-0000-0000-0000-000000000000' (or any UUID other than the null UUID).
3. Login to the viewer.
4. Check the "Don't show me this again" checkbox in the "Voice morphs are not supported by this viewer" warning message and click ok.
5. Open Preferences-> Notifications tab.
6. Observe the "Never show:" section.

**Actual result:** The "Voice morphs are not supported by this viewer" notification does not have a correct description in the settings 'Always show/Never show' for notifications. The "$ignoretext" is displayed.

**Expected result:** The "Voice morphs are not supported by this viewer" notification should have a correct description in the settings 'Always show/Never show' for notifications.

**Note:**
This issue is reproduced on Win10/OSX.
This issue is reproduced on Aditi- WebRTC(WebRTC-Voice 2024-06-24.9652733849 ), Vivox (Second Life Server 2024-06-11.9458617693) regions and on Agni Productengine regions.
This issue was found while checking the [1451](https://github.com/secondlife/viewer/issues/1451) ticket.

See actual.png screenshot:
![actual](https://github.com/user-attachments/assets/e61ff6f3-88c5-41f2-9bbc-50c25527ec20)

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.9.10325451220 (64bit) on Win11/OSX in the scope of [IQA #304](https://github.com/secondlife/iqa/issues/304).
This notification is now described as: ‘Warn me about voice morph not being supported’.
