### ISSUE TITLE
Viewer lost voice dot in spatial chat on Vivox region

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#2199]
### Description

I lost my voice dot in spatial chat after being logged in about 10 minutes. I was just sitting there and chatting with 4 other people, nothing special.

### Reproduction steps

1. Log into a vivox region with the WebRTC viewer.
2. Chat with 4 other users in spatial chat?

Observed: It worked fine for about 10 minutes and then I could not hear anyone else. I saw voice dots for everyone else in spacial chat but could not hear them. My own voice dot was not present in my Conversations window. Other people said they could not see my voice dot. 

Attached logging with extra voice debug:
[lost voice dot on vivox region SecondLife.log](https://github.com/user-attachments/files/16501079/lost.voice.dot.on.vivox.region.SecondLife.log)

<details>
<summary>Environment</summary>
Second Life Release 7.1.9.10205353598 (64bit)
Release Notes

You are at 118.3, 90.0, 21.9 in By Design located at simhost-06c9a56af17a2102e.agni
SLURL: http://maps.secondlife.com/secondlife/By%20Design/118/90/22
(global coordinates 261,494.0, 246,874.0, 21.9)
Second Life Preflight 2024-06-11.9458617693
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.91 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4651)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1722x1315
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/2,147 (0.0%)
August 05 2024 10:49:21
</details>

**Comment by Dan-Linden** [comment]
I later lost voice while using the Release 7.1.8.9375512768 viewer so this is not a WebRTC issue.
[lost voice on Release SecondLife.log](https://github.com/user-attachments/files/16503258/lost.voice.on.Release.SecondLife.log)

**Comment by roxanneskelly** [comment]
Got a timeout while attempting to talk to the vivox server.  We might need a repro.  I think Vivox has settled down their issues, now.

**Comment by Dan-Linden** [comment]
Since this also reproduced with a [vivox-only 7.1.8.9375512768 viewer](https://github.com/secondlife/viewer/issues/2199#issuecomment-2270018343), I propose this can be closed as won't fix.

**Comment by bridie-linden** [comment]
Closed as won't fix!
