### ISSUE TITLE
Bulk upload makes an incorrect cost estimate for a 1793x896 texture.

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#2212]
### Environment

Second Life Release 7.1.8.9375512768 (64bit)
Release Notes

You are at 82.9, 21.6, 23.4 in TextureTest located at simhost-06c9a56af17a2102e.agni
SLURL: http://maps.secondlife.com/secondlife/TextureTest/83/22/23
(global coordinates 259,923.0, 248,854.0, 23.4)
Second Life Preflight 2024-06-11.9458617693
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.91 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4651)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1722x1315
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 5/54,887 (0.0%)
August 06 2024 16:32:52

### Description

Bulk upload of a 1793x896 texture incorrectly expects the texture will cost 50L$, so the upload is rejected.

### Reproduction steps

1. Build > Upload > Bulk... and choose the attached "1793x896 becomes 2048x512.png"

Observed: The dialog incorrectly says "This will upload 1 items at a total cost of L$50. Do you with to continue with the upload?"
(Attempting to upload the texture correctly fails because the estimate is incorrect.)

Expected: The bulk upload should use the same estimate as Build > Upload > Image... which correctly estimates this is a L$10 upload (because total pixels <= 1k x 1k).

![1793x896 becomes 2048x512](https://github.com/user-attachments/assets/393ca5c1-84f3-4ebc-93a9-e6e0415cc150)

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.10.10516785745 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
