### ISSUE TITLE
A modal dialog “You are about to enable AutoFPS..” is displayed after clicking the "Auto-adjust now" button.

### ISSUE THREAD

**Issue by vladyslavasproductengine** [secondlife/viewer#2291]
### Environment

Second Life Test 7.1.9.10164740217 (64bit)
Release Notes

You are at 125.1, 129.9, 22.5 in Product Engine 2 located at simhost-02ddae96b0613bb32.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%202/125/130/23
(global coordinates 337,021.0, 307,330.0, 22.5)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (2712 MHz)
Memory: 8067 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4651)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: GeForce 940MX/PCIe/SSE2

Windows Graphics Driver Version: 25.21.14.1735
OpenGL Version: 4.6.0 NVIDIA 417.35

Window size: 1920x1001
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 96m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 2048MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/1,452 (0.0%)
August 14 2024 04:56:45

### Description

see description

### Reproduction steps

Reproduction steps
1. Install, open the viewer and log in.
2. Open Word->Improve graphics speed->Auto adjust settings
3. Uncheck ‘Enable Vsync’
4. Enter a very high desired frame rate for your machine (300 for instance)
5. Select ‘Auto-adjust now’ 

Actual result:
 A modal dialog “You are about to enable AutoFPS..” is displayed after clicking the "Auto-adjust now" button.

Expected result:
The ‘Auto-adjust now’ button should grey out, the Cancel button should become enabled and text appears that states “Working on it….

Note:
This issue is reproduced on Win10/OSX.
This issue was found acording to the test plan:  Settings affect & Auto-adjust now
https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2953248839/Improve+Graphics+Speed+Floater+Test+Plan
This issue is produced only first time enter after  accepting settings.
This issue is reproduced on the current production build Second Life Release 7.1.8.9375512768 (64bit).
Screenshots:
![actset](https://github.com/user-attachments/assets/41c51dd5-59a6-4d47-bb7d-375f0a5200d3)

**Comment by AtlasLinden** [comment]
I'd say this is expected behaviour but I'm currently unsure as to what causes the popup and I'm unable to reproduce it on either this build in testing or prod.

**Comment by vladyslavasproductengine** [comment]
@AtlasLinden Hello!
This happens when you first log into the viewer or when you clear the secondlife folder on Win10/OSX.
Also,This issue is reproduced on the current production build Second Life Release 7.1.8.9375512768 (64bit).
