### ISSUE TITLE
[WebRTC] Are you sure you want to leave this call prompt on shutdown

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#2296]
### Environment

Second Life Release 7.1.9.10205353598 (64bit)

### Description

"Are you sure you want to leave this call" pops up on shutdown for a second

Expected:
Either to not show the prompt or to not shutdown

### Reproduction steps

Start an IM call, shutdown viewer without stopping the call.

**Comment by dmytrohproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.9.10495892574 (64bit) on Win10/OSX in the scope of [secondlife/iqa#312](https://github.com/secondlife/iqa/issues/312).

After clicking the 'Close viewer' button, the 'You have ended the call. You will now be reconnected to Nearby Voice Chat' a pop-up message is shown and the viewer closes automatically (see "iqa#312_7.1.9.10495892574.mp4").

**iqa#312_7.1.9.10495892574.mp4**
https://github.com/user-attachments/assets/8a05c75b-cb71-4ead-8c5b-84f685f3ded9
