### ISSUE TITLE
"Create folder from selected" option is missing from the context menu for the "Listing" and "Version" folders of the "Marketplace Listings" floater

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#2304]
### Environment

Second Life Test 7.1.9.10164740217 (64bit)
Release Notes

You are at 141.6, 141.9, 25.3 in Ahern located at simhost-078bc7cb89e0e2550.damballah
SLURL: https://util.damballah.lindenlab.com/region/Ahern/142/142/25
(global coordinates 255,374.0, 256,654.0, 25.3)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3695.99 MHz)
Memory: 32688 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4780)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT

Windows Graphics Driver Version: 26.20.15029.27017
OpenGL Version: 4.6.13587 Core Profile Context 20.4.2 26.20.15029.27017

Window size: 1920x1017
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (2.2% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/399 (0.0%)
August 15 2024 03:20:22

### Description

See reproduction steps.

### Reproduction steps

1. Download and install the [Second Life Test 7.1.9.10164740217 (64bit)](https://github.com/secondlife/viewer/releases/tag/Second_Life_Project_B_Develop%232ee039c) build.
2. Log in with a merchant account.
3. Click "Me"→"Marketplace listings...".
4. Right-click on any listing folder.
5. Observe the context menu.
6. Left-lick on any listing folder.
7. Right-click on the version folder.
8. Observe the context menu.

**Actual result:**
The "Create folder from selected" option is missing from the context menu for the "Listing" and "Version" folders of the "Marketplace Listings" floater.

**Expected result:**
The "Create folder from selected" option should be present in the context menu for the "Listing" and "Version" folders of the "Marketplace Listings" floater.

**Note:**
This issue is reproduced on Win10/OSX.

According to the [Viewer Managed Marketplace Viewer Test Plan](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2699985032/Viewer+Managed+Marketplace+Viewer+Test+Plan) test plan.
Section: Test 6: Right click menu options on Listing and Version folders.

Actual right-click menu options on the Listing and Version folders were pointed out in the test plan comments.

**Listing folder:**
Create listing
Associate listing
Check for errors
Edit listing
List
Unlist
New folder
Image...
Rename
Cut
Copy
Paste
Paste As Link
Delete
Create folder from selected

**Version folder:**
Edit listing
Activate
Deactivate
New folder
Image...
Rename
Cut
Copy
Paste
Paste As Link
Delete
Create folder from selected

This issue is **not** reproduced on the current production build Second Life Release 7.1.8.9375512768 (see "expected_release_listing.png" and "expected_release_version.png").

**actual_test_listing.png**
![actual_test_listing](https://github.com/user-attachments/assets/ad518c53-6f6d-490b-aae2-4df4b0b6402b)
**actual_test_version.png**
![actual_test_version](https://github.com/user-attachments/assets/3b37a472-fb00-4fa6-957d-c204665ee1da)
**expected_release_listing.png**
![expected_release_listing](https://github.com/user-attachments/assets/ec7a6c50-5547-451c-a8b7-d22c188ab42e)
**expected_release_version.png**
![expected_release_version](https://github.com/user-attachments/assets/83b68b23-e079-43c4-9808-a19297420185)

**Comment by akleshchev** [comment]
Related: https://github.com/secondlife/viewer-private/issues/251

**Comment by akleshchev** [comment]
This was changed in https://github.com/secondlife/triage/issues/163 (I think there was a discussion in slack to that effect)

Reasons:
1. It bypasses nesting limit
2. Moving or deleting listing folders is supposed to warn about deleting associated folders yet it lacks those normal warnings
3. After use of 'Create folder from selected' marketplace ends up in a weird state where listing folder is inside another listing folder. Like this: 
![image](https://github.com/user-attachments/assets/0432c0b3-ea46-407f-877b-d160a911cf6d)

marketplace doesn't like changes in hierarhy and "Create folder from selected" is a change in hierarhy, so at minimum it shouldn't work for top two folders (listings and stock?).

I can enable "Create folder from selected" for version folders and below but is there any scenario when it's usefull?

**Comment by AtlasLinden** [comment]
Confirmed by Kurt, this "Create folder from selected" isn't required or necessary and may cause the issues mentioned by Caladbolg above. Treating this 'missing option' as expected behaviour and closing.
