### ISSUE TITLE
Ensure textures unload when region unloads

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#2315]
### Description

Test (on beta grid):
1. Go to secondlife://Aditi/secondlife/Lag%20Me%205/129/119/23
2. Set draw distance to 512m
3. Set debug setting RenderUseFarClip to FALSE 
4. Teleport to secondlife://Aditi/secondlife/TextureTest2/4/128/85
5. Open texture console
6. Observe number of Images (first value, second line -- should be around or above 5700)
![image](https://github.com/user-attachments/assets/446c8847-4e03-4bfb-a58d-5f49cba3e125)

7. Teleport back to secondlife://Aditi/secondlife/Lag%20Me%205/129/119/23
8. Look South and wait for TextureTest2 to unload
9. Observe number of Images in texture console

OBSERVE: Number of images does not go down
EXPECTED: Number of images should go down when Lagland unloads

Likely related  to https://github.com/secondlife/viewer/commit/27a2531c5bf375ed208d8fd5764a8797f08ce831

NOTE: previous behavior would sometimes unload textures about 30 seconds after the region unloads, but would usually hold onto textures indefinitely.

**Comment by AtlasLinden** [comment]
Reopening for testing
