### ISSUE TITLE
WebRTC: p2p voice calling option sometimes becomes disabled after calling another agent back too soon

### ISSUE THREAD

**Issue by maestrolinden** [secondlife/viewer#2325]
### Environment

backend version: utilx:584130

Atlasaurus 7.1.9.10326512121 (64bit)
Release Notes

You are at 128.8, 128.7, 23.0 in webRTC1 located at simhost-07c23d76c83837d55.aditi
SLURL: secondlife://Aditi/secondlife/webRTC1/129/129/23
(global coordinates 259,969.0, 245,377.0, 23.0)
WebRTC-Voice 2024-08-15.10397494850
Release Notes

CPU: Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz (3402.15 MHz)
Memory: 32704 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4780)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 2080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1911x1321
Font Size Adjustment: 96pt
UI Scaling: 0.75
Draw distance: 128m
Bandwidth: 10000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7234MB
Disk cache: Max size 1638.4 MB (63.3% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 20/3,969 (0.5%)
August 16 2024 16:49:21

### Description

If 2 agents just ended a p2p voice call in webRTC mode, then one agent attempts to call back too quickly (on the order of 1 second) after the call ended, the viewer can get into a state where the "Voice call" UI option to call the other agent (in either the right-click context menu or the top icon in "Conversations" is permanently disabled.  This condition persists even after the conversation is closed an reopened.

While although the UI to call the other avatar is disabled, the users are still able to voice chat spatially, and are still able to voice call other nearby avatars.

### Reproduction steps

1. Login with 2 webRTC-enabled viewers on 2 machines, with agents UserA and UserB.  The agents may be on the same region or different webRTC regions.
2. UserA: Initiate a p2p voice call to UserB via the people floater or the context menu option in the 'Conversations' floater
3. UserB: Click 'Answer' to accept the call
4. Both users: speak in voice chat, and verify the call is working
5. UserB: Click the 'Close voice connection' button to end the call
6. UserA: Within about 1-2 seconds, click the 'Open voice connection' button to call UserB again
7. If the connection succeeds, repeat steps (5) and (6), possibly swapping the roles of UserA and UserB each time (either user can trigger the bug)

Actual results:
- Sometimes, UserA, UserB, or both users will get into a state in which they are bounced back into spatial voice chat (which still works), but are unable to call the other agent - the 'Voice call' context menu option and 'Open voice connection' button become disabled.   
- When the viewer enters this state, closing and reopening the IM conversation does not restore the UI to its expected state of allowing calls.

![image](https://github.com/user-attachments/assets/ff44a86f-fbd8-40a3-9a67-1d449039fc77)

Expected results:
The users should never get into a state in which further p2p calls are permanently disabled in the UI.  While calling back "too soon" can cause the connection to fail, the users should always have the UI option to try again.
Both menu and button should allow calling or disconnecting.

**Comment by akleshchev** [comment]
I ended up couple times with a situation where one of the agents didn't disconnect automatically and where agents could call each other, but call wouldn't connect, but couldn't reproduce original issue.

**Comment by katerynamproductengine** [comment]
Passed QA.

This issue was verified on Aditi grid on webRTC1 region (WebRTC-Voice 2024-09-21.10968651181).
Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.
