### ISSUE TITLE
The "Paste" action is active when trying to paste any setting into a Library in My Environments

### ISSUE THREAD

**Issue by valeriiaaproductengine** [secondlife/viewer#2338]
### Environment

Second Life Test 7.1.9.10164740217 (64bit)
Release Notes

You are at 186.3, 55.9, 21.5 in Product Engine located at simhost-0b8a048fe6055a4b1.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/186/56/21
(global coordinates 336,826.0, 307,256.0, 21.5)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz (2611.2 MHz)
Memory: 16111 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4651)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.2879
OpenGL Version: 4.6.0 NVIDIA 528.79

Window size: 1897x889
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 4095MB
Disk cache: Max size 1638.4 MB (10.8% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Not Connected
Packets Lost: 268/108,098 (0.2%)
August 19 2024 04:13:11

### Description

See reproduction steps

### Reproduction steps

1. Login to the Second Life Test 7.1.9.10164740217 viewer.
2. Select World-> Environment -> My Environments.
3. Select any setting in the Library and click the Gear icon.
4. Select "Copy" from menu.
5. Staying in the library, select any folder, click the Gear icon and select "Paste" action.

**Actual result**: The "Paste" action is active when trying to paste any setting into a Library in My Environments.
**Expected result:** The "Paste" action should be inactive when trying to paste any setting into a Library in My Environments.

**Note:**
This issue is reproduced on Win10/OSX.
This issue was found according to Atlas Linden's comment in the https://lindenlab.atlassian.net/wiki/spaces/QA/pages/3053551633/EEP+Environment+Enhancement+Project+Test+Plan#8.-World-%3E-Environment test plan dated April 8, 2024.
This issue is reproduced on the production viewer (Second Life Release 7.1.8.9375512768).

Actual.png screenshot:
![image](https://github.com/user-attachments/assets/3294f37f-7e45-4cb3-b883-26561997d6ad)

**Comment by katerynamproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.
