### ISSUE TITLE
Return AvatarBakedTextureUploadTimeout

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#2342]
### Description

QA's [test plan](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2698575891/FUI+Avatar+Appearance+Regression+Test+plan?focusedCommentId=3247013897) requires use of AvatarBakedTextureUploadTimeout, but it was removed as unused by residents, restore it.

**Comment by dmytrohproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10582490681 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
