### ISSUE TITLE
Avatar/animesh rendering correctness pass

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#2349]
Tracy code investigation item.

Note: Performance impact of this change is likely not significant, however some changes will fix bugs.

## Test plan

- Keep an eye out for regressions in avatar loading reliability, and the quality of loading avatars.
- Prims with GLTF materials should render as expected

**Comment by katerynamproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.
