### ISSUE TITLE
Remove avatar rigging logging due to load time impact

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#2391]
### Description

LLScopedContextString debug code is present in avatar loading inner loop.

Tracy capture reveals a lot of time spent in `LLPolySkeletalDistortion::apply` during initial load in a region with many avatars. Further investigation shows that most of this time is spent in `LLScopedContextString`, a debug tool for Bento from 2016.

## Test plan

These changes reduce debug logging related to avatars. Please inform the viewer team if these debug logging removals negatively impact testing.

Overall, this fix is very low-risk and no regressions are expected.

**Comment by dmytrohproductengine** [comment]
Deferred QA.

Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.

Need more info.

Could you provide a test plan, please?

**Comment by cosmic-linden** [comment]
@dmytrohproductengine Moved test plan from PR to issue per viewer project conventions.

**Comment by dmytrohproductengine** [comment]
@cosmic-linden, thanks for the clarification.

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.
