### ISSUE TITLE
Favourite and Featured locations sending user to (0,0)

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2395]
### Environment

DeltaFPS Viewer: Second Life Test 7.1.10.10478834997

### Description

Logging directly into a favourite location sends the user to region coordinates (0,0).
This also occurs when attempting to log directly into Featured regions provided on the login screen: https://gyazo.com/027b1ab21a4867f84461993af3170a9a

This does not occur when logging into 'My last location' or 'My home'

### Reproduction steps

Log directly into a favourite or featured location directly from the login screen

**Comment by georgebproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10582490681 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
