### ISSUE TITLE
Drastic EEP changes causing NaNs

### ISSUE THREAD

**Issue by VixLinden** [secondlife/viewer#2397]
### Environment

Second Life Release 7.1.9.10495892574 (64bit)
Release Notes

You are at 117.0, 95.8, 21.9 in By Design located at simhost-06c9a56af17a2102e.agni
SLURL: http://maps.secondlife.com/secondlife/By%20Design/117/96/22
(global coordinates 261,493.0, 246,880.0, 21.9)
Second Life Preflight 2024-07-22.10048683488
Release Notes

CPU: 12th Gen Intel(R) Core(TM) i9-12900HK (2918.4 MHz)
Memory: 32440 MB
OS Version: Microsoft Windows 11 64-bit (Build 22631.4037)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5599
OpenGL Version: 4.6.0 NVIDIA 555.99

Window size: 1752x979
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3900kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 4095MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 15/47,660 (0.0%)
August 22 2024 11:26:06

### Description

Repro'ed by logging into [[Vixlandia](http://maps.secondlife.com/secondlife/Vixlandia/187/196/127)] and teleporting into [[By Design](https://maps.secondlife.com/secondlife/By%20Design/117/96/22)].

![Screenshot 2024-08-22 110545](https://github.com/user-attachments/assets/23859ef5-9cd2-424e-961e-e95c90930faa)

Textures and lighting render properly in [[Vixlandia](https://maps.secondlife.com/secondlife/Vixlandia/187/196/127)] , teleporting back into [[By Design](http://maps.secondlife.com/secondlife/By%20Design/117/96/22)] will recreate it.

### Reproduction steps
Repro 1:
1. Log into http://maps.secondlife.com/secondlife/Vixlandia/187/196/127
2. Teleport to https://maps.secondlife.com/secondlife/By%20Design/117/96/22

Repro 2:
1. Log in at http://maps.secondlife.com/secondlife/Danger!%20Danger!/80/51/39
2. Teleport to http://maps.secondlife.com/secondlife/By%20Design/216/48/22

Repro 3: (This one reproduces on Featurettes 7.1.8.9375512768 as well)
1. Go to http://maps.secondlife.com/secondlife/Bug%20Island/230/125/27 then walk North to the next parcel at http://maps.secondlife.com/secondlife/Bug%20Island/230/131/27  (The sky settings are in objects on those parcels and can be copied.)

Observed: Alpha objects turn white or other colors and the ground color changes between blue and gray. 
![image](https://github.com/user-attachments/assets/18e4f708-22ae-49b8-843b-c81ec42e9f15)

**Comment by AtlasLinden** [comment]
Clip of issue in action: https://gyazo.com/6465e019d0da185db6311929e4158c12
However, things become red in this instance.

**Comment by RunitaiLinden** [comment]
Possibly related to fix for #1466

**Comment by RunitaiLinden** [comment]
Fixed.

Haze contribution was going off the rails with a high enough value that it was causing something like floating point overflow.  Fix was to clamp haze contribution to 10.  Be sure to A/B test against "extreme" sky settings as this clamp may change the appearance of some skies and we might need another pass at it to get it right.

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.9.10515727195 (64bit) on Win11/OSX in the scope of [IQA #315](https://github.com/secondlife/iqa/issues/315).
