### ISSUE TITLE
Outfit Gallery images blurry

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2401]
### Environment

DeltaFPS Viewer: Second Life Test 7.1.10.10478834997

### Description

Custom images in the Outfit Gallery aren't fully loading.
This does not reproduce on the Atlasaurus viewer (7.1.9.10495892574)
![outfit_preview_blurry](https://github.com/user-attachments/assets/31f7187f-f34e-479e-9bdc-f04647242544)

### Reproduction steps

Observe custom images in the Outfit Gallery

**Comment by AtlasLinden** [comment]
No longer able to reproduce on latest DeltaFPS build: 7.1.10.10708851543
Sending to testing

**Comment by vladyslavasproductengine** [comment]
Pass QA.
Verified on Second Life Release 7.1.10.10800445603 (64bit) Win10/OSX.
