### ISSUE TITLE
The Minimap defaulted to North at Top for new users.

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#2404]
### Environment

Second Life Release 7.1.8.9375512768 (64bit)
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.91 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4780)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1672x1313
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (24.2% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Not Connected
August 22 2024 15:52:06

### Description

The minimap rotation defaults to North at top for new users. 
The minimap rotation defaults to Camera at top for all other cases. 

### Reproduction steps

1. Delete the C:\Users\[USERNAME]\AppData\Roaming\SecondLife folder
2. Create a new user.
3. Log in the new user, open the minimap, and right-click the minimap to check the rotation style
4. Observe that "North at top" is checked
5. Log out
6. Delete the C:\Users\[USERNAME]\AppData\Roaming\SecondLife folder
7. Log in the user, open the minimap, and right-click the minimap to check the rotation style
8. Observe that "Camera at top" is checked.

Expected: The minimap rotation should default to "Camera at top" in both cases, which everyone can agree is correct and wholesome.

**Comment by AtlasLinden** [comment]
This is expected behaviour according to https://github.com/secondlife/jira-archive-internal/issues/67632 in order to have consistency with the world map

**Comment by Steeltoe-Linden** [comment]
The Mini-Map and Map should resemble one another to help users see the correspondences in the information shown between them -- therefore "north at top."  Not wanting to infuriate existing users, which distorts any number of design decisions, we left it alone for existing users.  There may be disagreement on what is correct, but it was litigated in 2022 and I don't see a reason to revisit it. Let's always keep in mind that what we're used to is not always the right thing.

**Comment by Dan-Linden** [comment]
Okey dokey. Closing this as expected behavior.
