### ISSUE TITLE
[b-develop test build] ERROR: dataFormatBits : LLImageGL::Unknown format: 34027

### ISSUE THREAD

**Issue by AiraYumi** [secondlife/viewer#2407]
### Description

https://github.com/secondlife/viewer/actions/runs/10494918620

I tried to download it from github's Artifact and run it, but an error occurred.

You can see the full log at the link below.
https://bpa.st/IZHA

**Comment by Nicky-D** [comment]
This seems to be an unhandled case of GL_COMPRESSED_LUMINANCE_ALPHA in S32 LLImageGL::dataFormatBits(S32 dataformat).
Probably introduced by https://github.com/secondlife/viewer/pull/2389 though this PR more or less just uncovered this, as dataFormatBits is older.
I have not spend time to research if that function lacks more formats inside the switch

**Comment by AiraYumi** [comment]
Thank you Nicky-D.

This issue did not occur in the viewer built by merging the latest develop into b-develop, so I think the problem is resolved, but there may still be other issues.
