### ISSUE TITLE
The long covenant with emojis significantly slows down some operations in the viewer

### ISSUE THREAD

**Issue by DmitrySProductengine** [secondlife/viewer#2408]
### Environment
<details><summary>Environment</summary>
<p>

Second Life Test 7.1.9.10164740217 (64bit)
Release Notes

You are at 105.8, 109.8, 22.2 in Product Engine 3 located at simhost-0cd70bedfc4667751.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%203/106/110/22
(global coordinates 336746.0, 307054.0, 22.2)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2600 MHz)
Memory: 16384 MB
OS Version: macOS 14.5.0 Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-5.5.17

Window size: 1058x836
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (19.0% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/834 (0.0%)
August 23 2024 07:43:07

</p>
</details> 

### Reproduction steps

1. Log in to the Viewer as an estate owner or estate manager.
2. Create any notecard with long text and emoji (the example file is attached below - its contents can be copied to the notecard).
3. Drag the notecard into the Covenant field in the Region/Estate floater.
4. Observe the viewer's behavior during various operations (opening tabs in region/estate or about land floaters; general periodic freezing of the viewer).

**Actual result:**
The long covenant with emojis significantly slows down some operations in the viewer.

**Expected result:**
The long covenant with emojis should not slow down operations in the viewer..

**Additional information:**
This issue was found during Ad hoc testing in the scope of [IQA #295](https://github.com/secondlife/iqa/issues/295).
This issue is reproduced on Win10, Win11, and OSX.

This issue is reproduced on the current release 7.1.8.9375512768 build.

Hang time depends on the length of the covenant.

Similar behavior was before with regular text - ticket https://github.com/secondlife/jira-archive-internal/issues/80456

See the attached sample and screenshot:

1. : [sample of notecard with emoji.txt](https://github.com/user-attachments/files/16730304/sample.of.notecard.with.emoji.txt)

2. Actual - current release 7.1.8.9375512768:
<img width="1920" alt="Actual - current release 7 1 8 9375512768" src="https://github.com/user-attachments/assets/96f50412-dd04-4e83-91a7-5491f6a7e223">

**Comment by LLGuru** [comment]
Using ASCII text with the same number of lines (~6000) takes 60% time of the time taken by the original text with emojis
[sample.of.notecard.without.emoji.txt](https://github.com/user-attachments/files/17021110/sample.of.notecard.without.emoji.txt)

**Comment by igorlproductengine** [comment]
Failed QA.
Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.

Testing has shown that the viewer still freezes when opening the Region floater and the About Land floater. Initially, the freeze lasts from 2 to 5 seconds on my devices, while some of my colleagues experience freezes of 10 to 20 seconds. Over time, the duration of the freeze decreases, and the viewer's performance becomes smoother, but the issue does not disappear completely.

**Comment by georgebproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11296522354 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/366.
