### ISSUE TITLE
Alert about expiring voice morphs needs to be removed from the viewer.

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#2413]
### Environment

Second Life Release 7.1.9.10515727195

### Description

Alert about expiring voice morphs needs to be removed from the viewer.

### Reproduction steps

1. Log in with a user that has voice morphs which are about to expire.

Observe: A dialog pops up about the expiring Voice Morphs.
![image (4)](https://github.com/user-attachments/assets/ea803a55-631a-4804-b8b9-4cfd86e84569)

The first link is https://secondlife.com/destination/voice-island
The second link is https://secondlife.com/destination/voice-morphing-premium

Here's a log from a different viewer, but this does reproduce in Atlasaurus+WebRTC 7.1.9.10515727195
[SecondLife_VoiceMorphRenew.old.log](https://github.com/user-attachments/files/16732758/SecondLife_VoiceMorphRenew.old.log)

Expected: The voice morphs will be going away, so this alert should be removed.

**Comment by akleshchev** [comment]
Just expiring ones? Not expired ones?

**Comment by igorlproductengine** [comment]
Need more info.
Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.
The PE team is currently unable to test this issue, as we do not have access to an avatar with a Voice Morph subscription that is about to expire. Could you please:
1. Provide an account with an expiring Voice Morph for testing purposes?
2. Suggest an alternative way to trigger or simulate the expiring Voice Morph dialog event ?

**Comment by Dan-Linden** [comment]
I've reopened this.

I tested with my Testerd1 Tester account on Agni and saw
![VoiceEffectsWillExpire](https://github.com/user-attachments/assets/db8c1708-210b-46d6-b247-36b0b49a1922)

Message in SecondLife.log:
2024-09-23T20:38:19Z WARNING # newview/lltoastalertpanel.cpp(197) LLToastAlertPanel::LLToastAlertPanel : Alert: Your version of Second Life does not know how to display the notification it just received.  Please verify that you have the latest Viewer installed.\n\nError details: The notification called 'VoiceEffectsWillExpire' was not found in notifications.xml.

Second Life Release 7.1.11.10947335521 (64bit)
You are at 67.7, 34.8, 38.5 in Danger! Danger! located at simhost-0dd7e33bcf6d85949.agni
SLURL: http://maps.secondlife.com/secondlife/Danger%21%20Danger%21/68/35/39
(global coordinates 261,188.0, 249,635.0, 38.5)
Second Life Server 2024-07-22.10048683488

**Comment by akleshchev** [comment]
> I tested with my Testerd1 Tester account on Agni and saw

Looks like this notification can arrive from server.

**Comment by akleshchev** [comment]
During meeting it was decided that this should be reverted utill server updates.

**Comment by AtlasLinden** [comment]
In a new Develop branch build, this notification appears on every startup.
It also takes clicking OK 4 times to remove it (so it's possible it appears 4 times?)

Another request from the aforementioned meeting is to add a checkbox to remove this notification for next time.

**Comment by akleshchev** [comment]
https://github.com/secondlife/server/issues/1472

**Comment by igorlproductengine** [comment]
Need more info.
Verified on the Second Life Release 7.1.11.11074622243 (64bit) on Win10/OSX in the scope of secondlife/iqa#356.
The PE team is currently unable to test this issue, as we do not have access to an avatar with a Voice Morph subscription that is about to expire. Could you please:

1. Provide an account with an expiring Voice Morph for testing purposes?
2. Suggest an alternative way to trigger or simulate the expiring Voice Morph dialog event?

**Comment by AtlasLinden** [comment]
Verified this notification does not appear on ExtraFPS 7.1.11.11074622243 using the same account that triggered it on a Develop build.
Further testing of the notification to be performed after implementation of https://github.com/secondlife/server/issues/1472.
