### ISSUE TITLE
Do not calculate and store silhouette edges for nearly every geometric prim with a corner

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#2421]
`LLVolumeFace::mEdge` is calculated for many prims at region load time (depending on the flags), then stored long-term until the prim is unloaded. This is not necessary because the values of `mEdge` are only used for calculating silhouette edges, which are part of the selection outlines. Selection outlines can be calculated on-demand, so the silhouette edges should as well.

This should decrease time spent in `LLVolumeFace::createSide`, and reduce the memory overhead of cubes and some other prims.

## Test plan

Selection outlines should look the same as before this change.

**Comment by igorlproductengine** [comment]
Need more info.
Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.

Could you please provide a test plan?

**Comment by igorlproductengine** [comment]
Passed QA.

Verified on Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.

Hello, @cosmic-linden. I believe these changes should be reflected in the statistics bar for better visibility and tracking.
