### ISSUE TITLE
Reduce overhead of drawing nametags

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#2432]
### Description

In crowded scenes, drawing nametags hurts performance and creates visual clutter.  Reduce the number of nametags that can be drawn per frame.

**Comment by kylelinden** [comment]
We cannot default name tags to off, they are a necessary part of social interactions. Are there other methods we can use to reduce the UI draws? i.e. remove when an Av is impostored, reduce size, only show display name etc.

**Comment by RunitaiLinden** [comment]
Closing as not planned since it's been backed out.
