### ISSUE TITLE
Force an Error callstacks should show an accurate source location in bugsplat

### ISSUE THREAD

**Issue by brad-linden** [secondlife/viewer#2445]
### Environment

Second Life Test 7.1.10.242411739 (64bit)
Release Notes
Build Configuration RelWithDebInfo

CPU: 12th Gen Intel(R) Core(TM) i9-12900HK (2918.4 MHz)
Memory: 32440 MB
OS Version: Microsoft Windows 11 64-bit (Build 22631.4037)
Graphics Card Vendor: Intel
Graphics Card: Intel(R) Iris(R) Xe Graphics

Windows Graphics Driver Version: 31.0.101.5186
OpenGL Version: 4.6.0 - Build 31.0.101.5186

### Description

currently any deliberate crashes from LL_ERRS are all showing up as a lambda object in gltfscenemanager.cpp.  the accurate source location of the error should be shown instead.

### Reproduction steps

1. Log in
2. From Develop menu, select Force An Error -> Force LLError and Crash
3. Find the crash report in bugsplat

Expected Behavior
the crash report should show LLAppViewer::forceErrorLLError() as the source location for the crash

**Comment by georgebproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10622905308 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
