### ISSUE TITLE
Scrolling by the mouse wheel does not scroll up on the unopened "Destination" field on the regular login screen in the viewer

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#2454]
### Environment

Second Life Release 7.1.10.10582490681 (64bit)
Release Notes

You are at 213.5, 107.0, 21.5 in Product Engine located at simhost-0286f40426ea828a8.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/213/107/22
(global coordinates 336,853.0, 307,307.0, 21.5)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (2394.58 MHz)
Memory: 8078 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4780)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: GeForce GT 635M/PCIe/SSE2

Windows Graphics Driver Version: 23.21.13.8873
OpenGL Version: 4.6.0 NVIDIA 388.73

Window size: 1366x705
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 96m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 2112MB
Disk cache: Max size 1638.4 MB (0.1% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/756 (0.0%)
August 29 2024 05:26:19

### Description

See Reproduction steps.

### Reproduction steps

1. Download and install the [Second Life Release 7.1.10.10582490681](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%238406d10-DeltaFPS) build.
2. Log in and log out for the regular login screen available.
3. Restart the viewer.
4. Hover the mouse on the "Destinations" field.
5. Scroll down the mouse wheel.
6. Scroll up the mouse wheel.

**Actual result:**
Scrolling by the mouse wheel does not scroll up on the unopened "Destination" field on the regular login screen in the viewer.

**Expected result:**
Scrolling by the mouse wheel should scroll up as expected on the unopened "Destination" field on the regular login screen in the viewer.

**Note:**
This issue is reproduced on Win10/OSX.

This issue was found during ad-hoc testing of [secondlife/viewer/issues/2082](https://github.com/secondlife/viewer/issues/2082).

**Also**, the scroll mouse is able to scroll up from time to time.
After scrolling the mouse wheel down, the favorite destinations aren't chosen ('My Home' is the last position for scrolling).

This issue is **not** reproduced for the 'Username' field.
This feature has not yet been implemented in the current production build for Second Life Release 7.1.9.10515727195.

**actual.mp4**
https://github.com/user-attachments/assets/3705f80a-880c-4faa-900f-d5b362342e36

**Comment by vladyslavasproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.
