### ISSUE TITLE
Optimize unloading of prims

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#2462]
Optimize `LLMeshRepository::unregisterMesh`.

`LLViewerObjectList::cleanDeadObjects` takes a long time to run, especially during shutdown, but also when moving around the world, leading to intermittent slow frames. `LLMeshRepository::unregisterMesh` was found to be a bottleneck for this function.

## Test plan

Due to the nature of the performance fix, regressions are not expected. There is a small chance of increased crashes with `LLMeshRepository` in the stack trace, most noticably on shutdown.

**Comment by Dan-Linden** [comment]
Passed QA.
Verified on Second Life Release 26.2.0.21655710006 on Win11/OSX in the scope of https://github.com/secondlife/iqa/issues/606
