### ISSUE TITLE
Add Neutral tonemapper

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#2464]
### Description

Add Khronos' Neutral tonemapper and make it the new default.
Add a debug setting to control which tonemapper to use.
Add a debug setting to control intensity of tonemapper.

**Comment by AtlasLinden** [comment]
New tonemapper is observed on both Win and Mac in ExtraFPS viewers.
Passing QA.
See https://github.com/secondlife/viewer/issues/2650 for UI to control the related debug settings.
