### ISSUE TITLE
Sim surrounds do not fully load

### ISSUE THREAD

**Issue by kylelinden** [secondlife/viewer#2467]
### Environment

Second Life Release 7.1.10.10582490681 (64bit)
Release Notes

You are at 37.3, 131.9, 66.8 in Teskylation located at simhost-04619bbe021810930.agni
SLURL: http://maps.secondlife.com/secondlife/Teskylation/37/132/67
(global coordinates 331813.0, 305796.0, 66.8)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (2800 MHz)
Memory: 16384 MB
OS Version: macOS 11.7.10 Darwin 20.6.0 Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64 x86_64
Graphics Card Vendor: Intel Inc.
Graphics Card: Intel Iris Pro OpenGL Engine

OpenGL Version: 4.1 INTEL-16.5.14

Window size: 1105x801
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 1536MB
Disk cache: Max size 819.2 MB (100.0% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091638
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 65/8752 (0.7%)
August 29 2024 16:13:03

### Description

Logged into my region with a sim surround and noticed it was only partially loading.

### Reproduction steps

Logged into my region with a sim surround on Mac with a DeltaFPS build.
Noticed it was only partially loading. Attaching screenshot.
Flew around trying to change draw distance and nothing helped.

Workaround
Relogging helps but then if I teleport away and logout, then come back i might be broken again.
Inconsistent behavior, but new in
<img width="1063" alt="Screen Shot 2024-08-29 at 9 53 21 AM" src="https://github.com/user-attachments/assets/b894b804-80dc-49ec-ac24-8094c6ea0310">
 DeltaFPS

**Comment by cosmic-linden** [comment]
Per @RunitaiLinden 's suggestion, we are going to both look into this and will exchange info if any leads

**Comment by RunitaiLinden** [comment]
Fixed in DeltaFPS

Bug was introduced by texture streaming changes.  Fix was to refactor how "sculpt" gets called on LLVOVolume to work well with in the absence of mCachedRawImage.

**Comment by igorlproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10800445603 (64bit) on the Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/332.
