### ISSUE TITLE
The Destinations ComboBox on Login Screen changes the selected item to the similar one

### ISSUE THREAD

**Issue by LLGuru** [secondlife/viewer#2471]
### Environment

Any recent build

### Description

When the Destination ComboBox contains 2 similar items in the list,
after choosing the second item of this pair and reopening the dropdown list
the selection is on the first item of the pair (a few rows upper the user choise)

### Reproduction steps

**Prerequisites:** get 2 identical landmarks in the Favorites list

1. Login to viewer
Expected behavior: you see a few landmarks on the Favorites toolbar

2. On the Favorites toolbar click "More" button
Expected behavior: the small floater with the list of landmarks is opened

3. At the bottom of the opened floater click "Open landmarks" (scroll the list down if needed)
Expected behavior: The PLACES floater is opened with LANDMARKS tab selected

4. On the PLACES floater select the first tab FAVORITES
Expected behavior: the same list of landmarks as you have on the Favorites toolbar should be displayed in the floater

5. Drag and drop any landmark from the Favorites toolbar to the list on the PLACES floater
Expected behavior: you get 2 copies of the same landmark in the landmark list on the FAVORITES tab

6. Drag and drop the new landmark in the PLACES floater a few rows below its copy
Expected behavior: you get 2 copies of the same landmark in the landmark list on the FAVORITES tab

**Steps to reproduce:**
1. Close the viewer
2. Start the viewer again (do not login, stay on the login screen) 
3. Open the dropdown list of the Destinations ComboBox
4. Select the second item of the pair of identical landmarks
5. Close and open the dropdown list again

Expected behavior: the second item is still selected
Actual behavior: the first item of the pair is selected

**Comment by vladyslavasproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.
