### ISSUE TITLE
Reduce 'World map' floater drawing time

### ISSUE THREAD

**Issue by maxim-productengine** [secondlife/viewer#2473]
'World map' floater drawing time is ~1.5ms, which probably can be improved.
(Some time ago World map floater was closed after teleport, but now it remains open. So, it may linger and degrade fps)

Test Plan
Confirm that World map is displayed without issues.

**Comment by maxim-productengine** [comment]
Reopening because github bot changed the status too early(after merging pull request).

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.
