### ISSUE TITLE
Second Life reports incorrect amount of available video memory on some discrete GPUs on Windows

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#2482]
### Description

Testing on NVIDIA GT 1030 2GB, the viewer reports 4GB of vram are available and exhausts available video memory, leading to poor performance.

Test Plan:
1. Open task manager, click performance, click GPU, and note "Dedicated GPU Memory"
2. In Second Life, click Help->About Second Life and note "Texture Memory"
EXPECTED: Texture Memory should agree with "Dedicated GPU Memory" on discrete GPUs
3. Open Texture Console (Ctrl+Shift+3) and note "Est. Free"
EXPECTED: Est. Free should agree with task manager

**Comment by RunitaiLinden** [comment]
Fixed in DeltaFPS and did a low-end NVIDIA performance pass:

- Use GL_NVX_gpu_memory_info when available
- Disable transparent water on Mid+ and lower
- Adjust GPU benchmark to better tell the truth
- Texture bias tune up

**Comment by RunitaiLinden** [comment]
GT 1050 looks like a pass, but the OS is giving some other app extra VRAM.  Est. Free is calculated by subtracting Total from Texture Memory, then taking off an additonal 512MB plus some percent of Total, which usually gets in the ballpark of what Task Manager reports, but sometimes some other app is eating texture memory.  When this is the case, the OS should free vram and give it to the app that has focus when vram is exhausted, so we pretend we have access to most of the available vram even if other apps are taking vram, otherwise we end up never using available vram and always ceding to backgrounded tasks.

The Quadro is definitely a fail... looking into that.

**Comment by RunitaiLinden** [comment]
Potentially fixed in DeltaFPS

Don't have a quadro to test with, but from the logs it looks like we were getting the right VRAM number from OpenGL, then overriding it with the wrong number from DirectX.  Fix was to only ask DirectX if OpenGL was unable to provide a sensible VRAM number.

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10800445603 (64bit) on Win10/Win11 in the scope of [IQA #332](https://github.com/secondlife/iqa/issues/332).

During the test, video cards with different memory sizes were tested.
The parameter 'Est. Free' almost corresponds to the value of free dedicated video memory.

Video cards:
1. ATI Radeon HD 2600 XT - 512MB video memory  
Texture memory: 512MB;     Memory Used (Dedicated): 308 MB;     Est. Free: 218MB
(in this case, the Windows task manager did not show the load of this video card and I had to use the GPU-Z utility)
![7 1 10 10800445603 - amd HD 2600 XT](https://github.com/user-attachments/assets/5b3adc9c-ff34-4a51-9a10-d0a761916ce1)

2. NVIDIA GeForce GT 730 - 2GB video memory
Texture memory: 2048 MB;     Dedicated GPU memory: 0.8/2.0 GB;     Est. Free: 972 MB
![7 1 10 10800445603 - nvidia 730](https://github.com/user-attachments/assets/9d734a5c-95c4-447c-a358-75b1099c9b96)

3. NVIDIA Quadro 2000M - 2GB video memory
Texture memory: 2048 MB;     Dedicated GPU memory: 0.7/2.0 GB;     Est. Free: 947 MB
![7 1 10 10800445603 - nvidia quadro 2000M](https://github.com/user-attachments/assets/ad8006f2-3ec8-46f3-8908-b32d1c85ce68)

4. NVIDIA GeForce GTX 1050 Ti - 4GB video memory
Texture memory: 4096 MB;     Dedicated GPU memory: 0.8/4.0 GB;     Est. Free: 3005 MB
![7 1 10 10800445603 - nvidia 1050ti](https://github.com/user-attachments/assets/67875c1c-e6d9-4638-9d13-2c350213fb74)

5. NVIDIA GeForce 3070 mobile - 8GB video memory
Texture memory: 8192 MB;     Dedicated GPU memory: 0.8/8.0 GB;     Est. Free: 6766 MB
<img width="1280" alt="7 1 10 10800445603 - nvidia 3070 mobile" src="https://github.com/user-attachments/assets/4499df4d-ad61-4c95-95c4-751a96f987a4">

6. NVIDIA GeForce GTX 1080Ti - 11GB video memory
Texture memory: 11264 MB;     Dedicated GPU memory: 0.9/11.0 GB;     Est. Free: 10128 MB
![7 1 10 10800445603 - nvidia 1080ti](https://github.com/user-attachments/assets/1c2c02f0-36b6-439f-a4f0-60b441404f56)

7. NVIDIA GeForce RTX 3090 - 24GB video memory
Texture memory: 24576 MB;     Dedicated GPU memory: 0.9/24.0 GB;     Est. Free: 23505 MB
![7 1 10 10800445603 - nvidia 3090](https://github.com/user-attachments/assets/9c9f17f9-55c2-4405-848a-d70ce63cf13a)
