### ISSUE TITLE
Possible error in llmd5 finalize function leaving sensitive information not zeroized?

### ISSUE THREAD

**Issue by Hecklezz** [secondlife/viewer#2500]
### Description

Unless I'm mistaken, is [line 219 in llmd5.cpp](https://github.com/secondlife/viewer/blob/c2724537adab9d31c23d33e36002772a9c56f4c3/indra/llcommon/llmd5.cpp#L219) not supposed to be:
`memset (buffer, 0, sizeof(buffer));`
or more preferably in modern c++:
`buffer = {};`

Or is it intentional that only the first byte of the buffer is getting zeroized?

**Comment by marchcat** [comment]
For QA: there were code quality improvements made in #2507, which shouldn't affect any visible behavior.

**Comment by Dan-Linden** [comment]
Nothing to test. Moving this to Pending Release.

**Comment by vladyslavasproductengine** [comment]
Passed QA according to the Dan-Linden comment.
The issue was investigated in the scope of https://github.com/secondlife/iqa/issues/356.
The ticket is in Pending Release status and has not been changed.
