### ISSUE TITLE
Avatar Media/Voice Hearing Toggles

### ISSUE THREAD

**Issue by marchcat** [secondlife/viewer#2519]
### Feature Overview:
The PR #2518 introduces two new toggles to the avatar dropdown in the Second Life Viewer:
- **Hear Media/Sound** from an avatar.
- **Hear Voice** from an avatar.
These toggles allow users to control the "MediaSoundsEarLocation" and "VoiceEarLocation" preferences without navigating through settings.

![secondlife-bin_2024-09-06_14-34-18](https://github.com/user-attachments/assets/2cf9359c-d519-4b1f-93df-390d0104eb56)

### Key Testing Areas:
1. **Toggle Functionality**: 
   - Ensure both toggles work independently and correctly reflect the status of media/sound and voice output from avatars.
   - Verify that toggling these options updates the corresponding settings in real-time (without needing a restart).
   
2. **Default Settings Behavior**:
   - Confirm the default state of these toggles after a clean installation or profile reset.
   - Ensure that the toggles match existing preferences if already set by the user.

3. **UI Behavior**:
   - Check the correct placement and visibility of the toggles in the avatar dropdown.
   - Verify tooltips, label clarity, and any other user interface elements.

4. **Edge Cases**:
   - Test behavior when switching avatars rapidly.
   - Verify correct functionality in different regions and scenarios where avatars may not emit sound/media.
   - Confirm toggle behavior when media permissions are denied or unavailable.

**Comment by marchcat** [comment]
Reopen for testing.

**Comment by georgebproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.

**Comment by AtlasLinden** [comment]
Product has agreed to have this feature moved to the Communicate menu instead of the Avatar menu

**Comment by valeriiaaproductengine** [comment]
Failed QA.

This feature has not been moved to the Communicate menu. It remains in the Avatar menu.

Verified on the Second Life Release 7.1.11.11074622243 (64bit) on Win11/OSX in the scope of https://github.com/secondlife/iqa/issues/356.

**Comment by marchcat** [comment]
Right, it's currently in `develop`. Added #2748 for cherry pick.

**Comment by kylelinden** [comment]
@marchcat please revert all these changes and pull this out of ExtraFPS.

**Comment by marchcat** [comment]
Sure, will do.

**Comment by marchcat** [comment]
#2842 #2843

**Comment by marchcat** [comment]
Reverted in both develop and ExtraFPS.

**Comment by Dan-Linden** [comment]
QA, please verify this has been removed from ExtraFPS

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11296522354 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/366.

Note:
Avatar Media/Voice Hearing toggles have been removed from UI and do not appear in the viewer.
