### ISSUE TITLE
Voice: After calling and hanging up on a group, the call button remains grey.

### ISSUE THREAD

**Issue by roxanneskelly** [secondlife/viewer#2532]
### Environment

Second Life Release 7.1.9.10515727195 (64bit)
Release Notes

You are at 128.0, 128.0, 23.0 in webRTC1 located at simhost-07c23d76c83837d55.aditi
SLURL: secondlife://Aditi/secondlife/webRTC1/128/128/23
(global coordinates 259,968.0, 245,376.0, 23.0)
WebRTC-Voice 2024-08-30.10639499260
Release Notes

CPU: Intel(R) Core(TM) Ultra 9 185H (3072 MHz)
Memory: 32213 MB
OS Version: Microsoft Windows 11 64-bit (Build 22631.4037)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5612
OpenGL Version: 4.6.0 NVIDIA 556.12

Window size: 1694x989
Font Size Adjustment: 96pt
UI Scaling: 1.05
Draw distance: 128m
Bandwidth: 10000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7192MB
Disk cache: Max size 3993.6 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/211 (0.0%)
September 09 2024 10:58:53

### Description

After calling and hanging up on a group, without closing chat, the call button remains disabled.

### Reproduction steps

1. User logs in.
2. Bring up a group via 'people' and start a chat.
3. Click the call button.
4. hang up the call.
5. Observe the call button.

Expected: The call button re-enables after the call is hung up.
Actual: The call button remains disabled.

Workaround: close the chat session and re-open it.

**Comment by katerynamproductengine** [comment]
Passed QA.

This issue is not reproduced on Agni and Aditi grids on Vivox/WebRTC regions.
(Simulator WebRTC:
WebRTC-Voice 2024-09-23.10999422747
Simulator Vivox:
Second Life Server 2024-07-22.10048683488).

Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.
