### ISSUE TITLE
Sculpties deforming upon TP

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2540]
### Environment

DeltaFPS: Second Life Release 7.1.10.10708851543 

### Description

Sculpties are occasionally deformed after teleporting.
In this repro, the chairs (sculpties) become deformed upon teleporting to a specific region and heading back:
https://gyazo.com/7de06dcd653e0196f382f273ec679193

The sculpties LOD reverts to proper form upon relog.

Does not reproduce on the default viewer Atlasaurus 7.1.9.10515727195

### Reproduction steps

1. Observe chairs at http://maps.secondlife.com/secondlife/By%20Design/119/93/22
2. TP to http://maps.secondlife.com/secondlife/Dumont/208/43/21
3. TP back

**Comment by vladyslavasproductengine** [comment]
Pass QA.
Verified on Second Life Release 7.1.10.10800445603 (64bit) Win10/OSX.
