### ISSUE TITLE
Peer voice gain control/mute not working

### ISSUE THREAD

**Issue by roxanneskelly** [secondlife/viewer#2601]
### Environment

Second Life Release 7.1.9.10515727195 (64bit)
Release Notes

You are at 128.0, 128.0, 18.8 in RoxieDev located at roxie-mkii.staging
SLURL: secondlife://Aditi/secondlife/RoxieDev/128/128/19
(global coordinates 33,408.0, 5,248.0, 18.8)
roxie-dev dev
Release Notes

CPU: Intel(R) Core(TM) Ultra 9 185H (3071.99 MHz)
Memory: 32213 MB
OS Version: Microsoft Windows 11 64-bit (Build 22631.4169)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5612
OpenGL Version: 4.6.0 NVIDIA 556.12

Window size: 1739x989
Font Size Adjustment: 96pt
UI Scaling: 1.05
Draw distance: 128m
Bandwidth: 10000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 7192MB
Disk cache: Max size 3993.6 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/302 (0.0%)
September 18 2024 12:54:32

### Description

The slider for changing the voice level of a peer does nothing.  Neither does mute.

Expected, mute mutes the peer, and the volume slider changes the volume of the peer.

### Reproduction steps

1. Log in avatar A and B to a region.  Make them stand nearby.
2. Avatar A...hover mouse over avatar B until the popup appears, click on the (i), then change the volume slider while avatar B is transmitting voice.
3. Observe audio level.

Expected, the volume of the peer changes.
Observed, nothing happens.

For mute...
1. Log in avatar A and B to a region.  Make them stand nearby.
2. Avatar A...hover mouse over avatar B until the popup appears, click on the (i), then change the mute state while avatar B is transmitting voice.
3. Observe the audio.
Expected - peer is muted/unmuted appropriately.
Observed - peer is not muted/unmuted.

**Comment by vladyslavasproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of secondlife/iqa#348.

The slider for changing the voice level of a peer the sound more louder on the Vivox region than Webrtc.Is this expected behavior?
Webrtc:
WebRTC-Voice 2024-09-23.10999422747
Vivox:
Second Life Server 2024-07-22.10048683488
