### ISSUE TITLE
ExtraFPS test cases for several PRs 

### ISSUE THREAD

**Issue by brad-linden** [secondlife/viewer#2624]
### Description

**Test Plan:**
negative test case for the following modified UI from #2593 #2596:

- Font display
- Floater Image Preview
- Floater BVH Preview
- Floater Model Preview
- Hud Icon
- Hud Efect Blob
- Manip & Scale handles
- Avatar Imposters
- World Map
- Mini Map
- Snapshot Live Preview
- LLMediaCtrl
- LLJoystickButton
- LLBadge
- LLStatsBar

negative test case for particle texture loading from #2598 

verify mac performance for #2587

local baked texture while editing appearance should have improved resolution #2580 

fixed macos Locale settings - warning about MissingString(macOSLocale) should not be present in logs. #2563 

see webrtc race condition test plan in #2514 

new SMAA rendering option in #2466

**Comment by AtlasLinden** [comment]
@dmytrohproductengine thanks for asking for the clarification. This is a quick verification of a series of pull requests that are not associated with any issue/ bug report. Please see updated test plans below.

1. [#2593](https://github.com/secondlife/viewer/pull/2593) [#2596](https://github.com/secondlife/viewer/pull/2596): Verify UI appears correct around the following areas:
- Font display
- Floater Image Preview
- Floater BVH Preview
- Floater Model Preview
- Hud Icon
- Hud Efect Blob
- Minimap & Scale handles
- Avatar Imposters
- World Map
- Snapshot Live Preview
- LLMediaCtrl
- LLJoystickButton
- LLBadge
- LLStatsBar

2. https://github.com/secondlife/viewer/pull/2598 
Verify no irregularities spotted in particle texture loading

3. https://github.com/secondlife/viewer/pull/2587 
Verify performance on mac is stable

4. https://github.com/secondlife/viewer/pull/2580 
Verify local baked textures while editing appearance have improved resolution. Specifically focusing on 2k textures compared to 512.

5. https://github.com/secondlife/viewer/pull/2563 
Verify that this warning containing "MissingString(macOSLocale)" no longer appears in viewer log.

6. https://github.com/secondlife/viewer/pull/2514 
Perform the following:
* Close all active chat sessions.
* Select 'Voice Call' in the context menu of a nearby avatar.
* Validate popup appears for that nearby avatar requesting to start/ignore/go to im.
* Select 'start'
* Validate the call completes.

7. https://github.com/secondlife/viewer/pull/2466 
This will be tested in https://github.com/secondlife/viewer/issues/2673

**Comment by dmytrohproductengine** [comment]
Win10 - Passed QA.
OSX - Failed QA.

Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.

**OSX:**
Failed by step 7 from @AtlasLinden comment [secondlife/viewer/issues/2673](https://github.com/secondlife/viewer/issues/2673).
The antialiasing option "FXAA + Low" is shown after choosing the "Mid+" or "High"  graphics preset.
The antialiasing option "SMAA + Low" is shown after choosing the "High+" or "Ultra" graphics preset.
