### ISSUE TITLE
slow rate of LSL control event makes fast vehicles difficult to drive

### ISSUE THREAD

**Issue by AndrewMeadows** [secondlife/viewer#2625]
### Environment

TODO: find viewer version with the bug

### Description

There was a bug: https://github.com/secondlife/jira-archive-internal/issues/71178

A fix for it eventually reached FireStorm: https://github.com/FirestormViewer/phoenix-firestorm/commit/a67dde1f16c144247cff0b765201e64f8f8e75c2

That fix introduced a new bug where some twitchy vehicles would become difficult to drive because the rate of LSL control events in scripts had been reduced and vehicle steering was lagged.

Leviathan encountered a conflict with the fix in the GameControl project, rewrote that bit of code and made it even worse for vehicles.  After some feedback from Residents it was finally fixed in GameControl.

FireStorm expressed some interest in getting the fix so it was ported to develop in PR #2569

### Reproduction steps

One way to see the bug in action is to put this script on a box and wear it:
```
integer count;

default
{
    control(key id, integer levels, integer edges)
    {
        integer start = levels & edges;
        integer end = ~levels & edges;
        if (start & CONTROL_ROT_LEFT)
        {
            count = 0;
            llSetTimerEvent(10.0);
            llOwnerSay("Timer started.\nHold key on for 10 seconds.");
        }
        if (end & CONTROL_ROT_LEFT)
        {
            llSetTimerEvent(0.0);
        }
        count += 1;
    }
    timer()
    {
        llSetTimerEvent(0.0);
        llOwnerSay("Timer stopped.\nControl events count per 10sec : "+(string)count);
    }
    attach(key ID)
    {
        if (ID != NULL_KEY)
        {
            llSetTimerEvent(0.0);
            count = 0;
            llRequestPermissions(ID, PERMISSION_TAKE_CONTROLS);
        }
    }
    run_time_permissions(integer perm)
    {
        if (perm & PERMISSION_TAKE_CONTROLS)
        {
            llTakeControls(CONTROL_ROT_LEFT, TRUE, FALSE);
        }
    }
}
```
**(1)** While standing still press the **LeftTurn** key and **hold it for 10 seconds**. --> the avatar won't turn because the left turn control has been "taken" and the script should report about **230** events in 10 seconds.  This is ok.  What is really happening is the viewer is sending **AgentUpdates** at about 1Hz (keep alive rate when nothing is changing) but the server notices the key is being held down so it generates "repeat" **control** events at about 23Hz.

**(2)** Repeat step (1) but this time while holding down the left turn also walk forward in a flat open area without obstacles --> after 10 seconds the script should report about **440** or more events in 10 seconds.  This is because the avatar and camera are changing positions so AgentUpdate messages are sent more often, but still rate limited.

In the bugged version the **control** event rate when walking forward was lower than 440+ (I think).

**(3)** There is another quality (fixed by PR 2569) that relates to lag of **control** events when the input changes.  Unfortunately this requires some expertise as a driver of fast vehicles in SL to actually notice.  However Residents **Asdrea Evergarden** or maybe Alistar Snook could help you out.

**Comment by igorlproductengine** [comment]
Failed QA.
Verified on Agni on the Second Life Release 7.1.11.11074622243 on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/356.

Step 1 (without moving forward):
When holding the LeftTurn key for 10 seconds while standing still, the script correctly registers around 230 control events on both Windows 10 and macOS. This matches the expected behavior, where the viewer sends AgentUpdate messages at about 1Hz, and the server generates repeat control events at about 23Hz.

Step 2 (moving forward while turning left):
On Windows 10, when holding the LeftTurn key and moving forward simultaneously, the script registers over 440+ control events in 10 seconds, as expected due to increased AgentUpdate frequency while the avatar and camera are moving. However, on macOS, the script registers fewer than 440 events under the same conditions, which indicates the bug where the control event frequency is lower than expected while moving.

**Comment by AndrewMeadows** [comment]
I'm curious: what were the number of events on Mac?  If the viewer frame rate is low then the **AgentUpdate** rate will also be reduced and the measured **control** event rate will be affected.

I don't consider this failure to be a **blocker**.

**Comment by igorlproductengine** [comment]
Hello, @AndrewMeadows. On macOS, the frame rate was around 40-50 FPS during the test, and at times, I crossed parcel boundaries on the region, which might have influenced the results. On Windows, this didn’t seem to have any noticeable effect, but I thought it was important to mention, as in my opinion, if crossing parcel boundaries affects the event rate, this behavior might not be acceptable.

**Comment by AndrewMeadows** [comment]
Ok so an average update rate of 40Hz is good.  Close enough.  It is significantly more than the 23Hz.   Crossing parcel boundaries shouldn't have any effect.  OTOH... crossing **region** boundaries would probably produce a measurable reduction of average update rate, but I would not expect a big one -- a few updates might be lost during the time it takes to cross a region boundary.

More details... the high update rate in the moving case happens because the camera's transform is changing, which triggers the logic into deciding it needs to send an update.  If the avatar were to be stalled during the test such that it was not moving or rotating (e.g. crossing a region boundary or bumped up against a wall) then the measured update rate would be lower, functionally related to however long the camera was blocked or moving slowly.
