### ISSUE TITLE
Enabling the "Show bones" option enables the display of the border of all attached objects

### ISSUE THREAD

**Issue by DmitrySProductengine** [secondlife/viewer#2628]
### Environment
<details><summary>Environment</summary>
<p>

Second Life Release 7.1.11.10947335521 (64bit)
Release Notes

You are at 118.7, 117.0, 22.9 in Product Engine 3 located at simhost-0381ef04160a2ed12.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%203/119/117/23
(global coordinates 336759.0, 307061.0, 22.9)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2600 MHz)
Memory: 16384 MB
OS Version: macOS 14.5.0 Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-5.5.17

Window size: 1219x994
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (100.0% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091638
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/1640 (0.0%)
September 20 2024 07:16:11

</p>
</details> 

### Reproduction steps

**Steps to reproduce:**
1. Download and install the Second Life Release 7.1.11.10947335521 viewer (https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b589d39-ExtraFPS).
2. Log in to the Viewer.
3. Enable the "Show bones" option (Develop - Avatar - Show Bones).

**Actual result:**
Enabling the "Show bones" option enables the display of the border of all attached objects.

**Expected result:**
Enabling the "Show bones" option should enable the display of bones only.

**Additional information:**
According to the ‘SL Viewer Smoke Test - PE Master’ - [3.9.2 Upload and wear Bento Avatar](https://docs.google.com/document/d/1JtlZkp8l0WZPX8qg6YamSPGHwJMo8iVkM4_nKZqJBwE/edit#heading=h.wuvb8j3d2ph2).
This issue was found in the scope of [IQA #346](https://github.com/secondlife/iqa/issues/346).
This issue is reproduced on Win10, Win11, and OSX.

This issue is not reproduced on the current release 7.1.10.10800445603 build.

This may be the implementation of some new feature, but I couldn't find any information about it and therefore filed it as a bug.

See attached screenshots:
1. Actual - 7.1.11.10947335521
<img width="1920" alt="Actual - 7 1 11 10947335521" src="https://github.com/user-attachments/assets/b74eb04b-a519-4337-a9e3-6b913f1ae36d">

2. Expected - current release 7.1.10.10800445603
<img width="1920" alt="Expected - current release 7 1 10 10800445603" src="https://github.com/user-attachments/assets/6dbd5fba-f7de-4d0a-9bc1-dea1380a8da7">

**Comment by AtlasLinden** [comment]
This is new expected behaviour. Test plans to be updated
