### ISSUE TITLE
Reflection probe ambiance of 0 is still receiving tonemapping

### ISSUE THREAD

**Issue by RyeMutt** [secondlife/viewer#2632]
### Environment

Develop

### Description

Reflection probe ambiance of 0 in sky settings should not apply tonemapping to retain compatibility with legacy skies.

Regressed as part of changes for #2468

### Reproduction steps

1. Set Environment to Midday
2. Adjust Reflection Probe Ambiance to 0 in Personal Lighting
3. Observe that scene is still brightened/darkened from tonemapping

**Comment by igorlproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.11.11074622243 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/356.
