### ISSUE TITLE
Projected texture is visible on an alpha blending surface

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#2637]
### Environment

Second Life Release 7.1.11.10947335521 (64bit)
Release Notes

You are at 67.9, 39.5, 38.8 in Danger! Danger! located at simhost-0dd7e33bcf6d85949.agni
SLURL: http://maps.secondlife.com/secondlife/Danger%21%20Danger%21/68/40/39
(global coordinates 261,188.0, 249,640.0, 38.8)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4894)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 1556x1196
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 8192MB
Disk cache: Max size 1638.4 MB (11.9% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 2/6,467 (0.0%)
September 20 2024 14:02:10

### Description

Projected texture is visible on an alpha blending surface in the ExtraFPS viewer.

### Reproduction steps

Repro:
1. Upload the attached "254 of 255 opacity.png". (It's the big white gap after this sentence.) ![254 of 255 opacity](https://github.com/user-attachments/assets/f545045f-cac9-479b-b32a-b9d062257a83)
2. Apply the texture to a box.
3. Point a projector with a texture at the box.
4. Verify the projector texture is not visible on the box.

Observed: On ExtraFPS 7.1.11.10947335521, the projector is visible on the alpha texture.

Expected: The projector texture should not be visible on the object with the alpha texture.

<img width="1553" alt="alpha catching projector" src="https://github.com/user-attachments/assets/4b19529d-520a-414a-a52e-c062dfc6d65c">

**Comment by Geenz** [comment]
@Dan-Linden I checked the objects that should be set to alpha blending as noted in the screenshots, and they're set to no alpha mode and have no transparency applied.

Additionally, the provided texture does not seem to actually have any transparency information.  They're both being rendered as opaque as shown in this screenshot:
![Image](https://github.com/user-attachments/assets/3933b1bb-bb50-45c9-844a-0dc8ff12fa07)

Upon setting the green cube to 1% transparency, it correctly does not render the projected texture:
![Image](https://github.com/user-attachments/assets/b42b5e11-a17b-4b2c-b973-535b842f78e7)

Same for the red cube:
![Image](https://github.com/user-attachments/assets/f459d972-4b21-4592-ad9d-fc7870925196)

**Comment by Dan-Linden** [comment]
@Geenz can you test again?

It's the left white object in this screenshot which has the bug:
![Image](https://github.com/user-attachments/assets/70e18a4a-18c9-455b-b22d-57289033977f)

Repro:
1. Run the DeltaFPS viewer https://releasenotes.secondlife.com/viewer/7.1.10.10800445603.html
2. Download the attached "254 of 255 opacity.png" and uploaded it to Second Life
3. Create a new box in front of the projector.
4. Drag the uploaded "254 of 255 opacity.png" image onto the box. No need to edit anything else on the box. It should be automatically set to Alpha blending.

Observe: The box looks solid white and does not show the stripe pattern from the projector.
Log in an ExtraFPS viewer and observe that the box has a stripe pattern from the projector.

**Comment by Dan-Linden** [comment]
The boundary for this bug is between alpha value 208 and 209. This is on a scale where 0 is transparent and 255 is opaque.
On the ExtraFPS viewer, textures with an alpha value of 209 or greater will show a projector texture that is projected onto them. Textures with alpha of 208 or less will not show the projector texture.
On the DeltaFPS and older viewers, all 32-bit textures do not display a projector texture.

Here's a white texture, alpha is set to 208 (of 255) white.
![Image](https://github.com/user-attachments/assets/6d9d91c2-462d-4e5e-b3a3-b8be9e300129)

Here's a white texture, alpha is set to 209 (of 255) white.
![Image](https://github.com/user-attachments/assets/9314afe8-e72f-45f0-8433-37d832490a18)

**Comment by Dan-Linden** [comment]
This appears fixed in build 7.1.11.11748636296.
