### ISSUE TITLE
ExtraFPS colors horrible.

### ISSUE THREAD

**Issue by RonKhondji** [secondlife/viewer#2645]
### Environment

 Second Life Release 7.1.11.10947335521 (64bit)
Release Notes

You are at 45.3, 130.4, 72.3 in Monowai located at simhost-0725d54e64c6632e1.agni
SLURL: http://maps.secondlife.com/secondlife/Monowai/45/130/72
(global coordinates 260,141.0, 232,066.0, 72.3)
Second Life RC Magnum 2024-07-22.10048683488
Release Notes

CPU: AMD Ryzen 9 5950X 16-Core Processor             (3393.65 MHz)
Memory: 65441 MB
OS Version: Microsoft Windows 11 64-bit (Build 22631.4169)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3090/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5612
OpenGL Version: 4.6.0 NVIDIA 556.12

Window size: 2560x1369
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 200m
Bandwidth: 3000kbit/s
LOD factor: 4
Render quality: 5
Texture memory: 24576MB
Disk cache: Max size 1228.8 MB (16.4% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 25/193,292 (0.0%)
September 22 2024 02:56:19

### Description

I've tried the ExtraFPS viewer and noticed the colors on my mainland parcel are not what they have always been. It seems to be something that is fixable with environment settings.
Attached are 4 pictures with comparisons between Alchemy (which is as it always used to before ExtraFPS) and ExtraFPS at 4 environment times. Only the Midday time is somewhat bearable, although I think the color saturation is too much. 

Sunrise
![Sunrise](https://github.com/user-attachments/assets/c49b56e4-d74a-4d53-b8dc-896d643a94f7)

Midday
![Midday](https://github.com/user-attachments/assets/09e69976-561d-46f9-ab4e-fe3f6b4f2a63)

Sunset
![Sunset](https://github.com/user-attachments/assets/3c40cc1f-202d-49c9-8df2-20ccf7e44cfd)

Midnight
![Midnight](https://github.com/user-attachments/assets/ce12476c-12dc-4daf-b95f-a37e427f6db5)

I thought I'd mention it now to avoid drama when this viewer goes to release. If it's known and/or as intended then please ignore this report.

### Reproduction steps

1. Download  Second_Life_7_1_11_10947335521_x86_64_Setup.exe 
2. Install
3. Run with 'Use Shared Environment' or anything that's not Midday.

**Comment by Crexon1** [comment]
This might be the change to use the Kronos Neutral tonemapper. The old ACES tonemapper is still available to switch back if you prefer that one in the Advanced>Debug settings search for rendertonemaptype. 0 = Khronos Neutral, 1 = ACES
This was noted on release notes https://github.com/secondlife/viewer/pull/2468

**Comment by RonKhondji** [comment]
Thank you.
That wasn't the problem, but it did point me in the direction I needed to look.

The problem, for me, was the other debug setting: RenderTonemapMix. Changing that from 1.0 to 0.0 fixed my colors.

**Comment by Crexon1** [comment]
Ahh, if you had your EEP setting of reflection probe ambience to 0, then there was a bug where HDR tonemapping was still getting applied to it being in SDR. That was fixed here https://github.com/secondlife/viewer/issues/2632
