### ISSUE TITLE
The "Day Offset (hours)" option takes a value of the "Day Lenght (hours)" option after setting the "Day Offset (hours)" to "0" value in the "Environment" tab of the "Region/Estate" floater

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#2648]
### Environment

Second Life Release 7.1.11.10947335521 (64bit)
Release Notes

You are at 213.5, 106.7, 21.6 in Product Engine located at simhost-07e989f3f263c4188.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/213/107/22
(global coordinates 336,853.0, 307,307.0, 21.6)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3696 MHz)
Memory: 32688 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4894)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT

Windows Graphics Driver Version: 26.20.15029.27017
OpenGL Version: 4.6.13587 Core Profile Context 20.4.2 26.20.15029.27017

Window size: 1920x1017
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (1.2% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 79/36,553 (0.2%)
September 23 2024 07:25:58

### Description

The "Day Offset (hours)" option takes a value of the "Day Lenght (hours)" option after setting the "Day Offset (hours)" to "0" value in the "Environment" tab of the "Region/Estate" floater.

### Reproduction steps

1. Download and install the [Second Life Release 7.1.11.10947335521](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b589d39-ExtraFPS) build.
2. Log in with the estate manager account.
3. Teleport to a region where the account is an estate manager.
4. Click "World"→"Region/Estate"→"Environment" tab.
5. Set the "Day Lenght (hours)" option to a value from "4.0" to "12.0" (e.g. "5.0").
6. Set the "Day Offset (hours)" option to "0".
7. Observe the "Day Offset (hours)" value.

**Actual result:**
The "Day Offset (hours)" option takes a value of the "Day Lenght (hours)" option after setting the "Day Offset (hours)" to "0" value in the "Environment" tab of the "Region/Estate" floater.

**Expected result:**
The "Day Offset (hours)" should be set to "0" in the "Environment" tab of the "Region/Estate" floater.

**Note:**
This issue is reproduced on Win10/OSX.

This issue was found during testing of [secondlife/viewer/issues/2363](https://github.com/secondlife/viewer/issues/2363).

**Also**, 
The "Day Lenght (hours)" options range from "4.0" to "168.0".
The "Day Offset (hours)" options range from "-11.5" to "12".

So, this issue is reproduced for values from "4.0" to "12.0" ("Day Lenght (hours)" min value is "4.0", "Day Offset (hours)" max value is "12.0").

This issue is **not reproduced** on the current production build Second Life Release 7.1.10.10800445603.

**actual.mp4**
https://github.com/user-attachments/assets/c01a23b7-c66c-4cfd-8d7c-4efb8bc39868

**Comment by akleshchev** [comment]
0 hours is equal to day length (ex: if day length is 24h, 24h==0h) so it is a low priority issue, but I will see if I can make it nicer.

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11074622243 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/356.
