### ISSUE TITLE
Add UI for debug settings: RenderTonemapMix RenderTonemapType

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2650]
Add UI for the following debug settings for adjustment in Advanced Graphics Preferences: 
- RenderTonemapMix 
- RenderTonemapType

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11469579464 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/374.
