### ISSUE TITLE
Senra avatars face animations not playing

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2672]
### Environment

DeltaFPS (7.1.10.10800445603) and ExtraFPS (7.1.11.10947335521) viewers 
Also tested back to the Emoji viewer (7.1.3.7659007892)

### Description

Senra avatars do not appear to support face animations using gestures or moving lips when speaking.
These animations do function correctly for the Boy Next Door avatar (Develop>Avatar>Character Tests>Test Male

### Reproduction steps

1. Wear a Senra avatar
2. Ensure setting "Move avatar lips when speaking" is enabled
3. Verify avatar lips move when speaking
4. Play a gesture that moves avatar face/lips 
5. Verify avatar face and lips move

**Comment by Dan-Linden** [comment]
Check if this works after removing the AO. I have a feeling the AO has a very high priority.

**Comment by Dan-Linden** [comment]
Turning off the HUD does not make lip movement work.

The Senra Blake -head has a Priority 5 animation in it. Removing the animation script from the head, the reattaching it did not make lip movement work.

If the Senra Blake head is removed, I can see the default avatar mesh lips morph when talking.
After enabling on Develop > Metadata > Joints, I see that no bones move while talking. The lip morphing is probably driven by a face shape parameter.

**Comment by kylelinden** [comment]
Expected behavior.
Mesh heads will not morph with mouth animations. (If you see this working its a scripted animation add-on)
System heads will morph with mouth animations.
