### ISSUE TITLE
Antialiasing option SMAA

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2673]
### Environment

Introduced in ExtraFPS viewers: 7.1.11.10947335521 and above

### Description

New antialiasing option ([Enhanced Subpixel Morphological](https://www.iryoku.com/smaa/)) introduced: https://github.com/secondlife/viewer/pull/2466 
This issue is made for testing purposes.

### Test Plan
1. Verify Antialiasing dropdown is provided with the following options: 
1.1 Disabled
1.2 FXAA
1.3 SMAA
2. Verify Antialiasing dropdown is provided with the following options: 
2.1 Low
2.2 Medium
2.3 High
2.4 Ultra
3. Verify the above quality options for both FXAA and SMAA
4. Verify that no AA effect is detected when Disabled is selected regardless of which quality setting is chosen (i.e. no smooth edges)
5. Turn on Screen Space Reflections (SSR) and verify no colour issues are spotted with either FXAA or SMAA applied
6. Verify the following AA settings are selected for the given graphics quality
- Windows

| Low | Low+ | Mid | Mid+ | High | High+ | Ultra |
| --- | --- | --- | --- | --- | --- | --- |
| Disabled + Low | Disabled + Low | FXAA + Medium | FXAA + Medium | SMAA + High | SMAA + High | SMAA + Ultra |

- Mac

| Low | Low+ | Mid | Mid+ | High | High+ | Ultra |
| --- | --- | --- | --- | --- | --- | --- |
| Disabled + Low | Disabled + Low | FXAA + **Low** | FXAA + Medium | **FXAA** + High | SMAA + High | SMAA + Ultra |

**Note:** AA Quality will ALWAYS be Low for Intel macs

**Comment by dmytrohproductengine** [comment]
Win10 - Passed QA.
OSX - Failed QA.

Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.

On OSX, the antialiasing option "FXAA + Low" is shown after choosing the "Mid+", "High", High+" and "Ultra" quality and speed graphics preset in the "Advanced Graphics Preferences" floater (please, see screenshots below).

@AtlasLinden, could you please clarify, if the SSR is the "Screen Space Reflections" option in the "Advanced Graphics Preferences" floater?
Thank you.

**7.1.11.10947335521_mid+.png**
![7 1 11 10947335521_mid+](https://github.com/user-attachments/assets/a905f20d-2eaa-43e2-9137-196cc44f66ec)

**7.1.11.10947335521_high.png**
![7 1 11 10947335521_high](https://github.com/user-attachments/assets/2da9f542-cf50-4ea2-96ac-29084c2b2c3b)

**7.1.11.10947335521_high+.png**
![7 1 11 10947335521_high+](https://github.com/user-attachments/assets/533ea1e6-dd2d-4dca-a8de-f63022b0c7e5)

**7.1.11.10947335521_ultra.png**
![7 1 11 10947335521_ultra](https://github.com/user-attachments/assets/f12ade73-cf70-4b0a-9b2d-2d657156c12f)

**Comment by AtlasLinden** [comment]
Hi @dmytrohproductengine,
Yes SSR is Screen Space Reflections which is found in Advanced Graphics Preferences.
And it seems I didn't take into account the change that is made for Intel Macs in the above test plan. That is, the AA Quality is always going to be Low for Intel Macs. Thanks for verifying on this machine.
Both of these comments have been updated in the above test plan

**Comment by dmytrohproductengine** [comment]
@AtlasLinden, thank you for the clarification!
