### ISSUE TITLE
Sharpening setting CAS

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2682]
### Environment

Introduced in ExtraFPS viewers: 7.1.11.10947335521 and above

### Description

New sharpening setting ([Contrast Adaptive Sharpening](https://github.com/GPUOpen-Effects/FidelityFX-CAS?tab=readme-ov-file)) introduced: https://github.com/secondlife/viewer/pull/2415

This issue is made for testing purposes.

### Test Plan
1. Verify Sharpening slider is provided in Advanced Graphics Preferences. Slider values range from 0.0 - 1.0 and can be incremented in steps of 0.1.
2. Verify that the sharpness increases as the slider is dragged from 0 to 1. (Observing highly detailed objects will help to spot an obvious change. The sample objects here for instance: secondlife://Aditi/secondlife/Rumpus%20Room%202048/129/156/23)
3. Verify that no other graphics anomalies are spotted when adjusting this setting. (Particularly with SMAA/FXAA and Depth of Field when sharpness is at 0.0 and 1.0.)

**Comment by igorlproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.11.11074622243 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/356.
