### ISSUE TITLE
"Select grid" text is shown in the grid selector on the regular login screen page in the viewer

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#2697]
### Reproduction steps:
1. Download and install the [Second Life Release 7.1.11.10945332304](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b111dce-maint-b-2024-09-19) build.
2. Click "Me"→"Preferences"→"Advanced" tab.
3. Check the "Show Grid Selection at login" checkbox→click "OK".
4. Log in and restart the viewer.
5. Observe the grid selector.

**Actual result:**
"Select grid" text is shown in the grid selector on the regular login screen page in the viewer.

**Expected result:**
The name of the last logged-in grid should be shown in the grid selector on the regular login screen page in the viewer:
Second Life Main Grid (Agni) / Second Life Beta Test Grid (Aditi).

**Note:**
This issue is reproduced on Win11/Win10/OSX.

This issue was found during ad-hoc testing.

**Also**, the chosen grid is not shown in the grid selector after scrolling it by the mouse wheel on the regular login screen page in the viewer as pointed out in [secondlife/viewer/issues/2698](https://github.com/secondlife/viewer/issues/2698).

This issue is **not reproduced** on the current production build Second Life Release 7.1.10.10800445603.

<details><summary>Environment</summary>
<p>
Second Life Release 7.1.11.10945332304 (64bit)
Release Notes

You are at 213.0, 108.0, 21.5 in Product Engine located at simhost-04fc9fd708f788a32.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/213/108/22
(global coordinates 336,853.0, 307,308.0, 21.5)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3696.01 MHz)
Memory: 32688 MB
OS Version: Microsoft Windows 11 64-bit (Build 22631.4169)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT

Windows Graphics Driver Version: 32.0.11037.4004
OpenGL Version: 4.6.0 Core Profile Context 24.8.1.240822

Window size: 1920x1009
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 4055MB
Disk cache: Max size 1638.4 MB (0.3% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 1/1,175 (0.1%)
September 26 2024 04:00:14
</p>
</details>

**actual.png**
![actual](https://github.com/user-attachments/assets/9d263dec-e86e-47a4-babb-c2bd4e774702)

**Comment by LLGuru** [comment]
Fixed by https://github.com/secondlife/viewer/commit/2e68f3d7dc2f512fd0c948a47ae8b3942a15ce2c

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11296522354 (64bit) on Win10/OSX in the scope of [IQA#366](https://github.com/secondlife/iqa/issues/366).
