### ISSUE TITLE
The chosen grid is not shown in the grid selector after scrolling it by the mouse wheel on the regular login screen page in the viewer

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#2698]
### Reproduction steps

1. Download and install the [Second Life Release 7.1.11.10945332304](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b111dce-maint-b-2024-09-19) build.
2. Click "Me"→"Preferences"→"Advanced" tab.
3. Check the "Show Grid Selection at login" checkbox→click "OK".
4. Log in and restart the viewer.
5. Hover the mouse on the grid selector.
6. Scroll by mouse wheel up/down.

**Actual result:**
The chosen grid is not shown in the grid selector after scrolling it by mouse wheel on the regular login screen page in the viewer.

**Expected result:**
The chosen grid should shown in the grid selector after scrolling it the mouse wheel on the regular login screen page in the viewer.

**Note:**
This issue is reproduced on Win11/Win10/OSX.

This issue was found during ad-hoc testing.

**Also**, the grids switch as expected.
"Select grid" text is shown in the grid selector on the regular login screen page in the viewer, as pointed out in [secondlife/viewer/issues/2697](https://github.com/secondlife/viewer/issues/2697).

This issue is **not reproduced** on the current production build Second Life Release 7.1.10.10800445603 (see "expected_release.mp4").

<details><summary>Environment</summary>
<p>
Second Life Release 7.1.11.10945332304 (64bit)
Release Notes

You are at 213.0, 108.0, 21.5 in Product Engine located at simhost-04fc9fd708f788a32.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/213/108/22
(global coordinates 336,853.0, 307,308.0, 21.5)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3696.01 MHz)
Memory: 32688 MB
OS Version: Microsoft Windows 11 64-bit (Build 22631.4169)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT

Windows Graphics Driver Version: 32.0.11037.4004
OpenGL Version: 4.6.0 Core Profile Context 24.8.1.240822

Window size: 1920x1009
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 4055MB
Disk cache: Max size 1638.4 MB (0.3% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/787 (0.0%)
September 26 2024 04:07:40
</p>
</details>

**actual.mp4**
https://github.com/user-attachments/assets/04f552a0-f2ce-4418-90a1-b94f1ab7a794

**expected_release.mp4**
https://github.com/user-attachments/assets/7dbcfaf9-9c96-4c02-bc5c-e718f759ddbb

**Comment by LLGuru** [comment]
Fixed by https://github.com/secondlife/viewer/commit/2e68f3d7dc2f512fd0c948a47ae8b3942a15ce2c

**Comment by igorlproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11296522354 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/366.
