### ISSUE TITLE
Nametags appear squashed

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2709]
### Environment

ExtraFPS 7.1.11.10947335521 
Both Win11 and Mac

### Description

Nametags have an odd dip in ExtraFPS.
![Screen Shot 2024-09-26 at 11 07 46 AM](https://github.com/user-attachments/assets/36c7f0c9-3360-4b5a-a6fc-d15f12837d80)

### Reproduction steps

View nametags

**Comment by valeriiaaproductengine** [comment]
Passed QA.

The previous issue is now resolved. But now a small piece has appeared in the upper left corner of the Nametag. See the actual.png screenshot.

![actual](https://github.com/user-attachments/assets/aa6bb62e-a8cb-437a-9e12-8703f6b18f9e)


Verified on the Second Life Release 7.1.11.11074622243 (64bit) on Win11/OSX in the scope of https://github.com/secondlife/iqa/issues/356.

**Comment by akleshchev** [comment]
Fixed, returning back to QA.

**Comment by georgebproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11296522354 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/366.
