### ISSUE TITLE
Clouds are preserved at Low or Low-Mid graphics settings

### ISSUE THREAD

**Issue by georgebproductengine** [secondlife/viewer#2717]
**Steps to reproduce:**
 1.Log in to the Viewer.
 2.Open preferences and set Low or Low-Mid  'Quality&speed 'settings.
 3.Apply sky with clouds (e.g. Sheer Surreality).

**Actual result:**
Clouds are preserved at Low or Low-Mid graphics settings

**Expected result:** 
Clouds should dissappear at Low or Low-Mid graphics settings

**According to** the [Environment Rendering conformity test plan](https://lindenlab.atlassian.net/wiki/spaces/SLPP/pages/748323232/Environment+Rendering+conformity+test).
Test: Sky presets - Test 3.  4) No clouds.

**Additional info:**
The issue is reproduced on the OSX/Win10.
This issue is reproduced on production Second Life Release 7.1.10.10800445603 .

<details open>
<summary>Actual screenshot</summary>
<br>
<img width="1227" alt="Screenshot 2024-09-27 at 14 02 17" src="https://github.com/user-attachments/assets/d43e6c36-9b43-4839-a585-e11693c50c1c">

</details>

### Environment

<details open>
<summary>  </summary>
<br>
Second Life Release 7.1.11.10947335521 (64bit)
Release Notes

You are at 2.7, 15.4, 21.4 in Product Engine 3 located at simhost-06c92da1cee01d90f.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%203/3/15/21
(global coordinates 336643.0, 306959.0, 21.4)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2600 MHz)
Memory: 16384 MB
OS Version: macOS 14.5.0 Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-5.5.17

Window size: 1140x777
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (22.3% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091638
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Not Connected
Packets Lost: 0/3783 (0.0%)
September 27 2024 06:23:59
</details>

**Comment by Dan-Linden** [comment]
This may be expected behavior and actually a stale test plan. The cloud visibility is probably tied to ALM, and ALM is always on now.

**Comment by AtlasLinden** [comment]
Cloud visibility was tied to setting Atmospheric Shaders which is now on permanently as of PBR..
Requires test plan update.
