### ISSUE TITLE
Water sometimes doesn't look right

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#2730]
### Description

This bug occurred spontaneously after teleporting between regions on the beta grid. Specifically, I was teleporting from Rumpus Room 2 to CloudChamber. While I was at CloudChamber, I noticed the water looked weird, so I set the environment settings to default midday via Ctrl+Shift+Y, which did not fix the issue. I teleported to Rumpus Room and the water was still weird.

This bug occurred in a Release build built by Visual Studio off the tip of develop (`9e8cf72a355d5353564c0199990a6b5073f37fca`)

In the first image in Rumpus Room 2, the void water looks rather plain:

![water_what_plain](https://github.com/user-attachments/assets/acdb52d1-91be-4943-90fc-d4c55098bb9b)

In the second image in Rumpus Room 2, the void water has holes in it, as if it is missing the hazy underwater behind it, but possibly still rendering the sky:

![water_what_holes](https://github.com/user-attachments/assets/3f82c7ca-97a2-4139-ab5c-b37118a8bffe)

In CloudChamber (didn't take a picture), the above-terrain water had holes in it as well, but I could still see the ground underneath, which was tinted slightly darker. So, it seems that the water was rendering what was underneath it, but missing the haze.

Here's a few images of what the water looks like in Rumpus Room 2 on the same viewer, after restart when the bug is not occurring:

![water_ok_top](https://github.com/user-attachments/assets/67874d7a-ea6c-453e-9991-14d0b93b3226)
![water_ok_side](https://github.com/user-attachments/assets/c9911ccd-d830-419e-821b-b0179b0c5496)

I will note that the water looked similarly to the first two images when teleporting between Rumpus Room 2 and CloudChamber and watching the water change color. Could it be possible that some environment transition got stuck? However, that doesn't easily explain why the underwater haze was missing. Environment settings seemed fine otherwise for the terrain and objects.

**Comment by Dan-Linden** [comment]
See if this is fixed by the fix for https://github.com/secondlife/viewer/issues/2889

**Comment by georgebproductengine** [comment]
Deferred QA.

This issue unable to test because PE doesn't have access to the CloudChamber region.
Verified on the Second Life Release 7.1.11.11469579464 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/374..
