### ISSUE TITLE
Several small textures are blurred after unfocusing the viewer application window

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#2789]
### Reproduction steps

1. Open the viewer and log in.
2. Teleport to "http://maps.secondlife.com/secondlife/Bug%20Island/32/151/27".
3. Wait for uploading the textures.
4. Make the viewer window not maximized.
5. Open any other window or application in OS to unfocus the viewer's window (e.g. "Google Chrome").
6. Wait for 5-15 seconds.
7. Observe the small textures looking.

**Actual result:**
Several small textures are blurred after unfocusing the viewer application window in the "Small texture loading" test from the "Bug Island Test".

**Expected result:**
The small textures should look the same as before unfocusing the viewer application window.

**Note:**
This issue is reproduced on Win11/Win10/OSX.

This issue was found during ad-hoc testing of the "Small texture loading" test from ["Bug Island Test"](https://wiki.secondlife.com/wiki/Bug_Island_Test#Small_texture_loading) test plan.

**Perhaps**, this is expected behavior due to decreasing viewer FPS after unfocusing the viewer application window. Small textures became blurred with FPS lower than 21. After focusing on the viewer's window again, the FPS is increased and the small textures look as expected (see "actual_fps.mp4").

This issue is **reproduced** on the current production build Second Life Release 7.1.10.10800445603.

**actual.png**
![actual](https://github.com/user-attachments/assets/2ec14d3e-cfc3-4f84-b4e3-8c8f05065fc3)

**actual_fps.mp4**
https://github.com/user-attachments/assets/06dd3958-4c39-499f-8049-773ade48dd08

<details><summary>Environment</summary>
<p>
Second Life Release 7.1.11.11074622243 (64bit)
Release Notes

You are at 31.8, 151.6, 27.3 in Bug Island located at simhost-09cfd04007c40adad.agni
SLURL: http://maps.secondlife.com/secondlife/Bug%20Island/32/152/27
(global coordinates 260,128.0, 249,496.0, 27.3)
Second Life RC Magnum 2024-09-13.10853867644
Release Notes

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3696.01 MHz)
Memory: 32688 MB
OS Version: Microsoft Windows 11 64-bit (Build 22631.4249)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT

Windows Graphics Driver Version: 32.0.11037.4004
OpenGL Version: 4.6.0 Core Profile Context 24.8.1.240822

Window size: 1920x1009
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 4055MB
Disk cache: Max size 1638.4 MB (0.7% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/2,714 (0.0%)
October 04 2024 00:44:57
</p>
</details>

**Comment by AtlasLinden** [comment]
This is currently expected behaviour although that may change for higher end systems in https://github.com/secondlife/viewer/issues/2549
