### ISSUE TITLE
8 green light shining sphere objects are shown at a time in the viewer

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#2790]
### Reproduction steps

1. Open the viewer and log in.
2. Teleport to "http://maps.secondlife.com/secondlife/Bug%20Island/32/131/27".
3. Set "World" → "Environment" → "Midnight".
4. Set "Me" → "Preferences" → "Graphics" to "Mid".
5. Detach any light attachments (if there are any attachments on an avatar).
6. There are 8 green lights shining on 8 spheres in front of you, but only 6 lights will show at a time.
7. Move back and forth and verify that only 6 of the 8 lights appear at any one time.

**Actual result:**
8 green light shining sphere objects are shown at a time in the viewer in the "Lights" test from the "Bug Island Test".

**Expected result:**
Only 6 green light shining sphere objects should be shown at a time in the viewer in the "Lights" test from the "Bug Island Test".

**Note:**
This issue is reproduced on Win11/Win10/OSX.

According to the [Bug Island Test](https://wiki.secondlife.com/wiki/Bug_Island_Test#Lights) test plan.
Section: 11. Lights.
Step: 
There are 8 green lights shining on 8 spheres in front of you, but only 6 lights will show at a time.
Move back and forth and verify that only 6 of the 8 lights appear at any one time.

This issue is **reproduced** on the current production build Second Life Release 7.1.10.10800445603.

**actual.png**
![actual](https://github.com/user-attachments/assets/355de0f3-1b19-4c77-a49e-f01b4c28705f)

<details><summary>Environment</summary>
<p>
Second Life Release 7.1.11.11074622243 (64bit)
Release Notes

You are at 31.3, 131.3, 27.3 in Bug Island located at simhost-09cfd04007c40adad.agni
SLURL: http://maps.secondlife.com/secondlife/Bug%20Island/31/131/27
(global coordinates 260,127.0, 249,475.0, 27.3)
Second Life RC Magnum 2024-09-13.10853867644
Release Notes

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3696.01 MHz)
Memory: 32688 MB
OS Version: Microsoft Windows 11 64-bit (Build 22631.4249)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT

Windows Graphics Driver Version: 32.0.11037.4004
OpenGL Version: 4.6.0 Core Profile Context 24.8.1.240822

Window size: 1920x1009
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 4055MB
Disk cache: Max size 1638.4 MB (1.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/899 (0.0%)
October 04 2024 01:25:31
</p>
</details>

**Comment by Dan-Linden** [comment]
This is now expected behavior, now that ALM is always on. The test plan needs to be updated.

**Comment by Dan-Linden** [comment]
Test updated.
