### ISSUE TITLE
The halo is reflected in the water

### ISSUE THREAD

**Issue by vladyslavasproductengine** [secondlife/viewer#2792]
Steps to reproduce:
Test1:

1. Login in the Viewer.
2. Teleport to http://maps.secondlife.com/secondlife/Bug%20Island%202/38/250/23
3. Use World menu > Environment > Use Shared Environment
4. Shadows are enabled.

Actual Screenshot:
![halotest1](https://github.com/user-attachments/assets/02db7cbb-4eaa-480f-8d94-5005520f4bb2)

Expected Screenshot:
![Sun halo 0 1](https://github.com/user-attachments/assets/f9b822e2-a4af-4d50-893f-6d0e76606308)

Test4:

1. Login in the Viewer.
2. Teleport to http://maps.secondlife.com/secondlife/Bug%20Island%202/50/247/23
3. Use World menu > Environment > Use Shared Environment
4. Shadows are enabled.

Actual Screenshot:
![halotest4](https://github.com/user-attachments/assets/d1cf7bac-b3ec-4aa0-b2bf-02bdce996790)

Expected Screenshot:
![Sun halo and moon](https://github.com/user-attachments/assets/6508b7d5-3315-44e6-beaa-39da42bfd18c)

Test5:

1. Login in the Viewer.
2. Teleport to http://maps.secondlife.com/secondlife/Bug%20Island%202/54/250/23
3. Use World menu > Environment > Use Shared Environment
4. Shadows are enabled.

Actual Screenshot:
![halotest5](https://github.com/user-attachments/assets/435a65d6-73de-4d42-abfa-4957c792a203)

Expected Screenshot:
![Moon halo](https://github.com/user-attachments/assets/9ffbcc61-83cc-48b2-a649-6d36209f87d9)

Actual behavior:
The halo is reflected in the water.
Expected behavior:
The halo does not reflect in the water.

Additional information:
This issue was found according to the test plan:EEP Render Features test
https://lindenlab.atlassian.net/wiki/spaces/QA/pages/750190683/EEP+Render+Features+test
This issue is reproduced on the current production build Second Life Release 7.1.10.10800445603 (64bit).
This issue is reproduced on Win10/OSX.

<details><summary>Environment</summary>
<p>

Second Life Release 7.1.11.11074622243 (64bit)
Release Notes

You are at 54.0, 250.0, 25.6 in Bug Island 2 located at simhost-0ad04c4bcce5e167c.agni
SLURL: http://maps.secondlife.com/secondlife/Bug%20Island%202/54/250/26
(global coordinates 260,406.0, 249,594.0, 25.6)
Second Life Server 2024-09-13.10853867644
Release Notes

CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (2712.01 MHz)
Memory: 8067 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4894)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: GeForce 940MX/PCIe/SSE2

Windows Graphics Driver Version: 25.21.14.1735
OpenGL Version: 4.6.0 NVIDIA 417.35

Window size: 1920x1001
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 2048MB
Disk cache: Max size 1638.4 MB (20.7% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/892 (0.0%)
October 04 2024 02:14:12

</p>
</details>

**Comment by AtlasLinden** [comment]
This is new expected behaviour and requires a test plan update.

**Comment by Dan-Linden** [comment]
I am curious in which Release this started and if it was intentional.
