### ISSUE TITLE
Horizon and water look the same at all graphics settings when flying

### ISSUE THREAD

**Issue by katerynamproductengine** [secondlife/viewer#2794]
### Environment

<details><summary>Environment</summary>
Second Life Release 7.1.11.11074622243 (64bit)
Release Notes

You are at 128.0, 128.0, 299.8 in Bug Island 2 located at simhost-0ad04c4bcce5e167c.agni
SLURL: http://maps.secondlife.com/secondlife/Bug%20Island%202/128/128/300
(global coordinates 260480.0, 249472.0, 299.8)
Second Life Server 2024-09-13.10853867644
Release Notes

CPU: Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (1600 MHz)
Memory: 16384 MB
OS Version: macOS 13.6.9 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Mon Jun 24 01:25:37 PDT 2024; root:xnu-8796.141.3.706.2~1/RELEASE_X86_64 x86_64
Graphics Card Vendor: Intel Inc.
Graphics Card: Intel(R) UHD Graphics 617

OpenGL Version: 4.1 INTEL-20.7.2

Window size: 1440x876
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 256m
Bandwidth: 3000kbit/s
LOD factor: 2
Render quality: 6
Texture memory: 1536MB
Disk cache: Max size 1638.4 MB (1.9% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091638
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 17/10472 (0.2%)
October 04 2024 03:10:51
</details>

### Reproduction steps

1. Log into the viewer on Agni grid at the location:  http://maps.secondlife.com/secondlife/Bug%20Island%202/128/128/300 facing Southeast. 
2. Press the escape key so the camera is at the default position.
3. Set graphics settings from “Low” to “Low/Mid “, “Mid”, “Mid/High”, “High”, “High/Ultra” or “Ultra”.
4. Observe the environment.

**Actual result:** There is no a gray gap between the sky and water on “Low” graphic setting. Water color is regular (almost no gradients from light to dark) and the same on all graphics settings. There clouds are not reflected faintly in the water on “Mid”, “Mid/High” graphics settings. The horizon is not a slight U shape, bending up at the edges of the screen on the “Mid/High” graphic setting.

Actual screenshot:
<details><summary>Low:</summary>
<img width="1440" alt="Screenshot 2024-10-04 at 11 45 01 AM" src="https://github.com/user-attachments/assets/bb02dd44-d454-49f4-83e0-24e86107329b">
</details>
<details><summary>Low/Mid:</summary>
<img width="1440" alt="Screenshot 2024-10-04 at 11 46 19 AM" src="https://github.com/user-attachments/assets/1a0a2461-7eeb-419d-ab0c-10e17e8563c1">
</details>
<details><summary>Mid:</summary>
<img width="1440" alt="Screenshot 2024-10-04 at 11 11 47 AM" src="https://github.com/user-attachments/assets/daa285bd-8096-49d1-9554-ce50ee7a3fb0">
</details>
<details><summary>Mid/High:</summary>
<img width="1440" alt="Screenshot 2024-10-04 at 11 11 58 AM" src="https://github.com/user-attachments/assets/c9da3b43-6b22-4d69-8bcb-2cec2a10cf04">
</details>

**Expected result:** There is a gray gap between the sky and water on “Low” graphic setting. The water is dark blue at the bottom of the screen and transitions to a blueish gray at the horizon on “Low/Mid “, “Mid” graphics settings. There clouds are reflected faintly in the water on the “Mid”, “Mid/High” graphics settings. The horizon is a slight U shape, bending up at the edges of the screen on “Mid/High” graphic setting.

Expected screenshot:
<details><summary>Low:</summary>
<img width="887" alt="Screenshot 2024-10-04 at 11 47 53 AM" src="https://github.com/user-attachments/assets/dd4cecc5-7358-4960-90cd-626ae1d8ec5b">
</details>
<details><summary>Low/Mid:</summary>
<img width="882" alt="Screenshot 2024-10-04 at 11 48 35 AM" src="https://github.com/user-attachments/assets/4d4e9b64-1a46-424a-aa93-87ca1a7d65b0">
</details>
<details><summary>Mid:</summary>
<img width="885" alt="Screenshot 2024-10-04 at 11 49 08 AM" src="https://github.com/user-attachments/assets/69bb8527-deda-4d4e-b4bc-81d885ba5ebb">
</details>
<details><summary>Mid/High:</summary>
<img width="884" alt="Screenshot 2024-10-04 at 11 49 37 AM" src="https://github.com/user-attachments/assets/75a7aa25-e438-475c-8f19-2593142a75b6">
</details>

**Additional information:**
This issue was found in the scope of [IQA #353](https://github.com/secondlife/iqa/issues/353) during Environment Rendering conformity test -> Sky and water tests -> Test8/ Test9/ Test10/ Test11 (https://lindenlab.atlassian.net/wiki/x/oIGaL).
This issue is reproduced on Win10/OSX.
This issue is reproduced on the current release 7.1.10.10800445603 build.

**Comment by AtlasLinden** [comment]
New expected behaviour. Requires test plan update.
