### ISSUE TITLE
The front face of the 2nd box is not slightly darker than the two adjacent boxes when the "projector light without ambient" is enabled

### ISSUE THREAD

**Issue by sergiiiproductengine** [secondlife/viewer#2799]
**Steps to reproduce:**
1. Login to the [7.1.11.11074622243 viewer](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2364c055f-ExtraFPS).
2. Teleport to the http://maps.secondlife.com/secondlife/Bug%20Island%202/246/127/23 location facing East.
3. Change Render Settings to High or higher (Me > Preferences > Graphics > Quility & Speed slider).
4. Change environment to Midday (World > Environment > Midday).
5. Go to World > Environment > Personal Lighting and change the sun position (Azimuth - 45, Elevation - 90).
6. Change HDR Scale to 1.01 value and back to 1.00 (due to [secondlife/viewer/issues/2705](https://github.com/secondlife/viewer/issues/2705) issue).
7. Close Personal Lighting floater.
8. Click the nearby "projector light without ambient" to turn it on. Ensure the other lights are off.
9. Observe the boxes.

**Actual result:**
The front face of the 2nd box is not slightly darker than the two adjacent boxes when the "projector light without ambient" is enabled.

<details><summary>Actual screenshots</summary>
<p>

OSX:
<img width="1596" alt="without ambient" src="https://github.com/user-attachments/assets/afbc58e8-adc7-4304-a155-2e5813e13b50">

Win10:
![actual without amb](https://github.com/user-attachments/assets/b08250ec-007e-44d8-b199-8996a0f7f29a)

</p>
</details> 

**Expected result:**
The front face of the 2nd box should be slightly darker than the two adjacent boxes when the "projector light without ambient" is enabled.

<details><summary>Expected screenshot (provided in the test plan)</summary>
<p>

![Alpha modes 2 - projector - no ambient](https://github.com/user-attachments/assets/0e30b660-531e-4fae-b419-87dd7d178639)

</p>
</details> 

**According to** the [Environment Rendering conformity test plan](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/748323232/Environment+Rendering+conformity+test).
Test case: Alpha Modes - Set 2 - Test 3 - 1) The left 3 boxes should look almost identical but the front face of the 2nd box is slightly darker than the two adjacent boxes.

**Additional info:**
The issue is reproduced on Win10/OSX.
The issue is not reproduced on the current release viewer (Second Life Release 7.1.10.10800445603).

<details><summary>actual release 7.1.10.10800445603 screenshot</summary>
<p>

![release without ambience](https://github.com/user-attachments/assets/15b5ef99-4bb3-4b33-8efd-31f674a7d773)

</p>
</details> 

<details><summary>OSX Environment</summary>
<p>

Second Life Release 7.1.11.11074622243 (64bit)
Release Notes

You are at 244.0, 126.4, 22.8 in Bug Island 2 located at simhost-0ad04c4bcce5e167c.agni
SLURL: http://maps.secondlife.com/secondlife/Bug%20Island%202/244/126/23
(global coordinates 260596.0, 249470.0, 22.8)
Second Life Server 2024-09-13.10853867644
Release Notes

CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (2200 MHz)
Memory: 16384 MB
OS Version: macOS 12.6.0 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-4.8.101

Window size: 1598x920
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (0.3% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091638
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/16447 (0.0%)
October 04 2024 05:22:48

</p>
</details>

**Comment by Dan-Linden** [comment]
This seems related to https://github.com/secondlife/viewer/issues/2637

**Comment by Dan-Linden** [comment]
This appears fixed in build 7.1.11.11748636296.
Please test in ExtraFPS

**Comment by igorlproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.11.11750364439 (64bit) in the scope of https://github.com/secondlife/iqa/issues/381 on Win10/OSX.

Actual1 OSX: 
![Image](https://github.com/user-attachments/assets/59636660-d8a0-4750-bf97-bfafd35e967f)

Actual2 Win10:
