### ISSUE TITLE
Shadows on surfaces change incorrectly when changing the position of the sun and moon in the environment settings

### ISSUE THREAD

**Issue by valeriiaaproductengine** [secondlife/viewer#2801]
<details><summary>Environment</summary>
<p>
Second Life Release 7.1.11.11074622243 (64bit)
Release Notes

You are at 208.3, 233.9, 22.8 in Bug Island 2 located at simhost-0ad04c4bcce5e167c.agni
SLURL: http://maps.secondlife.com/secondlife/Bug%20Island%202/208/234/23
(global coordinates 260,560.0, 249,578.0, 22.8)
Second Life Server 2024-09-13.10853867644
Release Notes

CPU: 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz (2611.2 MHz)
Memory: 16111 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4957)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5612
OpenGL Version: 4.6.0 NVIDIA 556.12

Window size: 1920x1001
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (3.5% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 22/10,366 (0.2%)
October 04 2024 06:57:43

</p>
</details> 

### Reproduction steps

**Steps to reproduce:**

1. Login to Second Life Release 7.1.11.11074622243 (64bit) Viewer.
2. Teleport to http://maps.secondlife.com/secondlife/Bug%20Island%202/208/234/23 location.
3. Select World -> Environment -> My Environments.
4. From My Environments Select A-3PM setting.
5. In the "Fixed Environment" floater select the "Sun&Moon" tab.
6. Try changing the sun position by dragging the mouse a few times.

**Actual:** Shadows on surfaces change incorrectly when changing the position of the sun and moon in the environment settings.

**Expected:** Shadows on surfaces should change correctly when changing the position of the sun and moon in the environment settings.

**Additional:**
This issue is reproduced on Win10/Win11/OSX.
This issue was found during ad-hoc testing.
This issue is not reproduced on the production viewer (Second Life Release 7.1.10.10800445603).

See actual.mp4 videorecording:

https://github.com/user-attachments/assets/dbbdc268-b85b-47b0-ac36-1017fb4438ba

**Comment by AtlasLinden** [comment]
Could be due to https://github.com/secondlife/viewer/issues/2705
Retest for this issue in the next ExtraFPS build.
