### ISSUE TITLE
[ExtraFPS,  Win] Drop of FPS on some region compared to DeltaFPS

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#2875]
### Environment

CPU: AMD Ryzen 7 3800X 8-Core Processor              (3892.71 MHz)
Memory: 32682 MB
OS Version: Microsoft Windows 11 64-bit (Build 22631.4317)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.6590
OpenGL Version: 4.6.0 NVIDIA 565.90

Window size: 1659x1341
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 64m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 0
Texture memory: 8192MB
Disk cache: Max size 1638.4 MB (98.0% used)

RestrainedLove API: (disabled)
J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/2,047 (0.0%)
October 17 2024 09:50:35

### Description

Further testing and negative bias values narrowed issue down to vram, with RenderMaxVRAMBudget set 5Gb I got 20+fps on ExtraFPS.

Potentil improvements:
- adjust budget calculations to leave a bit more reserve
- 'emergency dump' vram when hitting high bias (may be not a full dump, but a partial one?)

### Reproduction steps

Visited http://maps.secondlife.com/secondlife/Wandering%20New%20York/48/175/22 with DeltaFPS viewer 7.1.10.10800445603 and experienced 30 to 50fps.
Visited same location uisng 7.1.11.11296522354 and my FPS was abismally low, 9 to 15fps.

P.S. For comparison 7.0.0.582000 got fairly stable 50fps.

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11565212741 (64bit) on Win10 in the scope of [IQA#375](https://github.com/secondlife/iqa/issues/375).
