### ISSUE TITLE
Text is temporarily small after resizing SL down, or large after resizing SL up

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#2883]
### Environment

Second Life Release 7.1.11.11074622243 (64bit)
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.91 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.5011)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.6590
OpenGL Version: 4.6.0 NVIDIA 565.90

Window size: 1587x1217
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 8192MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version:  

October 17 2024 13:06:05

### Description

Once after maximizing Second Life, then opening the Inventory (it may have been open before maximizing, not sure) all the folder names were very large. They updated to normal size after a few seconds.
Another time, I un-maximized Second Life so it because 1/4 of the screen size. The text in the Chat history window was very small and some of it looked missing. I didn't get a screenshot. That resolved after a second, but the names of the nearby people were still small as seen in the attached image: That also resolved after a couple seconds.

 ![Image](https://github.com/user-attachments/assets/89e4f6eb-6829-4e31-aa05-77e7a3be5561)

### Reproduction steps

I don't know what the exact repro is.

1. Run the 7.1.11.11074622243 ExtraFPS viewer.
2. Open and close floaters while switching Second Life between maximized and a small window size.
3. Verify the text in the floaters is always the same size.

Observed: Sometimes text in a floater will be too large after SL has been maximized. Sometimes text will be too small after SL has been restored down.

Expected: Text size should remain the same.

**Comment by kylelinden** [comment]
Suspect cause is https://github.com/secondlife/viewer/issues/2762

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11565212741 (64bit) on Win10/OSX in the scope of [IQA#375](https://github.com/secondlife/iqa/issues/375).
