### ISSUE TITLE
Water EEP setting not being acknowledged

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2889]
### Environment

ExtraFPS 7.1.11.11296522354

### Description

Water setting is not being shown in the ExtraFPS viewer. 
See below image. DeltaFPS on left vs ExtraFPS on right. Note this also occurs on the current RC of ExtraFPS 7.1.11.11074622243.

![Image](https://github.com/user-attachments/assets/28a3608f-f15d-479c-ada6-2f1de6f3c905)

### Reproduction steps

Observe water

**Comment by AtlasLinden** [comment]
![Image](https://github.com/user-attachments/assets/5d605959-753f-4c64-a315-9e0d90333bcf)

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.11.11469579464 (64bit) on Win11/OSX in the scope of [IQA #374](https://github.com/secondlife/iqa/issues/374).

In my opinion, build DeltaFPS 7.1.10.10800445603 (left part of the screenshot) lacks waves in the display of water, and build ExtraFPS 7.1.11.11296522354 (right part of the screenshot) does not display the transparency of water.

The tested build 7.1.11.11469579464 displays both waves and water transparency correctly.

See attached screenshots:
1. OSX - 7.1.11.11469579464
![Image](https://github.com/user-attachments/assets/6c5f464f-b72e-4d15-bd6e-4c3257f34d16)

2. Win11 - 7.1.11.11469579464
![Image](https://github.com/user-attachments/assets/f19b0b3d-ffc4-4a80-b5c8-b2f50cacd118)

**Comment by AtlasLinden** [comment]
Reopening this. It seems the Water Normal Map is being ignored.
In the above region TextureTest, the water should be completely clear (no waves). 
This has also been reported in a recent Canny.

**Comment by akleshchev** [comment]
> Reopening this. It seems the Water Normal Map is being ignored.

Fixed, pleasealso cover sky's exponential_scale and exponential_term during testing

**Comment by georgebproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.11.11750364439 (64bit) in the scope of https://github.com/secondlife/iqa/issues/381 on Win10/OSX.
 
 See attached screenshots:

1.OSX
![Image](https://github.com/user-attachments/assets/8c88239a-34e8-444e-a1d2-0fba0406bee6)

2.Win10
![Image](https://github.com/user-attachments/assets/ff2b022c-76bd-440a-aaf2-fb17a1442b61)
