### ISSUE TITLE
3p-SDL2 for Mac

### ISSUE THREAD

**Issue by AndrewMeadows** [secondlife/viewer#2891]
We need to hack SDL2 to NOT submit key presses to Cocoa's NSTextInputClient protocol on Mac.  This to fix #2870 

When that is done we can remove the workaround from #2890

**Comment by kylelinden** [comment]
We are not maintaining forks of 3p libs.

**Comment by brad-linden** [comment]
as discussed, the better plan in the long run is to adopt alchemy viewer's approach and use SDL windowing on mac in its entirety
