### ISSUE TITLE
Reset tone mapper default back to ACES

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2913]
### Environment

ExtraFPS

### Description

Reset default tone mapper to ACES instead of Khronos Neutral.
This also includes setting Tone Map Mix to 70% as it was previously.

### Reproduction steps

Reset graphics to default settings
Observe Tone Mapper settings  in Advanced Graphics Preferences

**Comment by igorlproductengine** [comment]
Failed QA

Verified on the Second Life Release 7.1.11.11469579464 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/374.

Currently, the "Reset to recommended settings" button does not affect the Tone Mapper settings. After manually changing both the Tone Mapper and Tone Map Mix values, applying the reset had no impact, and the settings remained unchanged.

**Comment by igorlproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11565212741 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/375.
