### ISSUE TITLE
[OSX] The "Total Rendering time" log shows "0.0000 ms" in the "SecondLife.log" file after using the "Frame Profile" option in the "Develop" menu

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#2930]
### Reproduction steps

1. Download and install the [Second Life Release 6.6.0. 571939](https://viewer-download.secondlife.com/Viewer_6/Second_Life_6_6_0_571939_x86_64.dmg) build.
2. Click "Me"→"Preferences..."→"Advanced"→check the "Show Develop Menu" checkbox.
3. Log in.
4. Click "Develop"→"Render Tests"→"Frame Profile".
5. Close the viewer.
6. In OS, navigate to the Second Life "logs" folder.
7. Open the "SecondLife.log" file.
8. Find the "Total Rendering time" log.
9. Observe the time data.

**Actual result:**
The "Total Rendering time" log shows "0.0000 ms" in the "SecondLife.log" file after using the "Frame Profile" option in the "Develop" menu.

**Expected result:**
The "Total Rendering time" log should show an actual result in the "SecondLife.log" file after using the "Frame Profile" option in the "Develop" menu.

**Note:**
This issue is reproduced on OSX only.

According to the [Viewer performance spot check](https://lindenlab.atlassian.net/wiki/x/AYCtww).
Step: Record the number in the "Total render time" tab of the spreadsheet Performance Tests.

This issue is **not** reproduced on the current production build Second Life Release 7.1.10.10800445603.

**SecondLife.log**
[SecondLife.log](https://github.com/user-attachments/files/17508567/SecondLife.log)

<details><summary>Environment</summary>
<p>
Second Life Release 6.6.0.571939 (64bit)
Release Notes

You are at 3.5, 128.2, 85.3 in LagLand located at simhost-039ac35d0127be4e0.agni
SLURL: http://maps.secondlife.com/secondlife/LagLand/3/128/85
(global coordinates 260099.0, 248192.0, 85.3)
Second Life Server 2024-10-15.11356152186
Release Notes

CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (2300 MHz)
Memory: 8192 MB
OS Version: Mac OS X 10.16.0 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Sun Dec 17 22:18:09 PST 2023; root:xnu-8796.141.3.703.2~2/RELEASE_X86_64 x86_64
Graphics Card Vendor: Intel Inc.
Graphics Card: Intel(R) Iris(TM) Plus Graphics 640

OpenGL Version: 2.1 INTEL-20.6.4

Window size: 2880x1570
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 3
Advanced Lighting Model: Enabled
Texture memory: 512MB
Disk cache: Max size 204.0 MB (18.2% used)
HiDPI display mode: 1

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.03
Dullahan: 1.12.3.202111032211
  CEF: 91.1.21+g9dd45fe+chromium-91.0.4472.114
  Chromium: 91.0.4472.114
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327

Packets Lost: 0/332 (0.0%)
October 24 2024 07:12:22
</p>
</details>

**Comment by Dan-Linden** [comment]
It's working in recent Mac viewers, so this was fixed at some point. Closed.
