### ISSUE TITLE
Nearby Chat strip to toolbar

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2953]
Add the ability to chat to Nearby Chat directly from the toolbar.

## Test Plan

TBD

**Comment by akleshchev** [comment]
Something like a floating text edit when mouse is hoverin over chat button?

**Comment by AtlasLinden** [comment]
How it is displayed in FS:
![Image](https://github.com/user-attachments/assets/9d7e81ba-cc58-4417-bbb9-7b3b76d4fa6a)

**Comment by AtlasLinden** [comment]
Closing this as a duplicate of an already imported feature request from Canny: https://github.com/secondlife/viewer/issues/2779
