### ISSUE TITLE
"Debug Avatar Textures" menu option usually does nothing.

### ISSUE THREAD

**Issue by mercurylinden** [secondlife/viewer#2968]
### Environment

Second Life Release 7.1.11.11296522354 (64bit)
Release Notes

You are at 209.5, 132.6, 23.0 in MercuryZone located at simhost-0ceee664fb3ee5231.aditi
SLURL: secondlife://Aditi/secondlife/MercuryZone/210/133/23
(global coordinates 132,049.0, 235,397.0, 23.0)
Barbecue 2024-10-25.11524490658
Release Notes

CPU: Intel(R) Core(TM) Ultra 7 155H (2995.2 MHz)
Memory: 32213 MB
OS Version: Microsoft Windows 11 64-bit (Build 22631.4317)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.6081
OpenGL Version: 4.6.0 NVIDIA 560.81

Window size: 3171x1920
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 10000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 8188MB
Disk cache: Max size 3993.6 MB (56.2% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 33/2,959 (1.1%)
October 28 2024 13:55:56

### Description

I'm unable to get "Debug Avatar Textures" to work. Maestro said it worked for him once, but was unable to get it to work again.

### Reproduction steps

1. Set your avatar to God mode (Develop -> Request Admin Status)
2. Select Develop -> Avatar -> Debug Avatar Textures

Result:
Nothing happens

Expected:
A UI with all the avatar textures that go into the final bakes shows up.

Notes:
Nothing appears in the viewer logs or in Hippolizer when the menu option is selected, so its hard to tell if it is even attempting to do anything.

**Comment by maestrolinden** [comment]
In case it helps, I was able to get this floater to load _once_ in the Second Life Release 7.1.10.10800445603 (64bit) viewer, on Mac.  After attempting to open the float while not in god mode (which failed), I entered god mode and got it to appear, like so:
![Image](https://github.com/user-attachments/assets/b6ffc0cd-31c9-4f95-a1a2-6e0487d6eb2d)

However, I was unable to open the floater in a subsequent session, even when wearing the same outfit after trying the same exact steps.  I have no idea why it's failing - faulty logic in the "is user in god mode" check?

**Comment by kylelinden** [comment]
Some godmode features only work after you teleport out of the region you "godded up" in. Caps refresh issue or something, pretty sure there was an old Jira about it but the workaround is always teleport away and try again. If that does not work the issue may be getting worse.

**Comment by mercurylinden** [comment]
Teleporting didn't work for me.

**Comment by mercurylinden** [comment]
Turns out you have to have your avatar selected for this to work. Best way to activate this is to right-click your avatar and select Debug Textures. Closing this issue.
