### ISSUE TITLE
"Total render time" is inaccurate on Radeon HD 2600 XT

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#2979]
### Environment

7.1.11.11565212741

CPU: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (3092.98 MHz)
Memory: 4061 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.3693)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: ATI Radeon HD 2600 XT

Windows Graphics Driver Version: 8.970.100.9001
OpenGL Version: 3.3.11672 Core Profile Context

Window size: 1920x1017

### Description

See cell K24 in https://docs.google.com/spreadsheets/d/1d6_5j_XceN9nIa2iFIcUJW8aBALdvI4uuCglcKIxiZ0/edit?gid=1393362928#gid=1393362928

Note from PE:
5 measurements were made - all of them showed the value 9223372013568. In my opinion - this is simply the largest possible value for calculation.
As an example, I provide a line of the log with this value:
2024-10-30T13:27:52Z INFO # llrender/llglslshader.cpp(150) LLGLSLShader::finishProfile : Total rendering time: 9223372013568.0000 ms

### Reproduction steps

1. Install build 7.1.11.11565212741 on the hardware listed above
2. Run the "Location 1 - LagLand" section of test https://lindenlab.atlassian.net/wiki/spaces/QA/pages/3282927617/Viewer+performance+spot+check at LagLand region
3. Develop menu->Render Tests->Frame Profile
4. Open the SecondLife.log
5. Find "Total rendering time:"

Observed: Total rendering time: 9223372013568

**Comment by kylelinden** [comment]
Cannot solve for GPU driver issues.
