### ISSUE TITLE
PBR Terrain not loading upon quick teleport

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#2991]
<details>
<summary>Environment</summary>

Both DeltaFPS (7.1.10.10800445603) and ExtraFPS (7.1.11.11565212741)

You are at 121.0, 110.0, 23.2 in Pasta Cake located at simhost-054bc31cb9bd66326.agni
SLURL: http://maps.secondlife.com/secondlife/Pasta%20Cake/121/110/23
(global coordinates 332,153.0, 305,518.0, 23.2)
Second Life Server 2024-10-15.11356152186
Release Notes

CPU: 12th Gen Intel(R) Core(TM) i9-12900HK (2918.4 MHz)
Memory: 32440 MB
OS Version: Microsoft Windows 11 64-bit (Build 26100.2033)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5612
OpenGL Version: 4.6.0 NVIDIA 556.12

Window size: 2560x1369
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/1,137 (0.0%)
October 31 2024 13:26:50

</details>

### Description

Teleporting from one region using PBR terrain to another and back can cause the terrain to be blank.
https://gyazo.com/31387d846252b01cc48440da443cdac9

Currently this has only reproduced on Atlas Lindens machine.
TPing into a non-PBR Terrain region and back will revert the issue.

### Reproduction steps

1. Login to PBR Terrain region
2. TP to another region using PBR terrain
3. TP back to original location

**Comment by cosmic-linden** [comment]
I got lucky and was able to reproduce this.

**Comment by valeriiaaproductengine** [comment]
This issue keeps reproducing - see screen recording:

https://github.com/user-attachments/assets/3b36397f-d1df-4280-93ae-0846334f4de1

Verified on the Second Life Release 7.1.11.11982653819 (64bit) in the scope of https://github.com/secondlife/iqa/issues/395 on Win10.

**Comment by georgebproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.12041172537 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/401.
