### ISSUE TITLE
Chat logging with AM-PM time format created in build 7.1.12.11386494836 is not displayed quite correctly in the current release 7.1.10.10800445603 viewer

### ISSUE THREAD

**Issue by DmitrySProductengine** [secondlife/viewer#3039]
### Environment

<details><summary>Environment</summary>
<p>

Second Life Release 7.1.10.10800445603 (64bit)
Release Notes

You are at 136.0, 116.1, 22.9 in Product Engine 3 located at simhost-06b407db4579a48da.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%203/136/116/23
(global coordinates 336776.0, 307060.0, 22.9)
Second Life Server 2024-10-15.11356152186
Release Notes

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2600 MHz)
Memory: 16384 MB
OS Version: macOS 15.0.1 Darwin 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:30 PDT 2024; root:xnu-11215.1.12~1/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-6.1.13

Window size: 1073x1001
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (30.1% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091638
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/1779 (0.0%)
November 07 2024 06:54:54

</p>
</details> 

### Reproduction steps

1. Download and install the Second Life 7.1.12.11386494836 viewer (https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%230ef7a9b-maint-c-2024-10-17).
2. Launch 2 viewer instances and log in as users A and B.
3. User A and User B: open the preferences and select the time format 1:00 AM (re-enter the viewer if necessary).
4. User A: send some messages to User B via IM, group chat, and Nearby chat.
5. User B: reply to user A in all chats.
6. User A and User B: exit the viewer and log in to the current release 7.1.10.10800445603 build.
7. User A and User B: observe all conversation logs.

**Actual result:**
Chat logging with AM-PM time format created in build 7.1.12.11386494836 is not displayed quite correctly in the current release 7.1.10.10800445603 viewer.

**Expected result:**
Chat logging with AM-PM time format created in build 7.1.12.11386494836 should displayed correctly in the current release 7.1.10.10800445603 viewer.

**Additional information:**
This issue was found during Ad hoc testing in the scope of [IQA #368](https://github.com/secondlife/iqa/issues/368).
This issue is reproduced on Win10, Win11, and OSX.

This issue is reproduced on the current release 7.1.10.10800445603 build.

In my opinion, it is no longer possible to change the current release build and perhaps this behavior will remain a "known issue" or "expected behavior" until these new time formats in logging are released. But maybe something can be done for better compatibility...

In the build 7.1.12.11386494836, support for switching to different time formats in chat logging works correctly. Regardless of the time format option, the time in the chat logs is displayed in the format in which it was configured.

Example of a chat log with different time formats (in this example, logs with the AM format are not displayed correctly in the current release build):
1. [dmitrys_productengine.txt](https://github.com/user-attachments/files/17663485/dmitrys_productengine.txt)

See attached screenshots:
1. Actual - OSX - 7.1.10.10800445603:
![Image](https://github.com/user-attachments/assets/c8335141-ca74-4f6c-a801-e6fac2e8e64f)

2. Expected - OSX - 7.1.12.11386494836:
![Image](https://github.com/user-attachments/assets/622d8d96-7cca-45f1-b92b-f7025c195b76)

3. Actual - Win11 - 7.1.10.10800445603:
![Image](https://github.com/user-attachments/assets/883239a1-0124-4110-911e-0220872d43f5)

4. Expected - Win11 - 7.1.12.11386494836:
![Image](https://github.com/user-attachments/assets/b71ed444-196c-4e50-8664-b351f74de2b3)

**Comment by AtlasLinden** [comment]
This will only affect users that can access the setting in a later build and then going back to a previous build.
Closing as Won't Fix.
