### ISSUE TITLE
Second Life Release 7.1.11.11565212741 (64bit) Beach Balled on Apple M3 Pro

### ISSUE THREAD

**Issue by calebrosia** [secondlife/viewer#3053]
### Environment

Second Life Release 7.1.11.11565212741 (64bit)
Release Notes

You are at 41.8, 216.4, 1214.3 in Moolmangcho located at simhost-0e663eee0f86b95c7.agni
SLURL: http://maps.secondlife.com/secondlife/Moolmangcho/42/216/1214
(global coordinates 262954.0, 236248.0, 1214.3)
Second Life Server 2024-10-15.11356152186
Release Notes

CPU: Apple M3 Pro (2400 MHz)
Memory: 18432 MB
OS Version: macOS 15.1.0 Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:00:32 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6030 x86_64
Graphics Card Vendor: Apple
Graphics Card: Apple M3 Pro

OpenGL Version: 4.1 Metal - 89.3

Window size: 1801x1084
Font Size Adjustment: 96pt
UI Scaling: 1.225
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 12288MB
Disk cache: Max size 1638.4 MB (38.3% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091638
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 19/18083 (0.1%)
November 07 2024 10:54:06

### Description

SL Corp meeting teleported to SLURL: http://maps.secondlife.com/secondlife/Moolmangcho/42/216/1214 to try out the npc bot there. 
The viewer on the secondary monitor from my laptop started freezing up and the beachball appears.
![Image](https://github.com/user-attachments/assets/8d6a4845-8482-4b34-9b13-87d4a3e98207)
![Image](https://github.com/user-attachments/assets/fdc8d55f-dade-4fc5-8822-9632ad9accca)
![Image](https://github.com/user-attachments/assets/039e464a-6583-43b4-86ee-f6bd65afcd95)
![Image](https://github.com/user-attachments/assets/2265b23f-3878-435d-9371-9117200a336d)

I recorded the viewer log and activity monitor for more data points

### Reproduction steps

1. Login inworld
2. Go to a region where there may be some activity (multiple agents nearby, 3 agents or more, nearby chatting etc.)
3. Viewer starts freezing up (maybe within 5 min)
[Beachball.log](https://github.com/user-attachments/files/17669761/Beachball.log)

**Comment by calebrosia** [comment]
I was able to beach ball with only one avatar as well. I think this time it was because the viewer may be not in focus for a period

**Comment by akleshchev** [comment]
Log snippet:
```
2024-11-08T00:07:23Z INFO # newview/llviewertexture.cpp(587) LLViewerTexture::updateClass : Viewer is no longer backgrounded, resuming normal texture usage.
2024-11-08T00:07:27Z INFO # llcommon/llapp.cpp(374) setStatus : status: error
2024-11-08T00:07:27Z INFO #CoProcMgr# llmessage/llcoproceduremanager.cpp(320) operator() : Pool Upload closing queue because status 'error'
```
Look like this happens when viewer was out of focus than focused back?

**Comment by calebrosia** [comment]
No longer reproduces on Second Life Release 7.1.11.11750364439 (64bit)

**Comment by Dan-Linden** [comment]
Please test on the newest Macs available.
