### ISSUE TITLE
PBR hair fighting itself

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#3059]
### Environment

ExtraFPS: Second Life Release 7.1.11.11565212741 
&
DeltaFPS: Second Life Release 7.1.10.10800445603

### Description

Test object is in the contents of "viewer#3059" at http://maps.secondlife.com/secondlife/Danger!%20Danger!/74/80/39

This hair appears correct when rezzed. 
![Image](https://github.com/user-attachments/assets/29136139-c16b-4f76-9706-a005b46418f0)

However, when worn appears as such: https://gyazo.com/0ce851ae3964184240777ae0327ea19e

This issue doesn't reproduce on the Atlasaurus build: 7.1.9.10515727195
![Image](https://github.com/user-attachments/assets/ecfc049b-9064-4c8b-bfbf-307f2b303dcb)

### Reproduction steps

Wear the hair mentioned. Location TBD

**Comment by Geenz** [comment]
To test this:
* Attach PBR hair or semi-transparent PBR rigged content that has multiple meshes that are toggled on or off for different states- for example the hair in this issue
* If the hair seems to have any sort of "Z-fighting" style effects, then QA fail
* If the hair does not have any sort of "Z-fighting" style effects, then QA pass

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11864501455 (64bit) on Win10/OSX in the scope of [IQA#386](https://github.com/secondlife/iqa/issues/386).
