### ISSUE TITLE
World Map tiles are blurry

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#3093]
### Environment

Second Life Test 7.1.12.11839252315 (64bit)
Release Notes

You are at 66.4, 40.3, 38.5 in Danger! Danger! located at simhost-015e4d5d77a758e42.agni
SLURL: http://maps.secondlife.com/secondlife/Danger%21%20Danger%21/66/40/39
(global coordinates 261,186.0, 249,640.0, 38.5)
Second Life Server 2024-10-15.11356152186
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.5011)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.6590
OpenGL Version: 4.6.0 NVIDIA 565.90

Window size: 1732x1234
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 8192MB
Disk cache: Max size 1638.4 MB (16.1% used)

RestrainedLove API: (disabled)
J2C Decoder Version: KDU v8.4.1
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 3/5,183 (0.1%)
November 14 2024 13:17:36

### Description

Many of the map tiles are blurry and never appear sharp.
![Image](https://github.com/user-attachments/assets/0855eb23-d8b0-4c14-8e55-e838b18e30b7)

### Reproduction steps

1. Log in with develop build 7.1.12.11839252315 on Windows or Mac - https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23a0e5e23
2. Open the World Map

Observed: Many of the map tiles are blurry and never appear sharp.

Expected: Clear map tiles, and quickly.

Notes: This does not reproduce on DeltaFPS Release or ExtraFPS RC.

**Comment by Dan-Linden** [comment]
Indeed.
Seen on ExtraFPS 7.1.11.11864501455 (64bit)

<details>
<summary>Environment</summary>
Second Life Release 7.1.11.11864501455 (64bit)
Release Notes

You are at 122.9, 90.9, 21.6 in By Design located at simhost-01d3500f306966b31.agni
SLURL: http://maps.secondlife.com/secondlife/By%20Design/123/91/22
(global coordinates 261,499.0, 246,875.0, 21.6)
Second Life Preflight 2024-10-19.11413863173
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.5011)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.6590
OpenGL Version: 4.6.0 NVIDIA 565.90

Window size: 1732x1234
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 8192MB
Disk cache: Max size 1638.4 MB (12.1% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 2/14,749 (0.0%)
November 15 2024 16:08:57</details>

**Comment by igorlproductengine** [comment]
During testing of Second Life Release 7.1.11.11864501455 (64bit) on Windows and macOS, the following issues were identified:

1. Blurry Textures: Textures located at the edges of the camera's field of view remain blurry until the camera is directly focused on them. After concentrating, the textures become sharp.
2. Missing Neighboring Regions on Mini-Map: Neighboring regions do not appear on the mini-map, even though they are present in the virtual world.

![Image](https://github.com/user-attachments/assets/4893a8c1-efbc-4565-876f-970b57458722)

**Comment by valeriiaaproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11982653819 (64bit) in the scope of https://github.com/secondlife/iqa/issues/395 on Win10/OSX.
