### ISSUE TITLE
Outfit Gallery images do not load

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#3104]
<details>
<summary>Environment</summary>
Second Life Release 7.1.11.11750364439 (64bit)

Release Notes

You are at 118.0, 95.7, 21.8 in By Design located at simhost-01d3500f306966b31.agni

SLURL: http://maps.secondlife.com/secondlife/By%20Design/118/96/22

(global coordinates 261494.0, 246880.0, 21.8)

Second Life Preflight 2024-10-19.11413863173

Release Notes

CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (2800 MHz)

Memory: 16384 MB

OS Version: macOS 11.7.10 Darwin 20.6.0 Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64 x86_64

Graphics Card Vendor: Intel Inc.

Graphics Card: Intel Iris Pro OpenGL Engine

OpenGL Version: 4.1 INTEL-16.5.14

Window size: 1280x800

Font Size Adjustment: 96pt

UI Scaling: 1

Draw distance: 96m

Bandwidth: 3000kbit/s

LOD factor: 1.125

Render quality: 1

Texture memory: 1536MB

Disk cache: Max size 819.2 MB (100.0% used)

HiDPI display mode:

J2C Decoder Version: KDU v7.10.4

Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft

Dullahan: 1.14.0.202408091638

  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54

  Chromium: 118.0.5993.54

LibVLC Version: 3.0.21

Voice Server Version: Secondlife WebRTC Gateway

Packets Lost: 87/65023 (0.1%)

November 18 2024 11:13:56
</details>

### Description

Outfit Gallery images do not load on Kyle Linden's ole Mac.

### Reproduction steps

1. Install https://releasenotes.secondlife.com/viewer/7.1.11.11750364439.html on an old Mac
2. Log in and open Avatar > My Outfits, then Outfit Gallery.

Observed: 
![Image](https://github.com/user-attachments/assets/cfbd209b-b49d-4dd4-93cb-da4079e724ad)

Expected: The images should load.

Log file: [SecondLife_gray_outfits.log](https://github.com/user-attachments/files/17805400/SecondLife_gray_outfits.log)

**Comment by kylelinden** [comment]
Kyle try to repro on DeltaFPS and update here.

**Comment by AtlasLinden** [comment]
See also: https://github.com/secondlife/viewer/issues/2401 which was fixed in DeltaFPS

**Comment by cosmic-linden** [comment]
I have a Windows machine, but maybe this isn't a Mac-specific issue. I will see if I can find any leads.

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11982653819 (64bit) on Win10/OSX in the scope of [IQA#395](https://github.com/secondlife/iqa/issues/395).

**Also**, an image is not shown in the "Change Folder Image" floater after assigning an image to the outfit folder in the "Outfit Gallery" tab of the "Outfits" floater (see [secondlife/viewer/issues/3147](https://github.com/secondlife/viewer/issues/3147)).
