### ISSUE TITLE
The viewer does not fully load all textures on the Intel HD Graphics 610 video card

### ISSUE THREAD

**Issue by DmitrySProductengine** [secondlife/viewer#3106]
### Environment
<details><summary>Environment</summary>
<p>

Second Life Release 7.1.11.11864501455 (64bit)
Release Notes

You are at 3.7, 127.9, 85.3 in LagLand located at simhost-07a82ae0a96565d36.agni
SLURL: http://maps.secondlife.com/secondlife/LagLand/4/128/85
(global coordinates 260,100.0, 248,192.0, 85.3)
Second Life Server 2024-10-15.11356152186
Release Notes

CPU: Intel(R) Celeron(R) CPU G3930 @ 2.90GHz (2904.01 MHz)
Memory: 3522 MB
OS Version: Microsoft Windows 11 64-bit (Build 22631.4460)
Graphics Card Vendor: Intel
Graphics Card: Intel(R) HD Graphics 610

Windows Graphics Driver Version: 31.0.101.2128
OpenGL Version: 4.6.0 - Build 31.0.101.2128

Window size: 1920x1009
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 96m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 1584MB
Disk cache: Max size 1638.4 MB (9.2% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: Undefined
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/1,357 (0.0%)
November 19 2024 02:47:03

</p>
</details> 

### Reproduction steps

1. Download and install the Second Life 7.1.11.11864501455 viewer (https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23c654dac-ExtraFPS).
2. Log in to the viewer on a computer with an Intel HD Graphics 610 video card.
3. Teleport to a region with many textures (for example: LagLand - http://maps.secondlife.com/secondlife/LagLand/4/128/85).
4. Wait some time for the textures to load.
5. Observe the loaded textures.

**Actual result:**
The viewer does not fully load all textures on the Intel HD Graphics 610 video card.

**Expected result:**
The viewer should fully load all textures on the Intel HD Graphics 610 video card.

**Additional information:**
This issue was found during Ad hoc testing in the scope of [IQA #387](https://github.com/secondlife/iqa/issues/387).
This issue is reproduced on Win11 (at the moment it is possible to check this behavior only on Win11, but with a high degree of probability this behavior will also be reproduced on Win10).

This issue is not reproduced on the current release 7.1.10.10800445603 build.

Textures are not loaded completely randomly (for example, I provided 2 screenshots from one location).
This behavior is also repro in a location with 20 bots but is slightly less noticeable (an example screenshot is also attached).

Long waiting times had no effect (the texture displays did not change after waiting for loading for more than 20 minutes).

This behavior was not reproduced on our Macs (although there are laptops with Intel video cards) or on this build on Win10/11 with ATI and Nvidia video cards.
Also, this behavior was not reproduced on the Intel(R) Iris(R) Xe Graphics video card.

See attached screenshots and logs:
1. Actual - LagLand - 7.11.11864501455
![Image](https://github.com/user-attachments/assets/8510411a-4899-432d-aa64-22b907c4a389)

2. Actual 2 - LagLand - 7.1.11864501455
![Image](https://github.com/user-attachments/assets/097b9b80-4d2e-4d5f-8339-e80f8d389afa)
[SecondLife_LagLand_7.1.11.11864501455.log](https://github.com/user-attachments/files/17815416/SecondLife_LagLand_7.1.11.11864501455.log)

3. Expected - LagLand - current 7.1.10.10800445603 release
![Image](https://github.com/user-attachments/assets/b72754cb-e1b2-4f5f-823e-0b85b7acd3b2)
[SecondLife_LagLand_7.1.10.10800445603.log](https://github.com/user-attachments/files/17815441/SecondLife_LagLand_7.1.10.10800445603.log)

4. Actual - Lag Me 5 - 7.1.11.11864501455
![Image](https://github.com/user-attachments/assets/065ddefe-120e-4930-adff-008ef60fc856)
[SecondLife_Lag Me 5_7.1.11.11864501455.log](https://github.com/user-attachments/files/17815446/SecondLife_Lag.Me.5_7.1.11.11864501455.log)

5. Expected - Lag Me 5 - current 7.1.10.10800445603 release
![Image](https://github.com/user-attachments/assets/228e0a6f-8e57-485c-97df-3e6c2c544ae5)
[SecondLife_Lag Me 5_7.1.10.10800445603.log](https://github.com/user-attachments/files/17815452/SecondLife_Lag.Me.5_7.1.10.10800445603.log)

**Comment by Dan-Linden** [comment]
Marked as showstopper for now, but need to know how many users this will affect.

**Comment by DmitrySProductengine** [comment]
**Additional investigation:**

We investigated additional on our computer with an Intel UHD 630 video card.
This behavior was not reproduced, although the video cards have similar characteristics.
After this test, I replaced the 4GB memory module (on the computer with an Intel HD 610 video card) with 16 GB and retested the bug.
In this configuration, the behavior was also not reproduced.

Results of re-testing (in all cases, 512 MB was allocated to the integrated graphics card in the motherboard BIOS settings):
1. 7.1.11.11864501455 build; 16 GB of RAM - the Viewer: memory 15810MB; texture memory 7253MB; Est.free 4642MB; Bias 1.  Windows task manager: Shared GPU memory usage 1.4 GB
2. 7.1.11.11864501455 build; 4 GB of RAM - the Viewer: memory 3522MB; texture memory 1584MB; Est.free -76MB; Bias 5.  Windows task manager: Shared GPU memory usage 1.3 GB
3. 7.1.10.10800445603 build, 4 GB of RAM - the Viewer: memory 3522MB; texture memory 1584MB; Est.free 555MB; Bias 4 (varies from 1 to 4).  Windows task manager: Shared GPU memory usage 1.1 GB.

The behavior looks like the new build defines free video memory worse for integrated video cards (which use additional RAM for themselves), also the use of video memory is slightly increased and this leads to the fact that it evaluates free video memory as "-", texture optimization (bias) starts and it does not finish, because the video memory is not released.

Most likely, this behavior will be relevant for integrated Intel video cards on computers with a small amount of RAM (4 GB).
At the moment, there is no way to test this behavior with 8 GB of RAM, but perhaps it will also be enough to display textures fully.

See the attached screenshots and log:
<details><summary>1. Expected - LagLand - 7.11.11864501455 - Win10 - 32GB Ram - Intel UHD 630</summary>
<p>

![Image](https://github.com/user-attachments/assets/9d831c79-0b50-4624-9840-f59ca7996881)

</p>
</details> 

<details><summary>2. Expected - LagLand - 7.11.11864501455 - Win11 - 16GB Ram - Intel HD 610</summary>
<p>

![Image](https://github.com/user-attachments/assets/3e182078-68df-4d23-8758-543ed61058db)

</p>
</details> 

<details><summary>3. Expected - LagLand - 7.11.11864501455 - Win11 - 16GB Ram - Intel HD 610 - screenshot 2</summary>
<p>

![Image](https://github.com/user-attachments/assets/8acc5981-39e8-4cb7-9f36-7b97c05c6098)

</p>
</details> 

4. [SecondLife_LagLand_16GB_7.1.11.11864501455.log](https://github.com/user-attachments/files/17845901/SecondLife_LagLand_16GB_7.1.11.11864501455.log)

<details><summary>5. Actual - LagLand - 7.11.11864501455 - Win11 - 4GB Ram - Intel HD 610</summary>
<p>

![Image](https://github.com/user-attachments/assets/d497f88d-414f-47e3-b847-d1681ec850ed)

</p>
</details> 

<details><summary>6. Expected - LagLand - 7.1.10.10800445603 - Win11 - 4GB Ram - Intel HD 610</summary>
<p>

![Image](https://github.com/user-attachments/assets/75c8de37-a72a-4a83-9474-ba8a13e6b685)

</p>
</details>

**Comment by kylelinden** [comment]
Need Frame rate details on 4GB system

**Comment by DmitrySProductengine** [comment]
This issue is still reproduced on the Second Life Release 7.1.11.11982653819 (64bit) build.
Tested on Win11 with 4GB RAM in the scope of [IQA #395](https://github.com/secondlife/iqa/issues/395).
FPS measurements were also taken on different builds:
1. current release 7.1.10.10800445603 build - FPS ~12.2.
2. 7.1.11.11864501455 build - FPS ~11.4.
3. 7.1.11.11982653819 build - FPS ~11.4.

When creating a screenshot using the 'Snipping tool' application on Windows, the FPS value recorded in the screenshot decreased slightly.
See the attached screenshots:
<details><summary>1. 7.1.10.10800445603 build - FPS
</summary>
<p>

![Image](https://github.com/user-attachments/assets/b0924307-6969-47bb-b600-1f35cb8b04c1)

</p>
</details> 

<details><summary>2. 7.1.11.11864501455 build - FPS</summary>
<p>

![Image](https://github.com/user-attachments/assets/76cd6d5c-4a88-4476-bef0-576cf9a14ab7)

</p>
</details> 

<details><summary>3. 7.1.11.11982653819 build - FPS</summary>
<p>

![Image](https://github.com/user-attachments/assets/27510e6b-9c63-4d6d-870c-125390877e77)

</p>
</details>

**Comment by Dan-Linden** [comment]
QA, please compare framerate again with the newest build.

**Comment by DmitrySProductengine** [comment]
This issue is still reproduced on Second Life Release 7.1.11.12041172537 (64bit) build.
Tested on Win11 with 4GB RAM in the scope of [IQA #401](https://github.com/secondlife/iqa/issues/401).
FPS measurement:
1. 7.1.11.12041172537 build - FPS ~11.5.

Now, I have created a screenshot using the "PrintScreen" function - in this case, there is no small drop in FPS, as was the case with the previous screenshots.
See the attached screenshot:
<details><summary>1. 7.1.11.12041172537 build - FPS</summary>
<p>

![Image](https://github.com/user-attachments/assets/99819922-908b-4477-bfcb-5f128cc0053f)


</p>
</details>

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.11.12325002554 (64bit) on Win11 in the scope of [IQA #418](https://github.com/secondlife/iqa/issues/418).
See the attached screenshot:
![Image](https://github.com/user-attachments/assets/a736af97-3fc6-4499-9301-be9ba9e40e88)
