### ISSUE TITLE
No ambient light on HD Graphics 4400

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#3118]
### Environment

Second Life Release 7.1.11.11923406699 (64bit)
Release Notes

You are at 107.0, 14.0, 22.8 in Bug Island 2 located at simhost-06a12f8f4413ce859.agni
SLURL: http://maps.secondlife.com/secondlife/Bug%20Island%202/107/14/23
(global coordinates 260,459.0, 249,358.0, 22.8)
Second Life Server 2024-10-15.11356152186
Release Notes

CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (2394.46 MHz)
Memory: 8076 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.5131)
Graphics Card Vendor: Intel
Graphics Card: Intel(R) HD Graphics 4400

Windows Graphics Driver Version: 10.18.15.4268
OpenGL Version: 4.3.0 - Build 10.18.15.4268

Window size: 1366x705
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 96m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 2048MB
Disk cache: Max size 1638.4 MB (0.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/1,127 (0.0%)
November 20 2024 14:16:34

### Description

Ambient light in the environment is not being rendered.
![Image](https://github.com/user-attachments/assets/82823dc3-8401-4fcf-81e9-0d19483d0fa5)

### Reproduction steps

1. Log into new ExtraFPS build on a HD Graphics 4400 card (https://github.com/secondlife/viewer/actions/runs/11923406699)
2. Go to http://maps.secondlife.com/secondlife/Bug%20Island%202/107/14/23 and look at the wall of textures to the South

Observed: The wall is black.

Expected: The wall textures should be visible because the environment has ambient light.

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.11.12041172537 (64bit) on Win10 in the scope of [IQA #401](https://github.com/secondlife/iqa/issues/401).
See the attached screenshot:
1. Expected - 7.1.11.12041172537
![Image](https://github.com/user-attachments/assets/cfcc62c2-d234-4155-8c7f-84399c7d96ca)
