### ISSUE TITLE
An image is not shown in the "Change Folder Image" floater after assigning an image to the outfit folder in the "Outfit Gallery" tab of the "Outfits" floater

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#3147]
### Reproduction steps:
1. Download and install the [Second Life Release 7.1.11.11982653819 (64bit)](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b7924f7-ExtraFPS) build.
2. Log in.
3. Click the "Outfits -- Change your avatar" toolbar button.
4. Click "Save as..." to create a new outfit.
5. Right-click on an outfit folder and choose "Image...".
6. Apply an image to an outfit folder.
7. Observe the "Change Folder Image" floater's image.

**Actual result:**
An image is not shown in the "Change Folder Image" floater after assigning an image to the outfit folder in the "Outfit Gallery" tab of the "Outfits" floater.

**Expected result:**
An image should be shown in the "Change Folder Image" floater after assigning an image to the outfit folder in the "Outfit Gallery" tab of the "Outfits" floater.

**Note:**
This issue is reproduced on Win10/OSX.

This issue was found during ad-hoc testing of [secondlife/viewer/issues/3104](https://github.com/secondlife/viewer/issues/3104).

**Also**, this issue is reproduced using the next options in the "Change Folder Image" floater:
- Upload from computer;
- Use snapshot tool;
- Choose texture.

This issue is reproduced **from time to time**.

This issue is **reproduced** on the current production build Second Life Release 7.1.10.10800445603.

**actual.png**
![Image](https://github.com/user-attachments/assets/a5d3c30e-5eba-406a-a3cc-ee1ca7c042ac)

**expected.png**
![Image](https://github.com/user-attachments/assets/33600910-e1d4-41da-8480-53a051817dd8)

<details><summary>Environment</summary>
<p>
Second Life Release 7.1.11.11982653819 (64bit)
Release Notes

You are at 213.5, 106.6, 21.5 in Product Engine located at simhost-031171905e72e3e76.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/214/107/22
(global coordinates 336,854.0, 307,307.0, 21.5)
Second Life Server 2024-10-15.11356152186
Release Notes

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3696 MHz)
Memory: 32688 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.5131)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT

Windows Graphics Driver Version: 32.0.12019.1028
OpenGL Version: 4.6.0 Core Profile Context 24.10.1.241007

Window size: 1920x1017
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 4029MB
Disk cache: Max size 1638.4 MB (0.3% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 12/16,652 (0.1%)
November 25 2024 06:33:28
</p>
</details>

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.12150664210 on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/404.
