### ISSUE TITLE
Intel HD Graphics 4400 defaults to Low+ instead of Low

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#3165]
### Environment

Second Life Release 7.1.11.12041172537 (64bit)
Release Notes

You are at 214.0, 28.3, 23.2 in TextureTest located at simhost-0ed1af4f6c09b0a7a.agni
SLURL: http://maps.secondlife.com/secondlife/TextureTest/214/28/23
(global coordinates 260,054.0, 248,860.0, 23.2)
Second Life Preflight 2024-10-19.11413863173
Release Notes

CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (2394.46 MHz)
Memory: 8076 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.5198)
Graphics Card Vendor: Intel
Graphics Card: Intel(R) HD Graphics 4400

Windows Graphics Driver Version: 10.18.15.4268
OpenGL Version: 4.3.0 - Build 10.18.15.4268

Window size: 1366x705
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 96m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 2048MB
Disk cache: Max size 1638.4 MB (0.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/1,414 (0.0%)
November 26 2024 21:31:58

### Description

OpenGL Version: 4.3.0 and Windows, should default to Low graphics quality.

### Reproduction steps

1. On a machine with old video card, OpenGL Version: 4.3.0,
2. Delete SL settings.
3. Log in with ExtraFPS viewer, https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23a90377d-ExtraFPS
4. Verify the graphics quality is set to Low

Observed: The Graphics quality is set to Low+

Attached log: [SecondLife.log](https://github.com/user-attachments/files/17929632/SecondLife.log)

**Comment by kylelinden** [comment]
Expected for this GPU to be set to Low+
