### ISSUE TITLE
The viewer, launched on video cards with OpenGL version lower than 4.6 for Windows and lower than 4.1 on OSX, has default graphics settings as Low+ and does not enable the "Vintage mode" option

### ISSUE THREAD

**Issue by DmitrySProductengine** [secondlife/viewer#3167]
### Environment
<details><summary>Environment</summary>
<p>

Second Life Release 7.1.11.12041172537 (64bit)
Release Notes

You are at 3.7, 127.9, 85.2 in LagLand located at simhost-05da026bb483ed43b.agni
SLURL: http://maps.secondlife.com/secondlife/LagLand/4/128/85
(global coordinates 260,100.0, 248,192.0, 85.2)
Second Life Server 2024-10-15.11356152186
Release Notes

CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (3411.13 MHz)
Memory: 7897 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.5131)
Graphics Card Vendor: Intel
Graphics Card: Intel(R) HD Graphics 4000

Windows Graphics Driver Version: 10.18.10.5161
OpenGL Version: 4.0.0 - Build 10.18.10.5161

Window size: 1920x1017
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 96m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 134182178MB
Disk cache: Max size 1638.4 MB (3.7% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 15/41,470 (0.0%)
November 27 2024 06:52:49

</p>
</details> 

### Reproduction steps

1. Download and install the Second Life 7.1.11.12041172537 viewer (https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23a90377d-ExtraFPS).
2. Log in to the viewer on a computer with video cards with OpenGL version lower than 4.6 for Windows and lower than 4.1 on OSX.
3. Open the Graphics settings (Preferences - Graphics tab).
4. Click on the ‘Reset to recommended settings’ button.
5. Observe the ‘Quality & speed’ value.

**Actual result:**
The viewer, launched on video cards with OpenGL version lower than 4.6 for Windows and lower than 4.1 on OSX, has default graphics settings as Low+ and does not enable the "Vintage mode" option.

**Expected result:**
The viewer, launched on video cards with an OpenGL version lower than 4.6 for Windows and lower than 4.1 on OSX, should have default graphics settings as Low and enable the "Vintage mode" option.

**Additional information:**
This issue was found during ticket verification (https://github.com/secondlife/viewer/issues/3135) in the scope of [IQA #401](https://github.com/secondlife/iqa/issues/401).
According to the ‘GL3 Fallback and Vintage Mode for Low Graphics’ test plan: 1. GL3 Fallback Mode & Vintage mode enabled - [1.2 Automatic fallback for older Intel cards (super potatoes)](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/3407052804/GL3+Fallback+and+Vintage+Mode+for+Low+Graphics+test#1.2-Automatic-fallback-for-older-Intel-cards-(super-potatoes)).
This issue is reproduced on Win10 (all our MacBooks have OpenGL 4.1).

This issue is reproduced on the current release 7.1.10.10800445603 build (but this is a new feature and was not implemented in the current release build).

This issue is reproduced on Intel HD Graphics 4000 (OpenGL 4.0.0) and ATI Radeon HD 2600 XT (OpenGL 3.3.11672).

Also, accordingly, since the "Vintage mode" option is not enabled by default, the settings in Debug settings also have the value True:
1. Debug > Show Debug Settings > RenderEnableEmissiveBuffer defaults to True
2. Debug > Show Debug Settings > RenderHDREnabled defaults to True

See attached screenshots:
1. Actual - 7.1.11.12041172537 - Radeon
![Image](https://github.com/user-attachments/assets/a3b7b92c-eb49-4d0d-adcd-bede1b9425bf)

2. Actual - 7.1.11.12041172537 - Intel
![Image](https://github.com/user-attachments/assets/e1efc910-2012-472e-9277-12277b4b3f7b)

**Comment by AtlasLinden** [comment]
Note for future testing that the Vintage mode setting is being renamed

**Comment by DmitrySProductengine** [comment]
Failed QA.
Verified on the Second Life Release 7.1.11.12150664210 (64bit) on Win10 in the scope of [IQA #404](https://github.com/secondlife/iqa/issues/404).

The viewer running on video cards (Intel HD Graphics 4000 and ATI Radeon HD 2600 XT) still has the default graphics value of Low+.
<details><summary>7.1.11.12150664210 - Intel HD 4000</summary>
<p>

![Image](https://github.com/user-attachments/assets/b26ab18f-540a-4b48-b936-28fe97139b13)


</p>
</details> 

<details><summary>7.1.11.12150664210 - Radeon HD 2600 XT</summary>
<p>

![Image](https://github.com/user-attachments/assets/483bae41-74a0-4933-ab88-65995bc19417)


</p>
</details> 

But it seems that the logic of the new feature option behavior has changed - now this mode (HDR and Emissive) is disabled for Low and Low+ modes and enabled by default for all modes above (Mid and further).
With this behavior, we can assume that although the viewers on these video cards have the default graphics value as Low+, the HDR and Emissive option is disabled by default - and this may be the expected result for this ticket.

However since the test plan still contains the old name (Vintage Mode) and the behavior of this feature, I decided to fail this ticket.

**Comment by AtlasLinden** [comment]
Thanks Dmitry,
Yes, the new behaviour is now the expected result.
This passes QA. Setting issue status to Pending Release.
