### ISSUE TITLE
Tone Mapping Mix slider broken with PBR skies

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#3170]
### Environment

ExtraFPS 7.1.11.12041172537 

### Description

The Tone Mapping Mix slider is now expected to have no effect on Legacy skies.
However, this is also having no effect on HDR skies
https://gyazo.com/5f8c091d2a3cba322e54e58c315c282b

### Reproduction steps

1. Open a sky with Reflection Probe Ambiance higher than 0
2. Move the Tone Mapping Mix slider in Advanced Graphics

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.12150664210 (64bit) on Win10/OSX in the scope of [IQA#404](https://github.com/secondlife/iqa/issues/404).
