### ISSUE TITLE
[ExtraFPS] Slightly transparent objects invert the color of everything behind them.

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#3234]
### Environment

Second Life Release 7.1.11.12150664210 (64bit)
Release Notes

You are at 233.2, 224.1, 27.2 in Teskylation located at simhost-0ca6a257f17de27d1.agni
SLURL: http://maps.secondlife.com/secondlife/Teskylation/233/224/27
(global coordinates 332,009.0, 305,888.0, 27.2)
Second Life Server 2024-11-25.12013542687
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.91 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.5131)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.6590
OpenGL Version: 4.6.0 NVIDIA 565.90

Window size: 1494x1133
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 8192MB
Disk cache: Max size 1638.4 MB (4.4% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 26/16,761 (0.2%)
December 06 2024 15:10:38

### Description

Found by Kyle Linden.
Slightly transparent objects invert the color of everything behind them.

### Reproduction steps

1. Create a box
2. Make it 2% transparent.
3. Set the Environment to Midnight or right-click the "Midday 4" sky setting in the Library and Apply Only To Myself.
4. Look through the box at content behind it.
 
Observed: The color of content behind the box is inverted.
Image looking at a fullbright green cube at Midnight: ![Image](https://github.com/user-attachments/assets/7639451e-65c7-4987-b8c1-1cb01f7b3e9e)

Expected: The colors should not be inverted, and the objects behind should be barely visible because it's only 2% transparency.

Notes: This may be a clue. If you apply "Midday 4" sky setting, then open Personal Lighting, adjust Reflection Probe Ambiance from 0.01 to 0.02, then back to 0.01, the color inversion is gone.

**Comment by RunitaiLinden** [comment]
Fixed in ExtraFPS.

A scaler that should have been applied to color only was also applied to alpha, making alpha sometimes go above one, which does strange things to blend functions.

**Comment by georgebproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.11.12306234817 (64bit) in the scope of https://github.com/secondlife/iqa/issues/411 on Win10/OSX.
