### ISSUE TITLE
Stars do not render in ExtraFPS unless HDR and Emissive is disabled

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#3248]
### Description

Repro:
1. Set sky to midnight
2. Set quality and speed to Mid
OBSERVE: No stars in the sky.
3. Set quality to Low+
OBSERVE: Starry sky

EXPECTED: Stars should appear regardless of settings.

**Comment by igorlproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.11.12306234817 (64bit) in the scope of https://github.com/secondlife/iqa/issues/411 on Win10/OSX.
