### ISSUE TITLE
Remove obsolete intel driver notification

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#3251]
### Description

When launching the viewer with an Intel HD 4000 on Windows 10, a notification may be popped up that asks you to update your drivers.  This notification doesn't display properly on all systems and can block users from logging in, and no driver update is necessary (or even available in many cases).  

Remove the notification.

**Comment by RunitaiLinden** [comment]
Not sure this is testable without a Dell Latitude E6530 or similar.

**Comment by igorlproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.11.12306234817 (64bit) in the scope of https://github.com/secondlife/iqa/issues/411 on Win10.
This issue was verified on the Graphics Card: Intel(R) HD Graphics 4000.
