### ISSUE TITLE
Fix in-mirror clipping

### ISSUE THREAD

**Issue by Geenz** [secondlife/viewer#677]
Is there a test plan?

**Comment by RunitaiLinden** [comment]
Done.  Should be good to go... if any specific clipping issues show up, please file issues specific to the content in question.

**Comment by DmitrySProductengine** [comment]
Deferred QA.
Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of [IQA #239](https://github.com/secondlife/iqa/issues/239).
Could you please add a test plan?

**Comment by Dan-Linden** [comment]
Closed. Any issues with mirrors should get a new bug.
