### ISSUE TITLE
Add mirrors tickbox to build tools

### ISSUE THREAD

**Issue by Geenz** [secondlife/viewer#679]
### Test plan:
Covered by 2.11 in https://lindenlab.atlassian.net/wiki/spaces/QA/pages/3054436428/Featurettes+Test+Plan#2.11-Mirror-settings-are-present-in-build-floater

Add it per face.

**Comment by Geenz** [comment]
Update on this:
Current UX discussion is leaning heavily towards using the existing reflection probe system to place mirrors, further reinforcing the "hero probe" system and simply making mirrors another update type.

As a result, this means we need a new "probe update type" parameter which defines:
* Static
* Dynamic
* Mirror
These should all be reflected in the build floater.

Existing probe shapes would apply.

**Comment by aiaustin** [comment]
One thing I suggest is that the effect of the Mirror probes is limited to the current land plot of objects it influences. By default at least, even if the size of the Mirror RP object defines the zone of influence , then any spill over into neighbour properties (e.g. on Linden Homes regions) would not be intrusive? might also help in looking at performance if the viewer could ignore nearby but not relevant Mirror RPs.

**Comment by Dan-Linden** [comment]
Please add a test plan.

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of [IQA #239](https://github.com/secondlife/iqa/issues/239).
Section 2.11 of the Featurettes Test Plan is passed without issues.
The feature is also available and works when selecting the face of an object.
