### ISSUE TITLE
Mirrors optimization pass

### ISSUE THREAD

**Issue by Geenz** [secondlife/viewer#682]
Test plan is section 2.9 of https://lindenlab.atlassian.net/wiki/spaces/QA/pages/3054436428/Featurettes+Test+Plan

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of [IQA #239](https://github.com/secondlife/iqa/issues/239).
Section 2.9 of the Featurettes Test Plan is passed without issues.
