### ISSUE TITLE
Fix pixelation on mirrors when RenderHeroProbeResolution is set to 1024

### ISSUE THREAD

**Issue by Geenz** [secondlife/viewer#684]
Test plan is section 2.8 of https://lindenlab.atlassian.net/wiki/spaces/QA/pages/3054436428/Featurettes+Test+Plan

![Image](https://github.com/secondlife/viewer/assets/341813/0ffe818b-dc83-4e55-9e1c-96929c9d3c78)

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/231.
