### ISSUE TITLE
PBR Terrain UI second pass

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#712]
Common sense fixes, plus feedback from Steeltoe on UI behavior

## Test plan

Please see the "Editing Terrain Composition" section in https://github.com/secondlife/viewer/blob/release/materials_featurette/doc/testplans/pbr_terrain_composition.md

**Comment by Dan-Linden** [comment]
Please add a test plan.

**Comment by cosmic-linden** [comment]
@Dan-Linden Added test plan

**Comment by georgebproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/239.
