### ISSUE TITLE
Update Fmod Studio to version 2.02.20

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#716]
Viewer curently uses version 2.02.13 and haven't updated for a while, fmod 2.02.20 acumulated some crashfixes that look relevant.

## Test Plan

verify that aurio works, verify updated version in the 'about' floater

**Comment by georgebproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.3.7790341084 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/118.
