### ISSUE TITLE
Add support for FLAG_MIRROR on reflection probes in the viewer.

### ISSUE THREAD

**Issue by Geenz** [secondlife/viewer#740]
This adds support for "mirror" reflection probes, which transforms a "hero" probe around a virtual plane placed at the center of the reflection probe that always points up on the probe's local Z axis.

## Test Plan
Upon this flag being set on a reflection probe, nearby objects should receive a planar mirror effect applied to them.  For best results, test against a cube with the associated reflection probe placed against one of its faces, and oriented against the face.

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of [IQA #231](https://github.com/secondlife/iqa/issues/231).
Currently, the “mirror” feature is presented in two options in the “Probe Update” dropbox: Mirror (Environment) and Mirror (Everything).
