### ISSUE TITLE
Put PBR material swatch behind feature flag

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#771]
Continuation of https://github.com/secondlife/server/issues/834

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of [IQA #239](https://github.com/secondlife/iqa/issues/239).

Debug settings contain the parameter UIPreviewMaterial.
The default value is false, but the current value in the viewer is true.
When this parameter is disabled, the preview window displays only the base color texture.
When this parameter is enabled, the preview window displays all PBR material.
