### ISSUE TITLE
Fix PBR terrain feature flag

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#773]
Currently, PBR terrain debug setting `RenderTerrainPBREnabled` requires user to manually enable and restart to take effect. This interferes with new server-side feature flag behavior to set the debug setting on the user's behalf.

- Make `RenderTerrainPBREnabled` not require restart
- Respect server-side config
- Update documentation for `RenderTerrainPBREnabled` in settings.xml

## Test plan

See "Feature Availability" in "Editing Terrain Composition" in https://github.com/secondlife/viewer/blob/release/materials_featurette/doc/testplans/pbr_terrain_composition.md

**Comment by DmitrySProductengine** [comment]
Failed QA.
Verified on the Second Life Release 7.1.5.8472515256 (64bit) on Win10/OSX in the scope of [IQA #178](https://github.com/secondlife/iqa/issues/178).
According to the description:
1. Make RenderTerrainPBREnabled not require restart - passed.
The option in World-Region/Estate-Terrain is available after enabling and is not available after disabling.

2. Respect server-side config - passed.
When the option is disabled, it is disabled until login.
When logging into a region with the option enabled (Rumpus Room 2), it is enabled.
When logging into a region with the option (Product Engine Trunk) disabled, it remains disabled.

3. Update documentation for RenderTerrainPBREnabled in settings.xml - failed.
The file 'settings.xml' still states that it requires a restart.
<img width="572" alt="Actual - 7 1 5 8472515256" src="https://github.com/secondlife/viewer/assets/136308794/de8bde8d-3869-4b67-a4ef-06defaad8272">

Perhaps something has changed in the operating conditions of this feature.

**Comment by cosmic-linden** [comment]
@DmitrySProductengine Nice catch on No. 3.

Advanced settings are generally not seen by users, but the due diligence is appreciated.

I also added further clarification on testing, which has been added to the original post of this issue.

**Comment by georgebproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.8.9103842320 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/239.
