### ISSUE TITLE
Do not crash on 'Unable to load basic shader'

### ISSUE THREAD

**Issue by LLGuru** [secondlife/viewer#808]
BugSplat collects different crash reports which actually don't relate to a real crashes:
https://github.com/secondlife/triage/issues/55

These fake crash reports can be grouped by **User Description** which is in fact the error message
https://app.bugsplat.com/v2/keycrash?g0=userDescription&stackKeyId=83464&database=SecondLife_Viewer_2018

The most popular error message is _"Unable to load basic shader"_
If the viewer can't load some shader it displays a message box
![image](https://github.com/secondlife/viewer/assets/124201357/be9bff60-4e2b-40f1-b5eb-01dd11aef617)
and then logs the error using `LL_ERRS()` which explicitly leads to a crash

But if the user is already notified, no needs to crash the process and send the crash report
The viewer could shutdown without sending a crash report

## Test Plan
- Imitate the error locally (delete or rename the shader file if possible),
- Start the viewer
- Verify the message box
- Verify soft shutdown with no crash

**Comment by akleshchev** [comment]
>But if the user is already notified, no needs to crash the process and send the crash report
I think the conclusion on this was: let viewer crash and log to bugsplat for the sake of statistics and because it has a potential to be an shader init issue.
