### ISSUE TITLE
Conversations > Sort participants by recent activity is sorting alphabetically 

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#822]
### Environment

Second Life Release 7.1.3.7821226606 (64bit)
Release Notes

You are at 234.1, 7.3, 30.2 in Hippotropolis located at simhost-0c34b765cfb90231d.agni
SLURL: http://maps.secondlife.com/secondlife/Hippotropolis/234/7/30
(global coordinates 238,570.0, 244,743.0, 30.2)
Second Life Server 2024-01-19.7590161929
Release Notes

CPU: AMD Ryzen 9 5980HX with Radeon Graphics         (3293.82 MHz)
Memory: 15775 MB
OS Version: Microsoft Windows 10/11 64-bit (Build 22000.2538)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon RX 6800M

Windows Graphics Driver Version: 30.0.15020.1001
OpenGL Version: 4.6.14800 Core Profile Context 21.50.20.01 30.0.15020.1001

Window size: 1680x979
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 11474MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 0/49,105 (0.0%)
February 16 2024 13:13:55

### Description

Conversations > Sort participants by recent activity is sorting alphabetically 

### Reproduction steps

1. Open the Conversations window 
2. Open the menu in the Conversations window and ensure "Sort participants by recent activity" is ticked.
3. Go near people that are speaking with voice and text chatting.

Observe: The list of users is always sorted Alphabetically.

Expected: The list of users should be sorted by recent activity, either chat or voice activity.

**Comment by AtlasLinden** [comment]
Issue had been archived. Reopening for testing.

**Comment by igorlproductengine** [comment]
Pass QA.
Verified on the Second Life Release 7.1.7.8993168213 (64bit) OSX in scope https://github.com/secondlife/iqa/issues/226.
