### ISSUE TITLE
[Website Join] join.secondlife.com will not accept legitimate and active  e-mail addresses

### ISSUE THREAD

**Issue by aiaustin** [secondlife/viewer#856]
### Environment

Web site for https://join.secondlife.com/

### Description

Setting up a new avatar at https://join.secondlife.com/ does not allow e-mail addresses. I have tested user@atate.org (my own domain) and user@openvce.net (our main collaboration domain) both of which have been used of Second Life avatars previously. 

Apparently reported before at https://jira.secondlife.com/browse/BUG-233563 

Image attached... replacing the actual user name intended and typed in with xxxxxxxxxxxxx for image only.
![SL-Join-E-mail-Glitch](https://github.com/secondlife/viewer/assets/4630885/39a4e186-1464-4300-8ae0-761aafa8da9a)
![SL-Join-E-mail-Glitch-2](https://github.com/secondlife/viewer/assets/4630885/1e0cf27a-3b3c-4a57-bd5a-e2b685e6cb1d)

There is no feedback on what the issue is, whether its syntax, characters that are not allowed in a legitimate e-mail address or some other reason to allow the user to carry on, so this is a BLOCKER for sign up.

Any e-mail address entered anyway ought to be verified by sending an e-mail to the address and insisting on a response click from that address, to make sure people don't misuse someone else's e-mail in a registration without them being informed.

### Reproduction steps

Try to register a new user at https://join.secondlife.com/ with an address of form user@atate.org or user@openvce.net, and others I assume.

**Comment by nerodevo** [comment]
Same issue with user@proton.me or user@protonmail.com (both domains by same company).

**Comment by aiaustin** [comment]
It may be worth looking at how many people trying to use joon.secondl;ife.com give up at the stage where an e-mail address has to be entered.

**Comment by AtlasLinden** [comment]
Hi Ai!
We use multiple reputation services to validate email domains and unfortunately these domains do not meet our standards for valid email addresses. The workaround is to use a different email domain that is validated. 
The concerns regarding the error message have been passed to the relevant parties.

**Comment by aiaustin** [comment]
Hi... Thanks for passing on the comment on the need to improve the feedback to a user using their e-mail address to join SL and getting stuck at that stage.

Others I am sure are in a similar position with corporate and organisational domains. To help me can you provide the data used to determine these are not valid e-mails as I may need to take steps to fix any issue.
