### ISSUE TITLE
Decrease PBR terrain repeats

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#906]
Bump the PBR terrain repeats back to the levels that the non-PBR terrain uses. This improves consistency, but then 2k terrain can get the higher texel density that people are hoping for.

## Test plan

See, "Tiling Without Texture Transforms" in this test plan: https://github.com/secondlife/viewer/blob/release/2024.06-atlasaurus/doc/testplans/pbr_terrain_appearance.md

**Comment by cosmic-linden** [comment]
Some historical notes:

The current scale for terrain textures, 12, causes seams across region boundaries. There's supposed to be code to fix seams at boundaries by applying an offset to the terrain, but it does not seem to be working.

This seam was undesirable for PBR terrain. The easy solution to it was to decrease PBR terrain scale from 12 to 8, to be a multiple of the terrain width. Then, there was the decision to increase the terrain repeats further to increase texel density. This led to PBR terrain scale to be changed once more from 8 to 4.

That leads us to now: Reverting the decrease in PBR terrain scale, in light of future 2k texture support. Due to the issues with seams at terrain borders when the scale is 12, 8 is a safer choice. Alternatively, I can again attempt to fix the offset code, which would allow for us to use 12 and still not have a seam, and would likely also involve fixing the bug with the terrain repeats jumping on region crossings.

In the interest of time, I will bump PBR terrain scale back up to 8 first. If there is time, I will then again attempt to fix the offsets, but may abandon if no success in a reasonable time.

**Comment by cosmic-linden** [comment]
Ticket for the offset issue: https://github.com/secondlife/viewer/issues/979

**Comment by sergiiiproductengine** [comment]
Could you please provide a test plan for verification?

**Comment by cosmic-linden** [comment]
@sergiiiproductengine Added test plan to original post of ticket

**Comment by brad-linden** [comment]
looks like this may not have gotten verified with the milestone it was supposed to be

**Comment by DmitrySProductengine** [comment]
Deferred QA.
Verified on the Second Life Release 7.1.9.10220184061 (64bit) on Win11/OSX in the scope of [IQA #301](https://github.com/secondlife/iqa/issues/301).

Unfortunately, the link provided in the test plan leads to a 404 page.
https://github.com/secondlife/viewer/blob/release/materials_featurette/doc/testplans/pbr_terrain_appearance.md
<img width="1918" alt="Screenshot 2024-08-07 at 15 30 41" src="https://github.com/user-attachments/assets/cf66f8ab-d185-49a1-b077-402deceac823">

I found a similar file:
https://github.com/secondlife/viewer/blob/brad/materials_featurette/doc/testplans/pbr_terrain_appearance.md

However, confirmation is still required that this test plan is suitable for testing. Maybe something was added to the test plan (which is currently unavailable), so the check may not be performed correctly.

**Comment by cosmic-linden** [comment]
@DmitrySProductengine Updated test plan with link to the doc in the atlasaurus branch. It appears the featurettes branch was deleted, and in any case it would likely be outdated at this point.

**Comment by dmytrohproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.9.10326512121 (64bit) on Win10/OSX in the scope of [secondlife/iqa#306](https://github.com/secondlife/iqa/issues/306).
