### ISSUE TITLE
(viewer only) Give users control over terrain texture repeats

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#907]
### New features

There are new client-only advanced settings for testing PBR terrain repeats (Advanced > Show Debug Settings). The settings are prefixed with "LocalTerrainTransform". At least one of the settings with the prefix "LocalTerrainAsset" must be set to a valid material ID, in order for the repeats to be applied. Since these settings are intended mainly for testing, there is no need to test this extensively. We will have a GUI for PBR texture transforms in the near future, along with an accompanying test plan.

### Regression testing

Make sure the terrain composition still loads: https://github.com/secondlife/viewer/blob/release/2024.06-atlasaurus/doc/testplans/terrain_loading.md

Make sure the terrain composition can still be edited in the floater: https://github.com/secondlife/viewer/blob/release/2024.06-atlasaurus/doc/testplans/pbr_terrain_composition.md

**Comment by cosmic-linden** [comment]
Reduced scope to advanced settings only to get user feedback. Remaining viewer work to set terrain repeats server-side is covered in https://github.com/secondlife/viewer/issues/1475

**Comment by valeriiaaproductengine** [comment]
Deferred QA.

Verified on the Second Life Release 7.1.9.9620320242 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/266.

At the moment (https://github.com/secondlife/viewer/blob/project/gltf_development/doc/testplans/terrain_loading.md) and https://github.com/secondlife/viewer/blob/project/gltf_development/doc/testplans/pbr_terrain_composition.md  links from the Regression testing section open with a 404 error and there is no way to test it. Could you please update the links?

**Comment by cosmic-linden** [comment]
@valeriiaaproductengine Test plan links in OP have been updated

**Comment by AtlasLinden** [comment]
@valeriiaaproductengine please confirm if you now have access to those test plans

**Comment by valeriiaaproductengine** [comment]
Hi @AtlasLinden! Test plans are now available.

**Comment by valeriiaaproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.9.9620320242 (64bit) build in the scope of https://github.com/secondlife/iqa/issues/266 on Win10/OSX.
