### ISSUE TITLE
HDRI Local Preview

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#926]
Add ability to load an EXR off disk and display in place of sky so artists can match lighting between Substance and SL without having to stand on their head and recite the alphabet backwards.

**Comment by AtlasLinden** [comment]
Setting to Pending Release followed by closing as this has already been out in the wild since the promotion of Featurettes 7.1.8.9375512768 
HDRI Local Preview setting is found via Develop>Render Tests and .exr files can be displayed over the sky. 
Verified on both Win10 and Mac
