### ISSUE TITLE
Add a notification appearing when user tries to insert a disallowed character

### ISSUE THREAD

**Issue by LLGuru** [secondlife/viewer#961]
Based on discussion in https://github.com/secondlife/triage/issues/85

In the floater opening by 'World' → 'About Land' user can't insert non-ASCII characters (e.g., emojis) into "My Notes" editor field
This happens because this editor field is stored in the Description of the library object,
but the fields Name and Description don't allow to use non-ASCII characters, and such characters are disallowed to insert

The proposition is to inform user about this limitation to avoid unexpected behavior looking like a bug

## Test Plan

1. Navigate to the user's owned land.
2. Click 'World' → 'About Land' and add any emoji to the 'Description' field.
3. Add a Landmark to the Favorites bar.
4. Right-click landmark on the Favorites bar and click 'View/Edit Landmark'.
5. Click the 'Edit' button in the opened 'Places' floater.
6. Paste the cursor on the 'My notes' field and click 'Win' + '.'.
7. Choose several emojis and close the system emoji floater.
8. Observe the 'My notes' field (no emogi was inserted).
9. Observe a pop-up notification (toast)

**Comment by LLGuru** [comment]
Fixed in https://github.com/secondlife/viewer/pull/968

**Comment by sergiiiproductengine** [comment]
Passed QA.

Verified with 'My notes' and 'Title' fields on the Second Life Release 7.1.4.8333131717 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/163.

<details><summary>actual notification</summary>
<p>
![notification](https://github.com/secondlife/viewer/assets/150452325/17db2d3e-1d73-4376-8fc5-494cc12f5b24)
</p>
</details>
