### ISSUE TITLE
EEP skies too bright after HDRI local preview merge

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#965]
### Description

Observe an EEP sky in GLTF Maint 2 vs Featurettes branch.

Sky is brighter in Featurettes branch.

**Comment by dmytrohproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.5.8472515256 (64bit) on Win10/OSX in the scope of [IQA#178](https://github.com/secondlife/iqa/issues/178).
