### ISSUE TITLE
Featurettes viewer does not start on Mac

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#977]
### Environment

CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (2500 MHz)
Memory: 16384 MB
OS Version: Mac OS X 11.7.10 Darwin 20.6.0 Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64 x86_64
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GT 750M OpenGL Engine

OpenGL Version: 4.1 NVIDIA-16.0.13 

Window size: 1051x716
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 64m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 0
Advanced Lighting Model: Enabled
Texture memory: 2048MB
Disk cache: Max size 1638.4 MB (25.7% used)
HiDPI display mode: 0

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Not Connected
March 12 2024 13:41:40

### Description

The 7.1.4.8208322938 Featurettes viewer does not start on Mac.

### Reproduction steps

1. On a Mac, download the installer from https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23c1bde75-pmfp2
2. Install and run the viewer.

Observed:
<img width="260" alt="Screen Shot 2024-03-12 at 2 28 19 PM" src="https://github.com/secondlife/viewer/assets/119471733/2439df48-5236-4531-b319-fa4a04e36cba">

Expected: The viewer should start.

**Comment by sergiiiproductengine** [comment]
Pass QA.

Verified on the Second Life Release 7.1.4.8270899680 (64bit) on OSX in the scope of https://github.com/secondlife/iqa/issues/156.
