### ISSUE TITLE
[Featurettes] Terrain is blurry on Mac M1

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#989]
<details>
<summary>Environment</summary>
Second Life Release 7.1.4.8270899680 (64bit)
Release Notes

You are at 122.2, 129.3, 26.3 in Bug Island located at simhost-0daa2588c4bff2655.agni
SLURL: http://maps.secondlife.com/secondlife/Bug%20Island/122/129/26
(global coordinates 260218.0, 249473.0, 26.3)
Second Life Server 2024-02-21.7995320426
Release Notes

CPU: Apple M1 (2400 MHz)
Memory: 8192 MB
OS Version: Mac OS X 14.4.0 Darwin 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:06 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T8103 x86_64
Graphics Card Vendor: Apple
Graphics Card: Apple M1

OpenGL Version: 4.1 Metal - 88

Window size: 1440x774
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 96m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 5461MB
Disk cache: Max size 1638.4 MB (58.8% used)
HiDPI display mode: 0

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 0/1617 (0.0%)
March 13 2024 14:19:12
</details>

### Description

Terrain is blurry on Mac (M1). Changing Graphics quality does not fix it.
This issue does not reproduce on Windows.
This issue does not reproduce on Mac OS X 11.7.10 / NVIDIA GeForce GT 750M OpenGL Engine

### Reproduction steps

1. Log in on a Mac with build 7.1.4.8270899680. https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23665d59d-pmfp
2. Look at the texture on Terrain.

Observed: Textures on the terrain are blurry. Other textures are fine.
<img width="1552" alt="observed" src="https://github.com/secondlife/viewer/assets/119471733/676f458e-21b5-4a73-8179-57f951da63f1">

Expected: Sharp terrain textures. 
<img width="1552" alt="expected" src="https://github.com/secondlife/viewer/assets/119471733/067f2a94-a776-4617-b166-42df54ec837a">

[SecondLife.log](https://github.com/secondlife/viewer/files/14594124/SecondLife.log)

**Comment by Dan-Linden** [comment]
This bug does not reproduce on my older Mac, 
OS Version: Mac OS X 11.7.10
Graphics Card: NVIDIA GeForce GT 750M OpenGL Engine

<details>
<summary>Environment</summary>

Second Life Release 7.1.4.8270899680 (64bit)
Release Notes

You are at 120.4, 128.3, 26.3 in Bug Island located at simhost-0daa2588c4bff2655.agni
SLURL: http://maps.secondlife.com/secondlife/Bug%20Island/120/128/26
(global coordinates 260216.0, 249472.0, 26.3)
Second Life Server 2024-02-21.7995320426
Release Notes

CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (2500 MHz)
Memory: 16384 MB
OS Version: Mac OS X 11.7.10 Darwin 20.6.0 Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64 x86_64
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GT 750M OpenGL Engine

OpenGL Version: 4.1 NVIDIA-16.0.13 

Window size: 1051x716
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 96m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 2048MB
Disk cache: Max size 1638.4 MB (0.3% used)
HiDPI display mode: 0

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 0/5367 (0.0%)
March 13 2024 14:54:47
</details>

**Comment by AtlasLinden** [comment]
Passed QA
Verified with M1 Mac on Featurettes build 7.1.8.9375512768
